vmware/load-balancer-and-ingress-services-for-kubernetes

- helm/ako/templates/configmap.yaml
- helm/ako/templates/deployment.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/lib.go
- internal/rest/dequeue_nodes.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/utils.go
- tests/bootuptests/stale_obj_delete_test.go
- tests/integrationtest/lib.go
Simplified the helm chart and forced AKO to set the controller version by querying the SDK if it's not specified.
> Fixing the helm charts + Controller version discovery

- cmd/ako-main/main.go
- go.mod
- go.sum
- helm/ako/templates/configmap.yaml
- helm/ako/templates/deployment.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/rest/dequeue_nodes.go
- internal/retry/dequeue_retry.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/utils.go
- tests/bootuptests/stale_obj_delete_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_route_model_test.go
- vendor/github.com/avinetworks/sdk/go/session/avisession.go
- vendor/modules.txt
This PR, modifies the helm charts to become more readable.
Plus makes the controller version auto-discoverable.
It also implements a slow retry layer in AKO.
The slow retry layer is used only if there's a problem in contacting the Avi Controller. 
We now call AviRestOperate inside a go routine and timeout post 80 seconds.
> Misc fixes

- internal/nodes/avi_model_l7_translator.go
- internal/rest/avi_obj_vs.go
- internal/rest/k8s_utils.go
- internal/status/ing_status.go
- internal/status/route_status.go
- tests/integrationtest/l7_ingress_rest_test.go
- tests/oshiftroutetests/oshift_route_rest_test.go
- don't sync status for dummy vs
- add service metadata in pool for namespace shard
- test cases for duplicate backend in route
- Update status from AviVsCacheAdd only for Post / Delete operation: If we update for put operation, then we may be adding updates which are not required. These should be handled during pool add operations
> additional fixes for status update

- internal/k8s/ako_init.go
We were missing stopping the slow retry queue on sigterm.
This commit takes care of that.
> Stop the slow retry queue on sigterm

- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/rest/dequeue_nodes.go
- statefulset ensures that there is only one pod running at a time if replica count is set to one.
- this would resolve problems which we face because there are multiple pods of ako running at a time
- Also increased wait time for controller response to 300 seconds
Note: serviceName is mandatory in statefulset spec
> moving ako from deployment to statefulset

- Makefile
- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- tests/avimockobjects/ipamdnsproviderprofiledomainlist_mock.json
- tests/bootuptests/bootupmock/ipamdnsproviderprofiledomainlist_mock.json
- tests/integrationtest/lib.go
- This is done to support route53 dns in any cloud.
> Changes to use ipamdnsproviderprofiledomainlist which will make fetching the subdomain generic wrt dns provider type.

- pkg/utils/avi_rest_utils.go
Add back the SetVersion call in AviRestOperate() in the utils package. This
allows individual operations to set Avi version.
> Allow session version to be set during rest operate calls to Avi

- internal/cache/controller_obj_cache.go
Passthrough VS can have multiple PGs, so we need to consider all of them.
> populate pool from all PGs in vs cache during boot up

- internal/cache/controller_obj_cache.go
- This to ease the configuration for the deployment of AKO.
> Validating NodeNetworkMap only if supplied, skipping the validation if empty.

- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/cni.go
- internal/lib/constants.go
- internal/lib/lib.go
Following are the summary of changes for advanced L4 as a part of this
commit:
- Disable VRF related changes  automatically for advanced L4.
- Reduce severity of the dynamic informer initialization problem and
convert to INFO.
- Advanced L4's expectation is to have AKO installed in a namespace
called "vmware-system-ako". We will hardcode it for now.
- CLUSTER_ID honoring.
> Changes related to advanced L4

- internal/lib/lib.go
- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- tests/oshiftroutetests/oshift_route_model_test.go
- vsvip objects should be deleted from cache only if controoler version
is >= 20.1.1 and the VS is not of type insecure passthrough. Else while
deleting the secure passthrough VS, vsvip won;t be pressent in the cache
and vsvip deletion would be skipped
> Do not delete vsvip cache for insecure passthrough VS deletion

- internal/lib/lib.go
- internal/rest/avi_obj_vs.go
- tests/advl4tests/advl4_hostname_test.go
Couple of fixes:
- Modified the logic of parsing the clusterID.
- Added ignore pool reachability to true for advanced L4 to operated
in single arm mode.
> Modifications to clusterID and ignore pool reachability

- pkg/utils/log.go
Otherwise we get an error saying persmission denied if user ID of the pod changes
in oepnshift after reboot
> changed log file permission to enable edit by other users

- internal/rest/avi_obj_vs.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
RemoveListeningPortOnVsDown was applicable for the shared VSes as well.
Due to the current behavior of the avi controller this flag would bring
down the shared VS with insecure pools going down, despite of having
functional SNIs.
Hence this commit restricts the changes to L4 VSes only.
> RemoveListeningPortOnVsDown only for L4 VSes

- internal/k8s/controller.go
- internal/lib/lib.go
This commit takes care of ensuring that AKO does not need any permissions
other than the ones deemed important for advanced L4. Also added a kube
builder annotation for gatewayclass.
> Disable informers and updates to kubebuilder annotation for gwclass

- internal/rest/dequeue_nodes.go
- pkg/utils/log.go
Adding timestamp to log file name, as changing file permission did not fix the issue as per system test report. 
Pass model to ExecuteRestAndPopulateCache for sni vs deletion  …
- If we encounter an error while deleting sni vs, if the model is nil, we would  not refresh the cache
and go on retrying forever, as we don't be able to get avimodel.GetRetryCounter().
- The same problem can also happen if we face error while bootup if avimodel is nil. Not making any change
for this now. We can potentially skip retry here or do a slow retry here.
> Multiples Fixes:  log file name and sni vs deletion error handling

- helm/ako/templates/clusterrole.yaml
- helm/ako/templates/psppolicy.yaml
- helm/ako/values.yaml
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
This includes a psp template needed by AKO and a corresponding
flag in the values.yaml that allows the policy to be used.
The clusterrole is modified as per.
> Allow AKO to work in psp enabled environments

- internal/lib/constants.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/rest/avi_obj_vs.go
This commit ensures that the passthrough secure VS is brought
down if all the pools on it are unreachable and down.
> Bring the VS passthrough secure VS down on pool down

- internal/k8s/advl4_controller.go
- internal/lib/constants.go
- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- internal/status/advl4_status.go
- pkg/utils/types.go
With this we allow PUT requests to vsvip in case of ip address changes, but in case there are vsvip IPAddress change related errors from the controller, they are reported back in the gateway status with reason `InvalidAddress`.
The two strings we look out for as part of those errors are:
- "Changing an existing VIP's vip_id is not supported"
- "If a new preferred IP is needed, please recreate the VIP"
> static IP on vsvip rest layer changes and gw status updates

- internal/cache/avi_ctrl_clients.go
- internal/k8s/ako_init.go
- pkg/utils/avi_rest_utils.go
avi controller clients, earlier were being initialised sequentially, wrapped the initialisation sequence with goroutines.
Please feel free to merge this after the release/review extra carefully :). This affects both AKO/AMKO.
> wrap avi client inits in goroutines for faster bootup

- internal/lib/constants.go
- internal/lib/lib.go
If the SE Group is not supplied as a parameter as in the case
with wcp, default the SE group name to "Default-Group"
> Use default-group for SEG if not specified.

- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/ingress_model_rel.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/dequeue_nodes.go
This commit addresses the issue of unnecessary PUT calls for VS
vip updates during AKO reboot.
Modified the logic of calculating checksum. Thing to note is,
an empty string when done a hash on, results in a non-zero
checksum. This is fixed as a part of the PR.
> Avoid unnecessary PUT calls to the Avi controller for Vsvip updates

- internal/rest/avi_datascript.go
- internal/rest/dequeue_nodes.go
- Do a fast retry on failure due to session expiry
- If any error occurs during execution of a rest call to avi,
then return false to the caller, so that no subsequent requests are made.
Without this change, we may land into a inconsient state. E.g. during clean up
of VSes for passthrough routes, if we get an error in deletion of insecure
passthrough VS, possibly due to session expiry, we would continute with the deletion
of the secure passthrough VS. But deletrion of the vsvip would fail.
On retry, insecure passthrough VS would be deleted, but we would get a 404 as secure
passthrough VS is already deleted, leading to stale pool objects.
> changes in retry logic

- Dockerfile.ako
- Makefile
- cmd/ako-main/main.go
This commit introduces a way by which one should be able to pass
a ldflag argument to AKO and AKO on bootup would print the version.
This will help us recognize the running AKO version.
> Use ldflags to print AKO version

- internal/rest/dequeue_nodes.go
- vendor/github.com/avinetworks/sdk/go/session/avisession.go
Currently we get same response from sdk for both session expiry (401) and 500 error.
Modified sdk code in vendor to get response for 401 error so that it can be handled separately.
> Do fast retry only for 401 error

- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- Instead of passing all the routes of the system to each service, this change filters the routes/ingresses for each l7 service and handles it.
- It also means that the all ingress and routes need not be fetched for each node update. ( node-> ingress ) mapping.
> Optimising the processing of services during node CUD for NodePort mode.

- CONTRIBUTING.md
- go.sum
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/lib.go
- scripts/pre_stop_hook.sh
This Commit addresses: 
1. IF clustername is invalid, do not delete stale VS and objects.
2. Adding header to pre_stop_hook
3. Adding env variable for running ako locally
> AKO Stability Fix for invalid clustername

- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/lib.go
This commit cherry-picks from master:
1. IF clustername is invalid, do not delete stale VS and objects.
> AKO-Stability-issue:

- internal/rest/dequeue_nodes.go
If controller pasword is changed while AKO is running, we can check
the error msg of the HTTP response. We would get this after session gets timed out
with HTTP Response code 401. The error msg would contain the string - Invalid credentials.
Then we would shutdown API server and AKO pod would get rebooted.
> Shutdown API Server if Avi Controller password is changed

- internal/lib/advl4.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/status/advl4_status.go
if an IP address is present on the gateway object, it is fair to assume that the gateway corresponds to a VS in avi
in case the IP is not present, the gateway can be deleted freely since deleting that would be a NOOP for AKO
so we add finalizer when an IP is updated to the gateway, and remove it when we delete the IP address.
The finalizer we attach to the gateway object is `gateway.ako.vmware.com`
This approach takes care of reboot scenarios, updates from the gateway AND service event handler, and of-course layer3 workflows.
> gateway finalizers implementation

- cmd/ako-main/main.go
- internal/k8s/ako_init.go
- pkg/utils/types.go
- pkg/utils/utils.go
- tests/advl4tests/advl4_hostname_test.go
This commit increases the value of informer re-sync period to 12 hours
This value was currently set to 30 seconds, which would mean that the
kubernetes API server would be polled too frequently for full sync.
This commit sets the value as used in the kube api server defaults:
https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/controller/apis/config/v1alpha1/defaults.go#L120
In addition to this, we also restrict the configmap informers to listen on specific namespaces for both advancedL4 and non-advancedL4. This brings down the indexer cache consumption significantly for systems that have huge number of configmaps.
> Increase informer re-sync value and reduction of configmap informer cache

- cmd/ako-main/main.go
- internal/k8s/ako_init.go
- pkg/utils/full_sync_worker.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
- tests/integrationtest/l4_service_test.go
- tests/k8stest/controller_test.go
- tests/multicloudtests/multi_cloud_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
This commit handles a couple of things:
- It will ensure that the Avi VSes aren't bricked if due to some
reason AKO was rebooted and during the first full sync, it couldn't
retrieve either a gateway or a service in advanced L4. These errors
before this commit would lead to a partial object model build up in
layer 2 which could process unintended updates.
- If during bootup of AKO, we are not able to retrieve the configmap
we will return immediately instead of just shutting down the API server
This is required because, the API server shutting down allows the pod
some more time to run till the liveness probe fails. This fix allows
us to shutdown the API server and return to main.
> Don't brick Avi VSes if kube API server is flakey

- internal/nodes/avi_model_advl4_translator.go
- pkg/utils/constants.go
Since advancedl4 is meant to run with the ESSENTIALS Avi license,
changing the network profile to always use System-TCP-Fast-Path
instead of proxy.
> Allow System-TCP-Fast-Path only as the network profile for adv l4

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- internal/rest/avi_obj_vs.go
- tests/integrationtest/l4_service_test.go
This commit introduces a `enableRHI` flag that allows the operator
to setup BGP peering for the virtual services created by AKO as a
cluster wide setting.
> Enable RHI as a AKO wide setting

- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- pkg/api/api.go
- pkg/api/api_fake.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/lib.go
UT for this required a proper FakeApiServer implementation, in which the Shutdown function just marks a flag to true.
> reboot controller in case up_since changes for avi ctrt leader

- internal/nodes/ingress_model_rel.go
- internal/nodes/validator.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/lib.go
This commit makes AKO tolerant to ingresses without backends.
We simply return and not process.
Added a test to verify this.
> Be tolerant to ingresses without backends

- Dockerfile.ako
- Makefile
- tests/integrationtest/l7_ingress_node_test.go
These changes are being done due to the new docker rate limit
imposition on docker pulls. For internal CI frameworks, we would
like to use internal registry of base images for builds.
> Changes to dockerfile and makefile

- internal/nodes/avi_model_l4_translator.go
- internal/rest/avi_obj_vs.go
- tests/advl4tests/advl4_hostname_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
This introduces staticIP support for k8s services objects using the `spec.loadBalancerIP` field
The functionality is similar to how AKO handles static IPs in gateways, wherein updates on the corresponding vsvip objects is not allowed. In order to update the static IP, the Service/Gateway object must be re-created using the new preferred IP.
Errors associated to preferred IP updates are reported to the gateway status conditions, but is not currently possible in case of service objects, although AKO logs the Avi controller API response error.
> static IP support for service LB using spec.loadbalancerIP

- internal/lib/lib.go
> l7 pool name fix for nested paths

- internal/cache/avi_ctrl_clients.go
- internal/lib/constants.go
- internal/lib/lib.go
- pkg/utils/avi_rest_utils.go
In cases where the controller version is greater than 20.1.2, AKO would enforce 20.1.2 as the avi controller api version.
> freeze controller api version to 20.1.2 for advancedl4

- internal/k8s/ako_init.go
- internal/nodes/avi_model_l4_translator.go
- tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
- tests/integrationtest/l7_ingress_node_test.go
Without this change - we may derive a Pool with no server after restart, then add the server again
after processing service from informer update.
> Process service type ClusterIP in full sync if AKO is not running in Adv L4 mode

- pkg/api/models/status.go
https://eli.thegreenplace.net/2018/beware-of-copying-mutexes-in-go/
moved the lock from a nested non-pointered object to the root struct.
Fixes intermittently occurring UT failures http://jenkins_url/job/ako_OS-pr-builder/563/console 
and possible deadlocks
`go vet` run on the file is clear post this, showed warnings earlier
> move lock to StatusModel from nested AviApiRestStatus object

- internal/cache/controller_obj_cache.go
- internal/lib/avi_api.go
- internal/lib/cni.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/crd_translator.go
This PR adds retry logic for API calls from controller_obj_cache (fullsync) and crd_translator (CRD validation)
Also removes the pathType BEGINS_WITH implementation enhancement for httpPolicies
> add retry for crd/populate cache api calls for 401s, pathType prefix fix

- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/nodes/validator.go
- internal/objects/ingress_to_service.go
- internal/status/statefulset_status.go
- pkg/utils/constants.go
- pkg/utils/utils.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- If key/cert is not specified on TLS route, then a secret named router-certs-default would be used.
- This secret should be presesnt in avi-system namesapce.
- So support this, routes are now stored as namespace/routename per secret.
- Similarly secret per route is being stored as namesapce/secretname.
> Support for using default secret for TLS route if cert is not specified on route

- internal/nodes/crd_translator.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
mostly syntactic sugar. Removed the `removeVSNodeRefs` function and handling the delete CRD cases inline in `BuildL7HostRule` and `BuildPoolHTTPRule`. No change in workflow
> cleanup code for crd_translator removeRefs, additional UT tests

- internal/cache/controller_obj_cache.go
- internal/rest/avi_obj_vs.go
- AKO will auto-allocate the ip from the list of usable networks.
> Supporting multiple usable networks as a part of the IPAM by skipping validation for network_name.

- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/status/statefulset_status.go
- tests/oshiftroutetests/oshift_crd_test.go
The type of the condition is now ako.vmware.com/ObjectDeletionInProgress, which signifies if AKO is deleting all Avi Objects. The value of status would be True only when the delete operation is in progress, else it would be set False. In case of an error like timeout, it would be set to unknown. 
- The status of this condition would be set to true after setting deleteConfig to true, before starting all object deletion.
- The reason would be set to ObjectDeletionStarted.
- The status would be set to false when all objects gets deleted.
- The reason would be set to ObjectDeletionDone.
For example:
Status condition before deletion:
- lastTransitionTime: "2020-12-15T10:10:45Z"
message: Started deleting objects
reason: ObjectDeletionStarted
status: "True"
type: …
> Change in AKO statefulset status condition message

- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
We can use both controller IP and hostname to connect to Avi Controller.
Renaming the field in values.yaml to reflect this.
Internal keynames are being kept unchanged.
> Renaming controllerIP to ControllerHost in helm values.yaml

- pkg/utils/ingress.go
networking v1beta1 IngressClasss is enabled in clusters prior to k8s-1.19 as well.
This PR enables ingress class functionality in AKO only when networking/v1 IngressClass is present and can be listed via the client api call.
This was already taken care in helm where we specifically check for networking/v1 IngressClass capability.
> enable ingress class workflow onlly for networking/v1 IngressClass enabled cluster k8s-1.19+

- internal/lib/lib.go
- internal/rest/avi_obj_vs.go
This includes/extends static IP vsvip configuration to public cloud types. Prior to this public cloud and staticIP vsvip implementation was exclusive of each other.
This also involves a major cleanup in the AviVsVipBuild function, to make it more readable, trimmed it down a bit for easier logical workflow.
I have intentionally kept the two commits separated out, where the first one just focuses on providing better readability, and the second one fixes the bug reported AV-102214
Since there have been multiple authors for this block of code, lets merge it when all you guys approve it @parimanur @monotosh-avi @sudswasavi 
Please try checking for all the use cases, including the fix introduced in the second commit
> avi_obj_vs AviVsVipBuild cleanup, fix AviVsVipBuild static IP usecases in public clouds

- internal/nodes/crd_translator.go
In previous versions of AKO, vsHTTPPolicySets was being initialized in BuildL7HostRule.
Bringing this back to avoid any checksum change.
> Initializing fields of VS to avoid checksum change during upgrade 

- internal/status/svc_status.go
This commit removes the need for a hostname to be present for the
service of type LBs status update.
This allows AKO to update the service object's status even if the
IPAM DNS profile is not configured in the Avi controller.
> Remove dependence on hostname for l4

- internal/rest/avi_obj_vs.go
This commit will unblock usage of Avi essentials license where RHI
is not supported in the VS payload.
If RHI is set to true only then, we set it in the VS object,
for all other cases RHI is not set in the payload but defaulted
to false by the go sdk.
> Only set RHI flag if it's set to true

- internal/k8s/ako_init.go
- internal/rest/dequeue_nodes.go
After setting deleteConfig to true, update statefulset status even if no VS object has to be deleted.
Make sure this works, by checking if the model is empty and updating status after VRF update is done.
> Update statefulset status even if no VS has to be deleted

- .github/workflows/go.yml
This limits the action to run on pull requests only, action on push is not required.
> remove lint action on push to master branch

- internal/k8s/ako_init.go
- internal/rest/dequeue_nodes.go
After setting deleteConfig to true, update statefulset status even if no VS object has to be deleted.
Make sure this works, by checking if the model is empty and updating status after VRF update is done.
(cherry picked from commit a89c73b34cb7988a956406d9f7ed45a3f7984fe1)
> Update statefulset status even if no VS has to be deleted (#246)

- internal/lib/avi_api.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/objects/ingress_to_service.go
- internal/status/advl4_status.go
- internal/status/crd_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/services_api_status.go
- internal/status/svc_status.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/integrationtest/ingressclass_test.go
- tests/integrationtest/l4_l7_namespace_shard_nodeport_test.go
- tests/integrationtest/lib.go
Changing the controller in an existing IngressClass has not been covered in the UTs (the way it was covered for GatewayClass), since the action is blocked by k8s.
This also fixes two issues in IngressClass/Ingress with 
1) relating to removing cache mappings: ingress removal was not happening properly in ingressClass/ingress cache mappings
2) namespace shard VS naming: shard VS name was getting calculated based on IngressClass namespace ("")
> IngressClass/Ingress UTs, namespace shard and cache mapping fixes

- internal/k8s/advl4_controller.go
- internal/k8s/controller.go
- internal/k8s/services_api.go
- internal/nodes/crd_translator.go
- internal/rest/avi_obj_vs.go
- internal/status/advl4_status.go
- internal/status/crd_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/services_api_status.go
- internal/status/svc_status.go
This commit sanitises some of the status package logs and makes sure that we pass and log the REST layer keys to the logs.
> passing cache layer keys to status update calls for logging

- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/objects/npl.go
- internal/rest/avi_obj_pool.go
- pkg/utils/constants.go
In this first set of changes, addition of pool servers from NPL annotation
of Pod is handled.
- A new service type NodePortLocal is introduced. When this is set,
servers would be populated from NPL annotation of POD.
- New PodInformers would be started only when this flag is set.
- New store objects are created to store NPL annotation per pod, and
mapping between Pods and Services.
Not handled in this set of changes:
- Automatic annotation of services from ingresses for NPL
- Mapping between gateway and POD
- CNI verification
> Introducing NodePortLocal in AKO

- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
The typo causes the controller settings to be set to empty, which in turn makes the ako pod fail to detect the controller.
> Fix typo in sample AKOConfig

- helm/ako/crds/nsxalbinfrasettings.yaml
- helm/ako/templates/clusterrole.yaml
- tests/oshiftroutetests/oshift_crd_test.go
This makes two fixes:
- Removes `network` being mandatory field.
- Corrects the schema for the `network` section of the CRD
> Fix nsxalbsetting CRD

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_translator.go
This commit intorduces the following changes:
- Allows an option to disable FQDN generation for L4 VSes.
- Allows specification of formats for FQDNs for L4.
- Allows specification of an annoation to generate custom FQDNs for L4 VSes.
Also removes the code that auto-generated the default FQDN for Shared VS for L4.
> Introduce L4 DNS formats etc

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_translator.go
- tests/oshiftroutetests/oshift_crd_test.go
This commit intorduces the following changes:
- Allows an option to disable FQDN generation for L4 VSes.
- Allows specification of formats for FQDNs for L4.
- Allows specification of an annoation to generate custom FQDNs for L4 VSes.
>  Introduce L4 DNS formats etc (Cherry-picked)

- hack/update-codegen-akocrd.sh
- helm/ako/crds/nsxalbinfrasetting.yaml
- internal/apis/ako/v1alpha1/nsxalbinfrasetting.go
- internal/apis/ako/v1alpha1/register.go
- internal/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/ako_client.go
- internal/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_ako_client.go
- internal/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/fake/fake_nsxalbinfrasetting.go
- internal/client/v1alpha1/clientset/versioned/typed/ako/v1alpha1/nsxalbinfrasetting.go
- internal/client/v1alpha1/informers/externalversions/ako/v1alpha1/interface.go
- internal/client/v1alpha1/informers/externalversions/ako/v1alpha1/nsxalbinfrasetting.go
- internal/client/v1alpha1/listers/ako/v1alpha1/expansion_generated.go
- internal/client/v1alpha1/listers/ako/v1alpha1/nsxalbinfrasetting.go
- internal/k8s/ako_init.go
- internal/k8s/services_api.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/rest/avi_obj_vs.go
- tests/integrationtest/lib.go
- tests/servicesapitests/servicesapi_l4_test.go
This introduces indexers to fetch corresponding GW/Services and push to layer 2.
Implements configuring ServiceEngineGroup for Gateway VSes, Network configuration
will be part of a subsequent PR.
This PR also fixes the NsxAlbInfraSetting client sets/listers/informers to be non-Namespaced.
Minor log consistency fixes in ingress_model_rel.go
> NsxAlbInfraSetting implementation init

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- pkg/utils/constants.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/lib.go
This PR adds support for the [EVH](https://avinetworks.com/docs/20.1/enhanced-virtual-hosting//) in AKO. 
- Introduces enableEVH flag which is currently set to false.
- Listing down overall scenarios tested for L2 changes.
- Create Insecure and secure ingress and check if there are no Pools and PoolGroups created for the shared VS
- Check that the model populated is of AviEvhVS when EVH is enabled.
- Create and edit multiple hosts + multiple Path + and editing of secret and check if model is updated appropriately.
- All the existing L2 layer tests are added with Evh Enabled but the validations differ.
> Graph Layer Changes to support EVH model in AKO.

- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_pool_group.go
- internal/rest/dequeue_nodes.go
- internal/rest/ssl_key_certificate.go
Adding GRBAC support for AKO.  Enabling default support for controller version 20.1.2 and above. GRBAC will come into picture if user is associated with labelled role.
> Granular RBAC support with AKO

- internal/nodes/crd_translator.go
- internal/nodes/dequeue_ingestion.go
AKO CRDs should not allow users to refer to Avi Objects that have been previously created by the AKO instance running in the same cluster. While checking for object presence in Avi, this checks for created_by field, which should not be equal to AKO user.
Additional commit that solves a UT failure seen on a previous run. http://10.79.111.162:8080/job/ako_OS-pr-builder/827
> Prevent object references created by current AKO instance

- helm/ako/templates/ingressclass.yaml
`defaultIngController` in helm values.yaml is of type string. While we add the default ingress class annotation `ingressclass.kubernetes.io/is-default-class` assuming that the value is a boolean. This ends up making Avi IngressClass default even if the value set is `"false"`.
> fix ingressclass template for defaultIngController

- internal/nodes/dequeue_ingestion.go
- internal/objects/npl.go
- internal/status/svc_annotation.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- Setting value for NPL annotation key to nil
- Instead of returning podLBSvcInstance podSvcInstance was being returned in SharedPodToLBSvcLister, fixed this.
> Fix problem in deleting NPL annotation from Service

- helm/ako/templates/clusterrole.yaml
- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/services_api_status.go
- internal/status/svc_status.go
Piggybacks on the objects' status updates. Once a call to update the
status for a route/ingress/LB service is made, first the status is
updated and then the annotations are updated.
- Sets the UUID for the virtualservice to which the object is mapped
to, in the `UpdateOptions`.
- Call to update the annotations is made. For route/ingress annotations
updates:
* Update the VS uuid for the hostname in the current update context.
* Remove the non-required hostnames from the annotations.
* Check if a patch is required (by comparing with the previous
annotations).
For LB service annotation updates:
* Just update the VS uuid for the hostname.
* Compare the new annotation with the previous one and update if
required.
This PR also fetches the controller cluster's UUID and sets it in the
objects' …
> Update vs uuids in the object annotations

- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/nodes/dequeue_ingestion.go
This commit introduces a flag that would allow AKO to function as
a pure Layer 7 ingress controller. This flag should be used where
AKO isn't needed for layer 4 functionality. Note, this flag can be
only set during AKO bootup and cannot be changed while the AKO pod
is already in running state.
If the system had layer 4 LBs synced as virtual services, AKO would
delete those if the flag is set to `true` and AKO is rebooted.
> Allow AKO to function as a pure layer 7 ingress controller

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/controllers/akoconfig_controller.go
- ako-operator/controllers/configmap.go
- ako-operator/controllers/utils.go
Additional changes include:
- Update the status field to include the current state of AKO controller
deloyment (including manifest deployment errors).
- Use `FormatBool` to convert to string.
> Update the AKOConfig object with layer7only flag

- internal/nodes/ingress_model_rel.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_crd_test.go
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
Services whcih are ingress backends should only be annotated with NPL annotation,
only if the ingress is valid as per ingress class filtering through validateIngressForClass()
- Updating ingress-service map only if the ingress has valid ingress class. This is unlike the current
method, where we populate this map irrespective of Ingress Class.
- Upon Ingress Class update, repopulate this map and update corresponding service annotation.
> Update NPL annotation in Service based on Ingress Class

- helm/ako/values.yaml
- internal/cache/avi_ctrl_clients.go
- internal/k8s/ako_init.go
- internal/lib/lib.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/dequeue_nodes.go
- tests/integrationtest/lib.go
This commit introduces another ENUM value for the SHARD_SIZE called
DEDICATED. If this value is set, then AKO will create a dedicated
virtualservice per FQDN. If there are multiple paths configured
for the same FQDN across multiple ingress objects, then AKO would
create a single virtual service for the FQDN and patch all the paths
to the same VS.
> Introduce dedicated VS for ingress FQDNs

- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- If the test NS is not cleaned up properly then it can create problem in multi NS tests
> cleanup test namespace in oshiftroutetests

- ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
- helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
- internal/nodes/ingress_model_rel.go
- internal/status/ing_status.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
- tests/integrationtest/ingressclass_test.go
- tests/integrationtest/l7_ingress_node_test.go
- tests/integrationtest/l7_ingress_rest_test.go
Changing the default ingress class annotation in Avi ingress class was not removing the VSes/Pools from Avi and does not remove status from the ingress objects. This PR fixes this issue.
This also includes a related ingress status update fix wherein the status is removed only when host is removed from the spec. But with new additions of namespace selector and ingress selection via ingress class, the status can be removed from ingress even when the host is still present in the spec. The check for the same has been removed from the workflow.
> fix default ingressclass transitioning issues

- internal/nodes/avi_model_evh_nodes.go
- internal/rest/avi_evh_obj.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
- DEFAULT_L7__APP_PROFILE is used for secure and insecure ingresses for the EVH Vs.
- The redirect policy should be bound to the child EVH VS instead of the Parent.
- Removed ServiceMetadata information from pool as it was causing a race in status update for insecure ingress path update.
Tested the secure, insecure and the CRD usecase with this change.
> Fixing the ApplicationProfile and associating the redirect policy for EVH child VS.

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/k8s/services_api.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/validator.go
- pkg/utils/utils.go
This PR has changes for:
1. L4 namespace sync for Service API
2. Few code corrections.
@sudswasavi @chauhanshubham : Recently, K8 Upstream changed project name from ServiceAPI to GatewayAPI.  I think we should also reflect out that change in our code base. (https://github.com/kubernetes-sigs/gateway-api).
> L4 Namespace Sync for GatewayAPI/ServiceAPI services

- Makefile
- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/rest/avi_obj_httpps.go
- internal/rest/dequeue_nodes.go
- tests/misc/temp_sni_to_pool_test.go
- tests/temp/temp_sni_to_pool_test.go
Currently http caching is not supported on PoolGroups. This means
that if customers had a httppolicyset refer to a PG instead of a pool,
then this feature cannot work.
This commit addresses this concern with an interim fix that removes the
poolgroup references from the httppolicies and instead references the pools
directly. This flag is not recommeded for use unless http caching is
required because removing Poolgroups would prohibit us from using
canary flows. Hence these are the restrictions of the commit:
- Only works for SNI VSes (no other thing, not insecure, nor EVH).
- Will be deprecated once the Avi controller builds the http caching
functionality on poolgroups.
- Flipping the flag to `true` in a running AKO setup will not take
effect unless AKO is rebooted. Some stale PGs could …
> Temporary support for http caching via pools

- internal/lib/lib.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/ingress_model_rel.go
- internal/status/ing_status.go
- internal/status/route_status.go
Without this fix we may delete an ingress status on path update, if
the pool for old path gets deleted in the end after addition of new pool.
> skip status deletion for Ingress if hostname is present in spec

- internal/status/ing_status.go
- internal/status/route_status.go
This PR take cares of not deleting FQDN-vsuuid map from ingress annotation if host/fqdn is present in ingress host rules.
> Do not delete FQDN-vsuuid map from ingress annotation if host is present in ingress

- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
- internal/rest/rest_utils.go
- internal/rest/ssl_key_certificate.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
Currently if we get an error in rest layer, then all other requests mapped to the
same shared VS are skipped. This leads to a scenario where problem in one ingress affects
other ingresses mapped to the same shared VS.
In this PR, not all requests are skipped in case of an error.
- If the failed request was anything other than POST call then we ignore the error and coninue.
- IF the failed request was POST then we attempt to remove its reference from other objects, then continue.
Also as part of this PR macro calls have been removed. In the current model it doesn't provide
any extra benifit as one macro call contains ony one request.
> Handle error in rest layer to sync requests from multiple K8s objects

- ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
- helm/ako/crds/ako.vmware.com_httprules.yaml
- internal/nodes/avi_model_nodes.go
- internal/nodes/crd_translator.go
- internal/rest/avi_obj_pool.go
- pkg/apis/ako/v1alpha1/httprule.go
- tests/servicesapitests/servicesapi_l4_test.go
This adds the ability to configure custom application Persistence Profile to Avi Pools via AKO's HttpRule CRD.
> configure applicationPersistenceProfile via HttpRule

- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
- pkg/utils/constants.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/integrationtest/lib.go
If a GSLB host header is specified in the HostRule CRD and the FQDN
is insecure then this commit introduces a way by which AKO programs
a URL re-write rule as a httppolicyset on the shared VS.
When the GSLB request is made to the global FQDN the request would
land on the VS which hosts the local FQDN. The HTTP re-write rule
would then modify the request header to the cluster local host header.
Following this, the header (which is the local host header) would be
matched with the local pools priority labels via the datascript.
This change requires a datascript change which is only available
with 20.1.4 and hence couple of things happen:
- This feature only works with 20.1.4 and above controllers.
- On switching the controller to 20.1.4 and starting an AKO during
upgrade would auto-matically …
> Introduce GSLB host header re-write for insecure hosts

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/nodes/route_ingress_model.go
- internal/objects/infrasetting.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/servicesapitests/servicesapi_l4_test.go
This commit introduces modelName generation based on AviInfraSetting CRD, and derives the shardVsName via the shardSize mentioned in the AviInfraSetting CR. To simplify transition cases between valid AviInfraSetting CRs, the Avi object names now include AviInfraSetting Name as well.
> Layer7 AviInfraSetting shardSize based modelName

- internal/k8s/ako_init.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/dequeue_ingestion.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/servicesapitests/servicesapi_l4_test.go
AviInfraSetting provides a way to configure ShardSizes for Shared VSes created by AKO. This PR facilitates modifying shardSize via the AviInfraSetting CRD for VSes created in EVH mode. In case of a shardSize change, the objects map to a differently named graph model, and objects from the old model are removed in  layer 2.
This commit also removes a few naming schemes that were previously used in namespace shardScheme.
> AviInfraSetting shardSize configuration for EVH VSes

- internal/lib/constants.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/crd_translator.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/integrationtest/l4_nodeport_test.go
- tests/integrationtest/lib.go
This PR introduces a new annotation called skipnodeport. In scenarios
where the global `serviceType` is set to `NodePort` the NodeIPs are
processed as Servers inside the Avi pool.
But in case, the user wants to skip these nodeports for such Services
and instead rely on an Endpoint object for the servers, the services
could be annotated with:
skipnodeport.ako.vmware.com/enabled: "true"
If this is set on a service, then AKO will look for the actual endpoint
object to figure out the servers for the pools instead of deriving the
nodeport info.
It is the responsibility of the network admin to ensure that the endpoints
are routable from the Avi Service Engines since static routes will be
skipped if service is set to NodePort.
This annotation will only work for nodeport mode. If the serviceType …
> Introduce skipnodeport annotation

- cmd/ako-main/main.go
- internal/lib/lib.go
- This prevents a case where due to a temprary network issue, we can't recognise an openshift cluster
> Check if AKO can access API of Service before checking Route API

- cmd/ako-main/main.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/k8s_utils.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/status_toiler.go
- pkg/utils/constants.go
- pkg/utils/queue.go
- pkg/utils/types.go
- tests/advl4tests/advl4_hostname_test.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/k8stest/controller_test.go
- tests/multicloudtests/multi_cloud_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/servicesapitests/servicesapi_l4_test.go
Currently function for updating and deleting status are called directly from rest layer.
This means multiple threads of rest layer may try to update the same object simultaneously,
To avoid this race condition, introducing a queue where objects would be added for status update,
which would be dequeued and processed later.
Unlike other worker queues in AKO, for status udpate we can not use only the key, hence the complete
object is added in the queue.
> update status of k8s objects through a queue

- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
This commit introduces a knob called GRBAC in the configmap
to switch off granual RBAC feature optionally.
Once this flag is set to true, the feature is turned out.
The feature is only supported with Avi controller version
20.1.5 and will be depcrecated in 20.1.4
> Provide a knob to switch off granular RBAC support

- Makefile
int_test target is changed to run all the UTs simultaneously.
This is reducing the PR builder time from 37 min to 20 min.
> Changing the make to execute many recipes simultaneously.

- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
Changes in rest layer to use Markers instead of Labels.
> cherry-pick, Disable GRBAC if avi controller build is less than 20.1.5. (#362)

- internal/rest/rest_operation.go
This commit includes 401 into the retryable errors. One may hit
this error when the sessions become stale. Hence we need to re-enqueue.
> Add session timeouts into retryable errors

- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
As part of this PR, httppolicysets of same VS are sorted in ascending order of path.
Changes has been done for SNI and EVH models.
> Fix issue related with ordering of httppolicysets of VS having same host with different Paths for Openshift route, K8 ingress

- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/rest/dequeue_nodes.go
- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
This PR addresses the issue wherein AKO reboots right after
virtualservices are deleted from Avi, during object deletes,
leaving status updates incomplete. During such scenarios, AKO
should correctly remove the status (IPaddress/finalizers/annotations)
from objects whose corressponding VSes have been deleted from Avi.
> fix status sync for status removal during reboot

- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/rest/dequeue_nodes.go
- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
* fix status sync for status removal during reboot
This PR addresses the issue wherein AKO reboots right after
virtualservices are deleted from Avi, during object deletes,
leaving status updates incomplete. During such scenarios, AKO
should correctly remove the status (IPaddress/finalizers/annotations)
from objects whose corressponding VSes have been deleted from Avi.
* check for ingress class enabled
> cherry-pick: fix status sync for status removal during reboot

- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
This commit removes the SE group labels configured for the AKO cluster.
This operation is carried out if `deleteConfig` is set to `true`.
The operation is only done for the label added for the cluster.
In order for this change to take effect, the existing SEs have to
be rebooted or new SEs have to be created within the SE group.
> Remove SE group labels on deleteConfig

- internal/status/ing_status.go
- internal/status/svc_status.go
This PR ensures that AKO annotations are completely removed
in case when deleteConfig is set to `true` or in cases when the
no hosts in ingress/routes have a corresponding VS in Avi.
> remove AKO annotations completely from ingress/routes if present with stale values

- internal/status/ing_status.go
- internal/status/svc_status.go
(#388)
This PR ensures that AKO annotations are completely removed
in case when deleteConfig is set to `true` or in cases when the
no hosts in ingress/routes have a corresponding VS in Avi.
> cherry-pick: remove AKO annotations completely from ingress/routes if present with stale values

- internal/cache/controller_obj_cache.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_datascript.go
The vsdatascriptset checksum calculation was inconsistent for graph nodes and the rest cache layer, 
that lead to multiple PUT calls. The rest layer checksum calculation did not involve replacing the datascript
string with the proper pool group name (in place constant POOLGROUP) that lead to different checksums.
> fix wrong script addition for checksum calculation

- internal/status/ing_status.go
This fixes a boot up issue where we face segmentation fault while deleting status
for multi host ingress.
> Use correct index while deleting Ingress status

- cmd/ako-main/main.go
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_tls_passthrough.go
- tests/bootuptests/stale_obj_delete_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/k8stest/controller_test.go
- tests/multicloudtests/multi_cloud_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/servicesapitests/servicesapi_l4_test.go
- tests/temp/temp_sni_to_pool_test.go
Currently there are two ways to specify vip network - vipNetworkList for AWS and
networkName for others. Removing networkName to use vipNetworkList for all cases.
But vipNetworkList can contain multiple entries only for AWS.
> remove networkName and use vipNetworkList for all clouds

- ako-operator/controllers/akoconfig_controller.go
- ako-operator/controllers/role.go
- ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
AKO Operator changes : 
- Added aviinfrasettings permissions to ako-cr and ako-operator-manager-role clusterrole 
- Updated Reconcile function to avoid stale objects for FT verifications.
> AKO Operator clusterrole change, Changing Update call to Patch in Reconcile

- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_nodes.go
In the rest layer we take lock and get a copy of the model.
But in layer2 we were not always taking a lock before updating the models.
This was figured out by using -race flag while building the binary object.
To fix this, added a lock in calculateChecksum and sniNodeHostName function.
> Fix for race conditons for updating avi model in graph layer

- internal/nodes/avi_model_l4_translator.go
- tests/npltests/npl_pod_test.go
If an ingress is referring a multi port service then we must check if portname
mentioned in the ingress spec matches with the service port
(cherry picked from commit 2e7d2b2d1d37bd6d30155a0ac8d3fabf4fb4c648)
> match portname for multi port service while populating servers for NPL

- internal/lib/lib.go
- internal/status/ing_status.go
In this time, the informers are not initialized yet.
(cherry picked from commit 07a6c7dc857865842854d261f708f7fb0be16189)
> Use kubeclient instead of informer to fetch ingress class for status update during bootup

- internal/cache/controller_obj_cache.go
While populating http policy in cache we check for the ref type in SwitchingAction.
But not all rules contain SwitchingAction, for which we get a panic because we try to process a nil value.
> Process SwitchingAction in http policy rule only if it contains SwitchingAction

- internal/rest/avi_evh_obj.go
Due to default pg reference, evh child was responding to each and every request.
With this change, evh child will responds to only path for which it has corresponding pgs.
> Removing default pool group reference from EVH Child.

- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
Required for Avi Essentials and Basic licensing where setting the value
to False is not allowed by the Avi Controller.
> keep EnableRhi nil if not set to true

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/objects/crdrules.go
When a hostrule is detected with a GSLB FQDN and it is for a secure
FQDN, a re-direct rule is attached on the shared VS for the GS FQDN.
The same is removed if:
- The hostrule is removed.
- If the ingress is deleted.
- If the gs fqdn is dynamically changed in the hostrule.
> Add/Remove HTTP redirect rules for gslb fqdn

- internal/rest/avi_obj_vsvip.go
using networkName instead of index results in same network multiple times because we are using a pointer.
> Use index while accessing network from networkList in rest layer for AWS multiVip

- internal/k8s/controller.go
This commit would allow AKO to listen on endpoint updates even in
nodeport mode. This is needed because if someone uses the skipnodeport
annotation and update endpoints, we need to read those endpoint
object updates and accordingly update the pool servers.
> Allow listening to endpoint updates in NodePort mode

- Makefile
- internal/lib/constants.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
- tests/advl4tests/advl4_hostname_test.go
- tests/oshiftroutetests/oshift_route_passthrough_test.go
If we get an error in rest layer when no free IP is avialable, then
retry forever until a free IP is avialable. Usually users can increase
avialable IP range and then after sometime the VsVip would get a free IP automatically.
> Slow retry forever on error - No available free IPs

- internal/rest/dequeue_nodes.go
- internal/rest/ssl_key_certificate.go
This PR fixes
1. Continuous  post for SSLkeyandcertificate even continuous 409 errors are there in retry layer for that sslkeyandcertificate 
2. Continuous delete call for AVI Objects even 404 error are there in retry layer.
This fixes S1 issue AKO: AKO continuously does POST for sslkeyandcertificate and fails to configure all VS.
> Fixing Continuous POST calls for sslkeyandcertificate in 409 error and DELETE calls for other AVI objects in 404 error

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- helm/ako/templates/statefulset.yaml
- tests/ingresstests/l7_graph_test.go
This was incorrectly set as bgpPeerList
> fix configmap key reference for bgpPeerLabels

- Dockerfile.ako-operator
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/controllers/akoconfig_controller.go
- ako-operator/controllers/configmap.go
- ako-operator/controllers/utils.go
Instead of relying on the in-memory object map, just fetch all the
related artifacts and delete them.
Also includes a cherry-pick for status updates of `AKOConfig` object.
> Fix for ako artifacts cleanup issue and a cherry-pick

- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
This PR handles following objects:
1. Ingress
2. Routes
3. Gateway
4. LB Service
5. Advance LB service
For services and routes, we do not have gated condition other than namespace sync feature to use.
So if namespace sync feature is disabled, we will reset status of all services and routes, irrespective whether it is handled by AKO or not.
That is not case with Ingress, gateways, as it has specific class which is only handled by AKO.
> Do not perform bulk status update on resources of un-accepted namespaces when namespace sync feature is enabled.

- internal/nodes/avi_model_evh_nodes.go
- tests/ingresstests/crd_test.go
- tests/npltests/npl_pod_test.go
In the rest layer we take lock and get a copy of the model.
But in layer2 we were not always taking a lock before updating the models.
A similar fix was done for shard vs model already.
> Fix for race conditons while updating avi model with for EVH

- Dockerfile.ako-operator
- ako-operator/PROJECT
- ako-operator/config/default/kustomization.yaml
- ako-operator/config/manager/manager.yaml
- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
- ako-operator/controllers/akoconfig_controller.go
- ako-operator/controllers/utils.go
Also, AKO Operator would now update the status of AKOConfig as soon as
it boots up (this is to make sure that the scorecard test of checking
the status update before the 60s timeout works). For this, we also
need to make sure that the AKOConfig status update doesn't prompt a
reconcile request and hence, we now use a predicate to avoid such
calls.
And, this also removes a spurious log.
> Upgrade AKO Operator's SDK version to 3 from 3-alpha

- internal/k8s/controller.go
- internal/lib/crd.go
This allows AKO to not get stuck while trying to initialize informers
for the CRDs, in case the CRDs are not installed on the cluster
Fixes #456
> unblock AKO run if CRDs are not installed in cluster

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
This PR adds supports for the NSX-T cloud in AKO.
The user needs to specify the backend network's T1Lr mapping as a
config option in the values.yaml on which the Service Engine would
create the backend network.
> Support NSX-T cloud in AKO

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
- internal/status/route_status.go
- tests/oshiftroutetests/oshift_secure_route_test.go
add UT corresponding to it that creates separate routes (reproducible
in case of ingresses too), with same host but differrent paths, and
then deletes one of the routes forcing a SNI pool delete. AKO does not
let graph nodes proceed to rest layer, unless the graph checksum changes,
(see saveAviModel) so for any changes whatsoever, the graph checksum must
change. This would lead to irrelevant PUT calls on the parent VS.
Fixes AV-116457
> add child node checksum to vs checksum calculation

- Makefile
- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- internal/status/crd_status.go
This also adds a pre-build sync-crd-files target in the Makefile
that should run before the build target and sync the CRD files to
the ako-operator helm directory.
Note: The expectation is that whenever someone changes the crd schema in AKO, 
the `build`/`build-local` targets should be executed which would automatically sync the 
changed CRD schemas to ako-operator. The source of truth would be the schemas 
defined in AKO and not AKO-operator, hence the new `pre-build` target is for AKO only.
> sync CRD files from ako helm directory to ako-operator

- Dockerfile.ako
- Makefile
- buildsettings.json
- cmd/ako-main/main.go
- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
AKO is built using parameters present in buildsettings.json which publishes
the min/max Avi and k8s versions supported with a given version of AKO.
Post this commit maintainers must update the buildsettings.json file to
correctly reflect the supported Avi and k8s versions.
Misc: minor TestSecureRouteMultiNamespaceInNodePort related cleanup
> Introduce buildsettings.json that enforces a supportability matrix

- Makefile
- internal/lib/constants.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/validator.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- tests/integrationtest/lib.go
This PR handles:
1. Openshift EVH changes.
2. Fixed: Datascript, from host rule, not attached to VS in EVH mode. (Attaching DS to child node)
2. Issue in cksum calculation for passthrough vs.
Note: For passthrough route with redirect allow, we are not encoding suffix (-indirect) of redirect VS created as AKO code base has logic based on that.
> Openshift EVH changes

- cmd/ako-main/main.go
- internal/cache/avi_ctrl_clients.go
- internal/k8s/ako_init.go
- pkg/utils/avi_obj_cache.go
This commit fixes a log format error and an error handling scenario
where AKO would have crashed if the Avi client does not get
initialized.
> Logging fixes and error handling

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_route_namespace_sync_test.go
Without this fix, gslb host doesn't get added to SNI VS VHDomainNames
> Use VHDomainNames for VS checksum calculation

- internal/nodes/avi_model_l7_translator.go
- internal/rest/dequeue_nodes.go
This PR works on:
1. Fixing : Delete cache entry only when Rest Method is DELETE. In case of non-retryable exception, AKO delete cache entry even if rest method is POST /PUT. This PR fixes that. 
2. Few log printing related issues.
> Remove cache entry only when rest method is DELETE

- internal/k8s/controller.go
- internal/lib/lib.go
After the migration from networkName to vipNetworkList, it was made
mandatory. In WCP environments networkName is not provided. This
extends the same behaviour with vipNetworkList.
> Allow vipNetworkList to be empty in case of advancedL4

- internal/lib/constants.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
If avi controller upgrade is is progress we would get 403 error.
Currently we don't retry on these errors, which would create a problem
if some kubernetes objects are modified while controller upgrade is in progress.
Enabling retry for these errors to handle this issue.
> Retry rest operations if avi controller upgrade is in progress

- internal/nodes/validator.go
- tests/advl4tests/advl4_hostname_test.go
- tests/ingresstests/ingress_annotation_test.go
- tests/ingresstests/ingressclass_test.go
While adding IngressMappings for the secret we were adding wrong Namespace.
Due to this problem, if the secret was added after adding Ingress, it was not getting processed.
> Fix problem with default secret annotation in Ingress

- internal/cache/controller_obj_cache.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/lib/avi_api.go
This also adds a few checks around executing CRD clientset calls
if the CRD is not installed on the cluster.
> adding additional logs for raw avi api queries outside rest layer

- internal/rest/k8s_utils.go
- internal/status/svc_status.go
This commit also adds a status check during deleting the service status.
> skip serviceLB status updates during bootup for layer7Only usecases

- internal/nodes/dequeue_ingestion.go
This PR handles encoding of service names/model names
1.  For L4 Virtual Service deletion case
2. For Adv L4 service 
3. For Service transition from loadbalancer type to cluster type.
> Fix EVH L4 service deletion

- tests/scaletest/lib/ingress.go
- tests/scaletest/lib/utils.go
- tests/scaletest/scale_test.go
- vendor/github.com/avinetworks/sdk/go/models/event_log.go
Adding test case to Scale test to check for any unwanted/redundant API calls to AVI controller on AKO reboot. 
An unwanted API call is one where only the Last Modified or Cloud Config Checksum fields of objects are updated without an update of any other fields
Config update event logs are fetched from the controller after AKO reboots. These logs are scanned for any unwanted API calls.
The second commit disables swap on a rebooted Kubernetes node. Without this, Kubelet fails to start after a node is rebooted.
> Scale Test - Test case to check for any redundant/unwanted API calls to AVI on AKO reboot

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_rest_test.go
This PR
1. Removes namespace from EVH Child VS name.
2. Handles upgrade scenario. Delete existing child EVH vs and objects related with it. This existing EVH Vs will have name with namespace included into it.
3. EVH IT modifications.
> EVH: Remove namespace field from child VS name

- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/k8s_utils.go
- internal/status/svcapi_status.go
- tests/advl4tests/advl4_hostname_test.go
- tests/ingresstests/ingressclass_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- tests/servicesapitests/servicesapi_l4_test.go
The hostname can be provided using the `HostName` field in gateway listener spec.
If not provided, AKO carries out the autoFQDN routine, based on the
`autoFQDN` field provided during installation. Hostnames are eventually
updated with IPs in respective Services.
> Allow specifying hostname per gateway listener

- internal/cache/cache_utils.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/validator.go
- internal/status/route_status.go
If a route is marked as `insecureEdgeTerminationAllow` then we skip
updating the vs uuid in the Route's annotation for the insecure
pool update. This is done because the Route is expected to get updated
with the vs uuid information of the SNI children which shouldn't
get overwritten.
> Skip updating vs uuid in annotation for insecureedgeallow

- internal/cache/controller_obj_cache.go
This commit introduces support for configuring the static routes
to the corresponding VRF contexts for the T1 router inside the controller.
The logic relies on the supplied T1Lr path which is used to figure
out the vrfconext name by talking to the Avi controller.
> Configure static routes inside T1 VRFs

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- tests/ingresstests/l7_graph_test.go
- tests/integrationtest/l4_service_test.go
- tests/servicesapitests/servicesapi_l4_test.go
This also removes redundant AddModelNode calls for Pools and L4PolicySets
since AKO does not really operate on these node objects apart from VsNode.
What all we can move away from with this:
1. Adding nodes to the graph, even though individual nodes are not used. See `DequeueNodes`, that relies solely on VsNodes. Adding Pool/L4PolicySet nodes in the graph, and not deleting them at any point could cause unnecessary memory utilization at scale. As far as pool nodes are concerned, since there was no checks of name uniqueness in the graph's pool nodes, multiple identical pool nodes were being added which again causes unnecessary in-memory consumption.
2. Should eliminate the need to include sni/passthrough/evh child VS Node checksum inclusion in parent VSes.
3. Eliminates the need to add …
> Calculate graph checksum using all nested nodes' checksums

- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/validator.go
- tests/ingresstests/l7_graph_test.go
- tests/integrationtest/lib.go
This commit removes the limitation in the current code that required
a portName to be specified in the Ingress object for Services of type
ClusterIP with multiple ports.
Now, we do the following:
- User specifies a port information with a numeric value on the ingress.
- We query the service and find the corresponding targetPort for this port.
- We use the targetPort to find a match with the endpoint list. (Like single port Service)
- Populate the servers using endpoint IPs (No change in behavior)
> Support for multi-port services with port number

- internal/rest/rest_operation.go
In case we get 404 error for DELETE operations, we can ignore them and
execure next set of operations. This would prevent a case where we
skip deletion of few objects due to 404 error on other objects.
> Ignore 404 error for DELETE operations

- helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_obj_vsvip.go
- pkg/apis/ako/v1alpha1/aviinfrasetting.go
- tests/ingresstests/ingressclass_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
Tests done:
create ingress/ lb service with public ip enabled
disabling public ip from aviinfrasetting deletes public ip
enabling public ip on existing aviinfrasetting adds public ip
removing annotation from lb service removes public ip
> Add public ip support for public cloud

- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
This commit supports the NSX-T VLAN transport zone.
When NSX-T is used with VLAN transport zone, the AKO code should
behave as the vCenter write access code.
This commit, removes the mandatory checks for the NSX-T cloud and
imposes them only if the NSX-T transport zone set to OVERLAY which
can be obtained from the cloud object.
> NSX-T VLAN Transport zone support

- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/hostname_cache.go
- internal/nodes/validator.go
- internal/status/svc_annotation.go
In VCF, we would create VIP per namespace, adding support for that in this PR.
We would look for an environment variable USE_VCF to enable this feature.
In this case, a mapping between namespace and hostname is saved to find out if
a hostname is present in multiple namespaces.
The parent VS name is modified in this case to include namespace instead of shard.
To do in next PRs
- UTs, Helm chart modification
> VIP per namespace for EVH in VCF

- internal/cache/controller_obj_cache.go
- internal/nodes/avi_model_evh_nodes.go
This PR fixes:
1. Issue : in EVH Passthrough, old stale data deletion was issue when passthrough route/ingress updated.
2. Add cloud name while fetching SEG
> Fix: EVH Passthrough VS Update Scenario and Add Cloud Name while fetching SEG

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/crd_translator.go
- tests/ingresstests/ingressclass_test.go
When AviInfraSetting is used, it changes the naming scheme for Pool names,
This is not accounted for while applying HTTPRules on pools, which causes AKO
to not identify any pool for HTTPRule placement.
Fixes AV-121134
> Allow AKO to identify pools for HTTPRule placement when InfraSetting is used.

- internal/nodes/avi_model_nodes.go
We should not check if EVH is enabled for checksum calculation
(cherry picked from commit b2f6d9737674ce81861c925e92bc44b1cd9783c2)
> Calculate checksum based on VS type

- internal/nodes/avi_model_nodes.go
- internal/rest/dequeue_nodes.go
- Infinite retry for all failures after retry counter is exhausted
- Increased retry counter to 100 from 10
In case rest request times out due to some problem, AKO would retry
all requests. But some of those requests might have been successful in
the controller. In that case AKO can get a 409 error if it tries to recreate
an objects on retry.
In case we get the timeout error object cache is not updated, so we would get
409 error on multiple objects.
fixes AV-120481
> infinite retry for all failures in rest layer

- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
Other status update fix includes status update fix during bootup
that prevented status update in ingresses hosting multiple vips.
The issue was seen as part of functional testing.
> status update gateway and ingress when svcapi is used.

- Makefile
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_rest_test.go
- tests/integrationtest/lib.go
AV-120552 : Modified the tests to check for model name with hostname shard or
vip per namespace (for VCF).
Skipping a few tests whcih would require substantially different verifications
in vip per namespace mode.
> Modified tests for EVH to include VIP per namespace use case

- docs/objects.md
Added a note for multi-port service support that supports port numbers from AKO 1.5.1 along with strings.
> Multi-port service support

- internal/k8s/ako_init.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
The Namespace list is used while populating status during boot up.
Hence, updating the list after initializing Namespace Sync.
(cherry picked from commit 695116ba52dfbd9da253fef267e24dfa3d8c2567)
> Populate valid Namespace list during AKO boot up

- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
Other status update fix includes status update fix during bootup
that prevented status update in ingresses hosting multiple vips.
> cherry-pick: status update gateway and ingress when svcapi is used.

- internal/cache/cache_utils.go
- internal/rest/avi_obj_vs.go
We were trying to match uuid of cache object without checking if the object is nil.
This can cause segmentation fault. Adding a check to prevent this.
Also fixed another problem where we were saving pointer to an object which was
already a pointer. Fixed this, although we are most likely not hitting this path.
Fixes AV-121646
> Check if value of object in cache is nil before further processing

- internal/nodes/avi_model_tls_passthrough.go
In case of passthrough with EVH we can’t encode the PG name becasue in l4 data script there is no encode function to use.
> Remove encoding from passthrough PG name

- tests/scaletest/configs/st_testbed.json
- tests/scaletest/lib/parser.go
- tests/scaletest/scale_test.go
This commit introduces changes in the scale test suite for EVH.
'evhEnabled' should be set to true in the testbed file if EVH is enabled on AKO
The test then verifies the AVI objects based on the encoded naming convention of EVH
> Scale Test changes for EVH support

- pkg/utils/avi_rest_utils.go
This avoids writing over the same variable via multiple goroutines.
Fixes AV-121758
> Initialize Avi clientPool with number of goroutines

- internal/rest/dequeue_nodes.go
Even if retry count is exhausted, AKO would do a slow retry.
In this case also, we have to refresh the cache.
Fixes AV-122026
> Refresh cache even if retry count is exhausted

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- tests/evhtests/l7_evh_graph_test.go
This PR fixes issue of multi-port service with port number specified in ingress for 
1. EVH (Secure, insecure)
2. SNI (Secure)
> Fix EVH and SNI: multiport service with portnumber specified in ingress definition

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/rest/avi_evh_obj.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
This PR fixes issue with EVH deployment where 
1. For secure, insecure ingress/ route with hostrule CRDs with TLS configs and Ingress secrets are mixed, then sslkeycertref on parent was getting overwritten by later applied definition.
> AV-122809: EVH: Hostrule SSLcertkeyref fixes for secure/insecure ingress, routes

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/rest/avi_evh_obj.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
This PR backport changes from master to 1.5.2 to fix issues
1. EVH: Secure , Insecure VS deployed with hostrule sslkeycert ref doesn't have sslkeycert ref as per expectations. Handles add, delete, update case.
2. SNI VS:  on delete hostrule with sslkeycert ref from SNI VS, SNI Vs gets default cert.
> EVH & SNI: Hostrule SSLcertkeyref fixes for secure/insecure ingress, routes

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/objects/resourceversions.go
This commit introduces a change that works as follows:
- During bootup of AKO, we perform a full sync. This results
into the layer 2 models getting built before activating layer 3.
- The informer event handlers are then used to enqueue updates to
the layer 2 queues as well for the same updates which were processed
as a part of the full sync update.
This current fix optimizes the second point by caching the resource
version of the k8s objects during fullsync.
Then during the regular event updates, it compares the cached resource
versions in AKO with that of the event updated objects.
If the resource versions are same, then AKO does not enqueue the same
key again in layer 2, thus reducing the burden of layer 2 significantly
during bootup.
This fix potentially solves a starvation problem in …
> Make AKO bootups faster

- internal/nodes/crd_translator.go
In case no path is provided in the Route object, this commit
enables matching a HttpRule with target `/` to a Route Pool with
path ``.
Fixes #AV-122276
> Fix HTTPRule setting on Pool for Route with no Path

- internal/status/route_status.go
- internal/status/svc_status.go
AKO's openshift status populates a unique router name to denote
the vip that was populated via AVI. It's possible that HA Proxy
also runs on the same cluster and updates the Route object as well.
AKO's status update code wasn't checking for the routerName while
update was called on the Route object. This will remove the HAProxy
status as well and end up leading to unnecessary status calls during
AKO bootup.
This commit fixes this issue.
> Status update should check for the AKO router name

- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/objects/avigraph.go
- internal/objects/store_lock less.go
- internal/objects/store_lock.go
This commit introduces a way to make the bootup cache population
parallel. Additionally, the number of Avi clients are always init
to 9 irrespective of shard size.
Fixes: AV-125494
> Make the bootup cache population parallel

- internal/k8s/crdcontroller.go
Consider the scenario:
- AKO boots up. During  bootup, a HostRule CRD is created.
- The HostRule CRD does not perform a validation logic during full
sync.
- We cache the resource version during fullsync.
- When the event handlers are switched on, we find the same resource
version, so we don't do the validation.
- The HostRule is never applied.
This fix will force a re-publish of the HostRule/HTTPRule/AviInfra
CRD if they are found to have a status change during the validation.
> Publish the CRD if the status changes during bootup

- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
The issue was introduced as part of
https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/commit/46e8d1da1496b4bf66220158150d704574a58aee
The changes got left out for advl4 usecases.
> Fix status update issue during WCP full sync

- helm/ako/values.yaml
- internal/k8s/crdcontroller.go
- pkg/utils/utils.go
This commit addresses 2 problems:
- The CRD status verification in layer 1 for optimization is now
removed.
- The secret informer is now switched on for all namespaces.
This helps with bootup speed because we don't use the clientsets
anymore. As a result of this change, the pod resource sizing
of AKO is altered in the values.yaml
Fixes: AV-125902
> Correct problem with status checks on CRD

- internal/k8s/ako_init.go
- internal/k8s/services_api.go
This commit adds the services API index handlers before the
event handlers are setup during AKO bootup.
> Add indexers for services API before setting up event handlers

- internal/k8s/ako_init.go
- internal/k8s/controller.go
This is done to make it consistent with ingressclass version when it is fetched through the indexer
Fixes AV-126133
> change version of ingressclass to networking/v1beta1 in indexer

- internal/objects/clusteripservices.go
- internal/objects/lbservices.go
- internal/objects/store_lock_less.go
This commit re-introduces the locks for a couple of objects
that are being accessed from the ingestion layer.
> Introducing locks for a couple of objects.

- internal/k8s/crdcontroller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/rest/dequeue_nodes.go
- tests/ingresstests/crd_test.go
- tests/integrationtest/lib.go
This PR fixes
1. Host rule rejection if GSLB FQDN and local FQDN in hostrule is same
2. Avoid duplicate fqdn addition for EVH.
3. Regression: When AKO migrate from SNI to EVH and vice-versa, EVH/SNI shared VS were not getting deleted.
> Reject hostrule if GSLB FQDN and local FQDN are same. Shard VS deletion when AKO migrate from SNI to EVH and vice-versa.

- buildsettings.json
- helm/ako/templates/clusterrole.yaml
The k8s event handler chooses create/update/patch calls internally,
and is not the responsibility of the AKO pod. The AKO pod still needs
the permissions to do update/patch.
Also upgrades the max controller version to 21.1.6
> Add update/patch verb permissions for Events

- ako-infra/avirest/handle_netinfo.go
- ako-infra/ingestion/avi_infra_controller.go
- ako-infra/ingestion/vcf_k8s_controller.go
- cmd/ako-main/main.go
- cmd/infra-main/AviControllerInfra.go
- go.mod
- go.sum
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/dynamic_client.go
- internal/lib/lib.go
- pkg/utils/constants.go
- pkg/utils/utils.go
- tests/advl4tests/advl4_hostname_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
- tests/integrationtest/l4_service_test.go
- tests/multicloudtests/multi_cloud_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/servicesapitests/servicesapi_l4_test.go
- tests/temp/temp_sni_to_pool_test.go
- vendor/github.com/apparentlymart/go-cidr/LICENSE
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
- vendor/modules.txt
In this commit changes for ako-infra is integrated to be consumed in the main AKO.
Changes include,
- SEgroup and cloud annotation in the vmware-systems-ns are being consumed in main ako
- VCF Network is added to IPAM
- Code reorganisation to maintain correct sequence flow.
> Add VCF network to IPAM and use SEgroup from NS annotation

- internal/k8s/ako_init.go
- internal/status/statefulset_status.go
Currently status of ako statefulset is updated with condition values after objects are deleted
by setting deleteConfig to true. However, in kubernetes 1.22 this can not be done because kubernetes
automatically removes this status. To get around this problem annotation of the statefulset would be
updated instead of status.
When object deletion starts we would set the annotation as:
annotations:
ObjectDeletionStatus: Started
After object deletion is completed, this would be changed to
ObjectDeletionStatus: Done
> Update annotation in AKO statefulset after avi object deletion through deleteConfig

- cmd/ako-main/main.go
- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/k8s_utils.go
- internal/rest/ssl_key_certificate.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/ingresstests/l7_rest_test.go
- tests/integrationtest/lib.go
This commit simplifies switching mechanisms for status updates
based on the serviceMetadata information, and helps identify
corresponding to which object the status update is bound for.
Fixes include - not allowing status update for SNI VS pools,
correct status update logic in case of vsvip updates.
Fixes: AV-128633
> Status update fixes

- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
This commits adds analytics policy support to parent VS's Hostrule CRD.
> Analytics policy support to parent VS's Hostrule CRD

- internal/k8s/ako_init.go
- internal/rest/dequeue_nodes.go
This PR fixes an intermittent issue of Parent VS not getting deleted properly when the delete config flag is enabled
> Fix: Parent VS not getting deleted properly when the deleteConfig flag is enabled

- Dockerfile.ako-infra
- Makefile
- ako-infra/ingestion/vcf_k8s_controller.go
- cmd/ako-main/main.go
- internal/cache/avi_ctrl_clients.go
- internal/k8s/ako_init.go
- internal/lib/avi_api.go
- internal/lib/dynamic_client.go
- internal/lib/lib.go
In VCF controller details won't be provided through configmap, instead
it would be provided via bootstrap CRD. Added neccessary changes.
Also added makefile changes to build ako-infra docker container.
> Read Avi Controller IP from bootstrap CR in VCF environment

- internal/nodes/avi_model_l7_hostname_shard.go
This PR fixes the issue of child FQDNs not getting removed from parent VSes when the secret is removed from the k8s.
> Fix for child FQDNs not getting removed from parent VS

- internal/k8s/controller.go
in VCF cluster, ako needs permission to access namespacenetworkinfos and akobootstrapconditions
> kube-builder tags to access CRDs for VCF

- ako-infra/ingestion/avi_infra_controller.go
- internal/cache/controller_obj_cache.go
- internal/lib/avi_api.go
- internal/lib/lib.go
When any SE group related op fails with provided tenant(GET/PUT), an assumption is made that the tenant is configured with se_in_provider_context set to True on the AVI controller.
A context switch is then done for the session and the operation is retried.
> Handling non admin tenant with SE_in_provider_context set

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
1. Allow status update with pools with PUT calls
2. Update status for SNI child
3. Fix public ip not removed when enablePublicIP unset in aviinfrasetting.
> Public IP and Status Update Fixes

- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/dequeue_ingestion.go
- tests/evhtests/l7_evh_graph_test.go
- tests/servicesapitests/servicesapi_l4_test.go
This commit avoids creating an extra dedicated VS, when services API is
being used and a gateway frontends the service of type LB. This would mean
an either/or workflow, decided by the presence of labesl on the k8s Service.
> Donot create dedicated VS if gateway labels are present on the service

- internal/status/route_status.go
- tests/evhtests/l7_evh_graph_test.go
This commit fixes a faulty route status check issue, that was
returning a wrong comparison between old/new route statuses.
Fixes - AV-131326
> Fix route status update while deleting entry from status

- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- helm/ako/crds/ako.vmware.com_hostrules.yaml
- internal/k8s/ako_init.go
- internal/k8s/crdcontroller.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/crd_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/objects/crdrules.go
- internal/objects/store.go
- internal/status/route_status.go
- pkg/apis/ako/v1alpha1/hostrule.go
The field fqdnType determines the interpretation of the fqdn matching.
fqdnType can be one of the following:
Exact - matches the fqdn exactly
Contains - considers the value specified in `fqdn` for a substring match
Wildcard - matches based on fqdn suffix, this must contain a `*` as a prefix
(for instance: *.tenant.com)
This implementation also helps in **easily** specifying the Hostrule for parent VSes
for which AKO programs the fqdn automatically (without user input). The users
can specify a substring of the parent VS name, to attach the hostrule to that VS.
> Introduce fqdnType (Exact/Contains/Wildcard) in HostRule

- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/dequeue_ingestion.go
- pkg/utils/types.go
- tests/evhtests/l7_evh_graph_test.go
- tests/servicesapitests/servicesapi_l4_test.go
This commit avoids creating an extra dedicated VS, when services API is
being used and a gateway frontends the service of type LB. This would mean
an either/or workflow, decided by the presence of labesl on the k8s Service.
> cherrypick: Donot create dedicated VS if gateway labels are present on the service 

- internal/cache/controller_obj_cache.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/dequeue_nodes.go
- tests/ingresstests/l7_rest_test.go
This PR adds support to retain shared VS VIP on AKO reboots.
The following approaches have to be taken by the user to remove the shared VS VIP after this PR.
1. Toggle the `enableEVH` flag in config map and reboot the ako
2. Manually delete from the UI or shell.
> Retain the shared VS VIP on ako reboot

- Makefile
- ako-infra/avirest/handle_netinfo.go
- ako-infra/ingestion/avi_infra_controller.go
- ako-infra/ingestion/vcf_k8s_controller.go
- internal/lib/dynamic_client.go
- tests/avimockobjects/CLOUD_NSXT_mock.json
- tests/infratests/akoinfra_test.go
- tests/integrationtest/lib.go
Testcases to validate that ako-infra waits for correct Boostrapcondtion objects.
More tets cases regarding networkinfo cr validation and annotation update would be handled in subsequent PRs.
> test cases for ako-infra boostrapconditions

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
This commit removes the advancedL4 flag from helm. This flag is used
internally and need not be exposed to the end user.
The servicesAPI flag under AKOSettings can be used for Services API
use.
> Remove advanced_l4 from helm

- docs/crds/hostrule.md
- internal/k8s/crdcontroller.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
This PR adds documentation for the new field aliases in hostrule CRD. It also includes code that addresses some minor comments given by @chauhanshubham in the PR [#706](https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/706)
> Doc: Documentation for the new field aliases in hostrule CRD

- internal/rest/dequeue_nodes.go
This PR is to retain the dns info corresponding to the parent FQDN as in AWS making the whole DNS nil will result in an error/issue.
cc: @apalsule
> Fix: Retains the dns info corresponding to the parent FQDN

- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/rest/avi_obj_vsvip.go
- internal/status/route_status.go
- tests/avimockobjects/CLOUD_NSXT_mock.json
- tests/avimockobjects/CLOUD_VCENTER_mock.json
- tests/avimockobjects/ipamdnsproviderprofile_uuid_mock.json
- tests/ingresstests/l7_graph_test.go
This prevents AKO to overwrite the ipam network subnet configuration
in the Vip while doing a PUT VSVIP call.
Resolves AV-132243
> Do not overwrite the ipam network subnet config in Vip before PUT

- internal/rest/avi_obj_vsvip.go
copying the IPAMNetworkSubnet does not work, and the vip.DiscoveredNetworks gets removed.
which causes the vsvip to go down eventually after enabling/disabling the virtualservice
> Always recreate IPAMNetworkSubnet while updating VSVIP

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/controllers/configmap_test.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- docs/ako_operator.md
- docs/akoconfig.md
- docs/install/helm.md
- docs/install/operator.md
- docs/troubleshooting/events.md
- docs/values.md
- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/control_config.go
- pkg/utils/events.go
Introduce a flag in the AKO Configmap that allows users to disable
AKO event broadcasting. Any changes in the parameter value takes affect
during runtime, without requiring AKO reboot. By default Events are
enabled and needs explicit user intent to disable. AKO Warning events
are never disabled regardless of the `enableEvents` flag.
> cherry-pick: Control AKO Event broadcasting using ConfigMap `enableEvents`

- internal/k8s/controller.go
- internal/lib/constants.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
This commit fixes issues in pushing to the Status queue
which were happening multiple times for certain object updates
like VS and VSVIP.
Annotation addition from AKO updates the resourceVersion leading to
redundant work for the graph layer. The commit enhances checks
for ingress/svc/route diff during Update.
> Status update push to queue fixes, ingress/svc/route update check enhancements

- internal/nodes/dequeue_ingestion.go
- internal/nodes/hostname_cache.go
- internal/nodes/ingress_model_rel.go
- internal/nodes/validator.go
- internal/objects/crdrules.go
- tests/evhtests/l7_evh_crd_test.go
This commit fixes the following problems in the object cache mapping
- solves a problem with Wildcard based fqdnType hostrules, that was not
returning all Ingresses in which the host the wildcard fqdn.
- solves a problem with `Contains` based fqdnType hostrules, that was not
correctly returning all Shared VS models, particularly in case of
create-delete-create workflows.
- solves problems related to fqdnType switching.
> Hostrule fixes relating to fqdnType Wildcard and changes between fqdnTypes

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/controllers/akoconfig_controller.go
- ako-operator/controllers/configmap.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
This commit adds `syncNamespace` and `advancedL4` fields back into the akoconfigs CRD with a warning message.
This is done to avoid any API Version upgrade or introducing admissions controllers for the AKO Operator 1.6.1 release.
> Bringing back syncNamespace and advancedL4 in akoconfig CRD for 1.6.1

- internal/cache/controller_obj_cache.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/hostname_cache.go
- internal/nodes/ingress_model_rel.go
- internal/nodes/validator.go
- internal/objects/crdrules.go
- internal/rest/avi_obj_pool.go
- internal/rest/ssl_key_certificate.go
- tests/evhtests/l7_evh_crd_test.go
Save cloud properties in cache if dns provider not set
Hostrule fixes relating to fqdnType Wildcard and changes between fqdnTypes
This commit fixes the following problems in the object cache mapping
- solves a problem with Wildcard based fqdnType hostrules, that was not
returning all Ingresses in which the host the wildcard fqdn.
- solves a problem with `Contains` based fqdnType hostrules, that was not
correctly returning all Shared VS models, particularly in case of
create-delete-create workflows.
- solves problems related to fqdnType switching.
> [cherry-picks]: hostrule and cloud cache fixes

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/controllers/configmap_test.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- docs/ako_operator.md
- docs/akoconfig.md
- docs/install/helm.md
- docs/install/operator.md
- docs/troubleshooting/events.md
- docs/values.md
- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/control_config.go
- pkg/utils/events.go
Introduce a flag in the AKO Configmap that allows users to disable
AKO event broadcasting. Any changes in the parameter value takes affect
during runtime, without requiring AKO reboot. By default Events are
enabled and needs explicit user intent to disable. AKO Warning events
are never disabled regardless of the `enableEvents` flag.
> Control AKO Event broadcasting using ConfigMap `enableEvents`

- internal/k8s/ako_init.go
- internal/lib/lib.go
This regression is caused because of retaining shared vs vip during AKO reboot. Now we have added check if deleteConfigMap is set to true, we should not save anything.
> AV-136288: Ingresses are not getting synced to AVI After changing deleteconfig value from True to False

- CHANGELOG.md
- internal/k8s/crdcontroller.go
This commit corrects the validation on tcpSettings while specifying listeners.
> Validate enableSSL on listener Port only when listener settings are configured

- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
This commit allows AKO to configure these additional policies in the
SNI/EVH parent VSes, which were missed before. All other policies are
being set in the parent VS fine.
> Fix to configure appProfile, httpPolicies, datascripts for EVH/SNI parent VSes

- internal/k8s/controller.go
- internal/lib/constants.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
This commit fixes issues in pushing to the Status queue
which were happening multiple times for certain object updates
like VS and VSVIP.
Annotation addition from AKO updates the resourceVersion leading to
redundant work for the graph layer. The commit enhances checks
for ingress/svc/route diff during Update.
> [cherry-pick]: Status update push to queue fixes, ingress/svc/route update check enhancements

- internal/nodes/crd_translator.go
This PR fixes the issue of non-significant logs duration not coming as infinite by default.
> Sets the non significant log duration as infinite by default

- ako-infra/ingestion/constants.go
- ako-infra/ingestion/vcf_k8s_controller.go
- cmd/ako-main/main.go
- cmd/infra-main/main.go
- internal/lib/dynamic_client.go
- internal/lib/lib.go
This commit updates the workflow to proceed with deconfiguration
by watching over workload namespace addition/deletion. AKO identifies
the workload namespaces and differentiates between them and other System
namespace by way of a label "vSphereClusterID: <cluster-id>" which
is only present in user created Workload namespaces.
> Update deconfiguration logic by watching over Workload namespace

- ako-infra/avirest/handle_netinfo.go
- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vrf.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/rest_operation.go
- internal/rest/ssl_key_certificate.go
This commit removes the controller version that is being overwritten
on individual API calls to the controller instead of using the api
version which was used to initialise the session to the controller.
With these changes, all REST layer API calls end up using the version
which was used while initializing the session.
> Remove overwriting controllerVersion on POST/PUT/DELETE api calls

- internal/k8s/crdcontroller.go
This commit resolves an issue wherein every SEGroup used in the AviInfraSetting
was getting configured with the labels required for static route syncing.
This was being done even if the user specified `disableStaticRouteSync` to be true
or in cases where static route syncing is not required.
Fixes AV-139903
> Skip label configuration during AviInfraSetting validation if disableStaticRouteSync set to true

- internal/k8s/crdcontroller.go
This commit resolves an issue wherein every SEGroup used in the AviInfraSetting
was getting configured with the labels required for static route syncing.
This was being done even if the user specified `disableStaticRouteSync` to be true
or in cases where static route syncing is not required.
> [chery-pick]: Skip label configuration during AviInfraSetting validation if disableStaticRouteSync set to true

- internal/lib/constants.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/rest/avi_obj_vsvip.go
This commit fixes issues with using Gateways and ServiceLB at the same time.
The bug lead to improper dedicated VS creation of Service of type LB.
This also fixes an issue with L4 VSVIP when autoFqdn is disabled and no
subDomains are configured in the dnsProfile, which was leading to an empty
string fqdn programming.
Fixes AV-139523
> Fix Service LB handling with Gateways

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/rest/avi_obj_vsvip.go
This commit fixes issues with using Gateways and ServiceLB at the same time.
The bug lead to improper dedicated VS creation of Service of type LB.
This also fixes an issue with L4 VSVIP when autoFqdn is disabled and no
subDomains are configured in the dnsProfile, which was leading to an empty
string fqdn programming.
> [cherry-pick]: Fix Service LB handling with Gateways

- internal/nodes/route_ingress_model.go
This PR hardcodes the AviInfraSetting values such as `enablePublicIP` to true by default for MCI.
> [MCI] AviInfraSetting with default values

- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/validator.go
- internal/rest/avi_pool_group.go
- internal/status/svc_annotation.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/utils.go
- tests/ingresstests/l7_nodeport_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_crd_test.go
Changes that are cherry-picked
1. Fix: AKO not updating the pool members correctly #644
2. Use NS bound informer for Secrets in Openshift #651
3. Support for multi-port Services with port number for ServiceType NodePort and NodePortLocal #655
4. Host rule rejection if GSLB FQDN and local FQDN in hostrule is same
5. Avoid duplicate fqdn addition for EVH.
6. Fix for child FQDNs not getting removed from parent VS #701
7. AV-131413: VS not getting converted to Dedicated VS Type using AVIInfraSetting CRD #705
8. Save cloud properties in cache if dns provider not set
9. Add tenant and api version for fetching authtoken #778
10. Remove overwriting controllerVersion on POST/PUT/DELETE api calls #788
> Cherry-pick from 1.7.1, 1.6.2, 1.6.1 to branch 1.5.3. 

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/dequeue_ingestion.go
Issue was due to name convention for shared passthrough VS.
Passthrough VSes were getting created with same name in multiple AKO.
This PR addresses that.
> AV-142604: VSes are not getting created for Openshift cluster for Passthrough Redirect route with Multiple AKO

- internal/k8s/ako_init.go
- pkg/utils/utils.go
This PR fixes the issue of VSes getting deleted after the AKO reboot.
> [Bug-fix] Fixes the VS delete issue after AKO reboot

- internal/cache/controller_obj_cache.go
- internal/k8s/crdcontroller.go
- internal/lib/lib.go
This PR adds a cloud_uuid query parameter in the /api/network call which will work in case of both Default-Cloud and NonDefault-Cloud.
> AV-139061 Added cloud_uuid to network api call

- docs/akoconfig.md
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/lib.go
vipPerNamespace is only used in a VCF cluster with WCP enabled
over a NSX topology. Therefore vipPerNamespace can be automatically
set to active in a VCF Cluster. This does not require an explicit
user configuration.
> Remove vipPerNamespace from user configurable parameters

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/objects/lbservices.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vsvip.go
- internal/status/route_status.go
- tests/integrationtest/l4_service_test.go
This PR adds support for sharing VIPs among Service of Type LBs in kubernetes. The proposed functionality works by means of a annotation that can be added to these Services, which help the Services to be grouped under 1 VIP.
The annotation to be used is `ako.vmware.com/enable-shared-vip` that takes in a string value.
All services that share this unique annotation value, will be grouped into a single virtual service in Avi, and therefore get a single shared VIP. In other words, AKO would maintain 1 VIP per unique annotation value.
In case of users wanting to set a preferred static VIP through the `.spec.loadBalancerIP` field in the Service, it is required that all Services sharing a unique annotation value must have the same preferred VIP provided in the spec. If two Services in under the …
> Add support for Shared VIP with Service of type LoadBalancer

- internal/nodes/ingress_model_rel.go
This PR cherry-picks the commit added as a fix for the issue where AKO was not retrieving the routes correctly for an empty path in the route configuration.
> [fix] AKO not retrieving routes for an empty path

- internal/rest/avi_obj_vsvip.go
AKO should only log regarding validity of floating IP when public ip is enabled
> AV-145202 Fix floating ip warning

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/dequeue_ingestion.go
This commit adds support for using infrasetting CRD,
with Services of type LB, when sharing VIP using
the annotation. An infrasetting can be referenced from such
Services via an annotation, which must be provided on
all Services that intend to share a VIP.
> Add infrasetting support with sharedvip using Service of type LB (#865)

- buildsettings.json
- internal/nodes/dequeue_ingestion.go
- version.yaml
[AV-149725]:  L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation
> L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation

- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_nodes.go
AV-149730: This PR addresses following issue:
Naming convention of L4 pool is changed in 1.7.1.  `protocol` field has been added as part of pool name. But as checksum was not getting changed for `VirtualService` and `L4PolicySet`, new pools were not getting referenced in L4policyset and Virtual Service. Also as old pools were attached to VS and L4 Policyset, old pools also were not getting deleted.
> Regression fix: Change L4 checksum as naming convention for L4 pool is changed in 1.7.1

- ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
- helm/ako/crds/ako.vmware.com_httprules.yaml
- internal/k8s/crdcontroller.go
- internal/lib/constants.go
This PR fixes mandatory check "to have destinationCA or pkiProfile in tls setting section for httprule". It also adds validation to have only pkiprofile or destinationCA in rule.
Testing Done:
1. Httprule without pkiprofile or  destinationCA -->Accepted
2. Httprule with pkiprofile --> Accepted
3. httprule with destinationCA --> Accepted
4. httprule with destinationCA and pkiProfile --> rule Rejected
> Fix HttpRule: Remove mandatory check for DestCA and PkiProfile

- internal/k8s/crdcontroller.go
- pkg/apis/ako/v1alpha1/aviinfrasetting.go
- pkg/apis/ako/v1alpha1/httprule.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
AV-143438: Cherrypicks the fix added in the master branch to the release-1.7.2 branch.
> Fix for the issue `Predefined health monitors are not assigned to a pool` 

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
For all public clouds except openstack, use global vrf
for openstack, use tenant vrf for non admin tenant, and use global vrf otherwise
for nodeport mode, use global vrf always
in AV-149966, AKO used tenant vrf through getVrf because setting global vrf was skipped in checkAndSetVRFFromNetwork in nodeport mode
> AV-149966 set vrf to global in nodeport

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/validator.go
- tests/advl4tests/advl4_hostname_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_rest_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
- tests/ingresstests/l7_rest_test.go
- tests/integrationtest/l4_nodeport_service_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- tests/servicesapitests/servicesapi_l4_test.go
Fixes the servers not being added to pool for ingress with named ports
testing done:
on AKO with serviceType as NodePortLocal, created an ingress with named ports. 
result:
servers got added to pool
> AV-149930 Fix named ports with Ingress

- CHANGELOG.md
This PR corrects the changelogs as the AKO can be installed in namespaces other than the `avi-system` namespace.
> Changelogs correction

- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_nodes.go
AV-149730: This PR addresses following issue:
Naming convention of L4 pool is changed in 1.7.1. protocol field has been added as part of pool name. But as checksum was not getting changed for VirtualService and L4PolicySet, new pools were not getting referenced in L4policyset and Virtual Service. Also as old pools were attached to VS and L4 Policyset, old pools also were not getting deleted.
> [Cherry-pick]: Regression fix: [AV-149730] Change L4 checksum as naming convention for L4 pool is changed in 1.7.1

- MAINTAINERS.md
- buildsettings.json
AKO supports 4 major releases of Kubernetes. So changed min and max according to it. 
@apalsule @swathinsankaran @aaha97 @abhishekbsingh : We need to check from customer perspective impact of changing min K8 version. But I think we should keep only 4 major releases into picture to reduce wide variety of testing
> Support for kubernetes 1.24

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/dequeue_ingestion.go
When Aviinfrasetting  CRD applied to passthrough Route using annotation, Naming conventions for Avi object will be as follows:
1. VS: `<cluster-name>--Shared-Passthrough-<aviinfraCrdName>-<number>`
2. PoolGroup: `<cluster-name>--<AviInfraCrdName>-hostname`
3. Pool: `<cluster-name>--<AviInfraCrdName>-hostname-svcname`
4. DataScript: `<cluster-name>--Shared-Passthrough-<aviinfraCrdName>-<number>`
Testing Done:
1.  SNI: Create passthrough route with aviinfra annotation without redirect: 
2. SNI: Create passthrough route with aviinfra annotation with redirect
3. SNI: Transition passthrough route: With annotation to without annotation.
4. SNI:  Transition passthrough route: Without annotation to with annotation
5.  SNI: Apply aviinfra crd with l7Setting: ShardSize (This will change passthrough …
> AviInfrasetting Support to Passthrough Routes

- ako-infra/ingestion/vcf_k8s_controller.go
- cmd/ako-main/main.go
- go.mod
- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/crdcontroller.go
- internal/rest/avi_obj_vsvip.go
- internal/status/ing_status.go
- pkg/utils/log.go
- vendor/modules.txt
This PR sets the client-go logger as AviLogger, thereby converting all the client-go logs into AviLogger format.
It fixes the bug AV-91662.
Reference: https://github.com/kubernetes/client-go/issues/18#issuecomment-624162529
Tested the changes by removing the hostrule CRD when AKO was running and found the following client-go logs are coming in AviLogger format.
Logs:
```
2022-07-25T18:24:50.870+0530	DEBUG	nodes/avi_model_evh_nodes.go:521	key: Endpoints/default/ew-app, msg: Added hosts [ingress-host-insecure-kubernetes.avi.internal] to HTTP policy for VS kubernetes--c992fe61f72008238aa3fbe1c599bf85696bb212
2022-07-25T18:24:53.871+0530	ERROR	v2/klog.go:914	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/k8s/controller.go:1206: Failed to watch *v1alpha1.HostRule: …
```
> Sets the client-go logger as AviLogger

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/lib.go
- internal/nodes/dequeue_ingestion.go
This PR adds the code to ignore the processing of the pods which don't have the annotation "nodeportlocal.antrea.io"
in it. This was done previously at the Graph layer and with this commit, the
check will done at the Ingestion layer.
fixes AV-148367.
> AV-148367: NPL optimisations

- internal/nodes/avi_model_l7_hostname_shard.go
**Issue** is present only in Insecure Ingress for SNI deployment. DataScript is being used to redirect traffic to respective poolgroup and pool-member. As DataScript is doing case insensitive search to select pool member using `priority label`,  pool with case sensitive name was not getting selected and that was causing 470 error.
**Fix** For insecure ingress pool, priority label has been updated to all lower case characters to match appropriate pool.
For existing deployment, it will cause `PUT` request on pool and pool groups who has case sensitive host name and path.
This will impact only insecure ingress deployment on SNI.
Other modes uses, http policyset to redirect traffic and no datascript comes into picture.
**Previous to fix**
**After fix ***
> AV-147609: HTTP Ingress with a single path gives a 470 error

- cmd/ako-main/main.go
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/k8s/advl4_controller.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/k8s/services_api.go
- internal/lib/constants.go
- internal/lib/control_config.go
- internal/lib/lib.go
- pkg/utils/utils.go
As part of this PR
1. Introduced changes to stop processing events from namespaces mentioned in values.yaml
2. Removed logic where AKO was listening on AKO deployed namespace only for secrets.
As part of this PR, we did not handle runtime update to `blackListedNamespaces` variable as it will overload AKO with fetching updates from all un-blocked namespaces in bulk. So if customer does update to `blackListedNamespaces` list, then AKO needs to be re-started.
Testing done:
1. K8 cluster: without providing any blocked namespaces and with blocked system namespaces.
2. Openshift cluster: Without providing any blocked namespace and with blocked system namespaces.
>> Result on Openshift (with 2 master and 3 worker nodes. more than 1k secrets present)
a. Without blackListedNamespace: Took 2 to 4 …
> AV-153526: Avoid going through the system-namespaces on openshift and k8

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- tests/ingresstests/ingressclass_test.go
- tests/integrationtest/lib.go
- tests/k8stest/controller_test.go
- tests/multicloudtests/multi_cloud_test.go
This PR adds the optimization to process ingresses that belong to the ingressClasses owned by AKO.
It fixes AV-148368.
Optimizations added:
1. During AKO reboot, validates every ingress object and ignore it if it belongs to a non-ako ingressClass.
2. Ignores the handling of ingresses that are not part of AKO's ingressClass in Add and Delete ingress handler functions. To capture the transition from ingressClass non-avi-lb to avi-lb and vice versa, in the Update ingress handler function the same optimisation code is not added.
Tested scenarios and their results:
1. Ingress from non-avi lb to avi-lb ingressClass -> VS got created
2. Ingress from avi lb to non-avi lb ingressClass -> VS got deleted
3. Avi-lb not default and ingress dont have ingressClass -> ignored
4. Ingress with non-default …
> IngressClass optimisations

- buildsettings.json
- internal/nodes/dequeue_ingestion.go
Cherry Pick: Fixes [AV-149725] 
* L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation
* Change max version supported to 21.1.4 in 1.8.1
> Chery-Pick: L4 Shared VIP Infrasetting: Error out if all L4 VS does not have same avi-infra annotation (#881)

- internal/rest/avi_obj_vsvip.go
- tests/integrationtest/lib.go
This PR corrects the 'invalid type for address' warning logs coming in AKO log.
fixes AV-154444
> [AV-154444] corrects the 'invalid type for address' warning logs coming in AKO log

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
This PR fixes a crash issue during passthrough route cleanup after adding aviinfrasetting.
Also added a couple of UT fixes caused by the ingressClass optimizations.
Tested scenarios
>k8s and Openshift
1. Passthrough ingress transition from ingressClass without infraSetting to ingressClass with infraSetting
2. Passthrough ingress transition from ingressClass with infraSetting to ingressClass without infraSetting
3. Passthrough Ingress deletion
> [AV-154711] fix for AKO restart issue

- internal/k8s/ako_init.go
This commit fixes an issue of AKO not blocking the namespace during bootup even though the namespace was present in the blocked namespace list.
> fix for AV-156686

- cmd/ako-main/main.go
- cmd/infra-main/main.go
- internal/objects/nodes.go
- internal/rest/ssl_key_certificate.go
- pkg/utils/log.go
This PR fixes the below issues:
1. an issue with caching the Node objects in secondary AKO deployed in NodePort mode.
2. INFO logs were coming with extra square brackets.
> Fixes few issues with log and issue with caching Nodes in NodePort mode

- hack/jenkins/save_build.sh
This PR includes changes to generate SRP provenance data in our Jenkins build pipeline. We use srp tool and observer tool in our build pipeline to generate provenance data dynamically. Please go though the following JIRA for more details. The JIRA also contains links to srp related documents to check for details.
https://avinetworks.atlassian.net/browse/AV-149833
I have created a new job at https://prodjenkins.eng.vmware.com:8443/job/ako_OS-master-ci-build_srp/. This job is created by copying from https://prodjenkins.eng.vmware.com:8443/job/ako_OS-master-ci-build/
A new shell script needs to be added in an **Execute shell** in the job manually. This will download the srp and observer tools and generate the observer provenance data. …
> AV-149833 : SRP tool integration in AKO

- internal/cache/controller_obj_cache.go
- internal/rest/dequeue_nodes.go
This PR fixes an issue in populating VS DataScript cache when AKO encounters 409 error for POST requests.
> AV-159660: Fixes an issue in populating VS DataScript cache when AKO encounters 409 error

- internal/cache/controller_obj_cache.go
- internal/rest/dequeue_nodes.go
This PR contains the issue fix in populating VS DataScript cache when AKO encounters a 409 error for POST requests.
> Cherry-pick of  issue fix in populating VS DataScript cache

- cmd/ako-main/main.go
- cmd/infra-main/main.go
- internal/objects/nodes.go
- internal/rest/ssl_key_certificate.go
- pkg/utils/log.go
This PR cherry-picks the below fixes to master branch:
1. an issue with caching the Node objects in secondary AKO deployed in NodePort mode.
2. INFO logs were coming with extra square brackets.
> Cherry-pick of fixes added for log issues and issue with caching Nodes in NodePort mode

- helm/ako/templates/statefulset.yaml
This PR introduces the following changes.
1. Modifies the statefulset under helm to limit the number of AKOs
to two and fails the installation/upgrade when the number of replicas
given in values.yaml file is more than 2.
2. Adds the check to limit the number of replicas of secondary AKO
to one.
3. Pod anti-affinity rule to schedule the ako in different nodes.
Tested scenarios:
1. Helm Install/upgrade the AKO with replicaCount as 1,2,4.
The number of AKOs came up as 1, and 2 when replicaCount was 1 and 2. Got an error `ReplicaCount more than 2 is not supported.` when the replicaCount was 4.
2. helm install/upgrade with replicaCount more than 1 for secondary AKO
Install/upgrade failed with error `ReplicaCount more than 1 is not supported for secondary AKO.`
3. In a 3-node cluster, kept the …
> [HA] Changes in Statefulset

- internal/cache/controller_obj_cache.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vrf.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/dequeue_nodes.go
- internal/rest/k8s_utils.go
- internal/rest/rest_operation.go
- internal/rest/rest_utils.go
- internal/rest/ssl_key_certificate.go
This PR includes the following changes in the rest layer:
1. Adds a time delay before doing any REST operation towards the controller in the passive AKO to give the active AKO enough time to create objects in the controller.
2. In the passive AKO, all the REST operations are modified into GET operations, and the path in POST operation is modified to `path + "?name=" + objname`. Sometimes the GET operation for the path `path + "?name=" + objname` returns 0, added a retry so that active AKO creates the object and passive AKO reads the object in the subsequent GET calls.
3. During failover, there is a high chance to get 409 (object already exists) errors from the controller. The rest operation code is modified to build the cache and retry on getting a 409 error.
4. In passive AKO, the GET …
> [HA] Rest layer code changes

- internal/k8s/ako_init.go
- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/multicluster_ing_status.go
- internal/status/route_status.go
- internal/status/status_publisher.go
- internal/status/status_toiler.go
- internal/status/svc_annotation.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
This PR contains the status layer changes for HA. The following changes are added:
1. Converts status layer functions as methods. There will be two versions for active and passive ako. Active AKO updates the status and Passive AKO logs a message and returns.
> [HA] Status layer code changes

- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/leader_election_callbacks.go
- internal/status/statefulset_status.go
- internal/status/status_publisher.go
- pkg/utils/full_sync_worker.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
1. Allows the leader AKO to delete the objects in the controller created by
the AKO when the deleteConfig flag is set to True.
2. Leader AKO updates the statefulset annotation when the deleteConfig flag is set or unset.
> [HA] Configmap changes

- internal/cache/controller_obj_cache.go
This PR fixes an issue where the VSVIP key collection was empty in VS cache because of a wrong function call.
A wrong function `AviCacheGet` was called to get the VSVIP name by passing UUID. This PR corrects the code to call the function `AviCacheGetNameByUuid` with UUID to get the VSVIP name.
> [Bug fix] Fix for VSVIP key collection coming as empty in VS cache

- internal/nodes/avi_model_nodes.go
this will overwrite any ssl profile provided through CRDs
> AV-160077 Add AVI default SSL profile to pool to support older AVI versions

- docs/values.md
This PR corrects the reference URL mentioned in `podSecurityContext` section of values.md file.
> [doc] AV-164899: Corrects the podSecurityContext reference

- internal/cache/controller_obj_cache.go
This PR gives the ability to modify the SE group labels to any AKO which is coming up first irrespective of the leadership so that the labels will be present while route creation.
Tested scenarios:
1. Deleted static routes from the controller and verified whether routes are getting removed from the SE.
2. Rebooted the AKO and verified the routes are getting added in the SE.
3. Configured `deleteConfig` as false and verified the routes are getting removed from the SE.
4. Configured `deleteConfig` as true and verified the routes are getting added back in the SE.
5. Aviinfrasetting with SE group name.
> fix for AV-164932 

- internal/rest/avi_obj_vsvip.go
This commit fixes an issue where the VS VIP goes down with the error message `No network/subnet matched Virtual Service IP`.
On debugging the code, the AKO was not filling the discovered networks correctly in one PUT operation of VS VIP resulting in this error.
This commit ensures that the discovered network is filled correctly in VS VIP before the PUT operations.
Tested scenarios:
1. Deleted the ingress which resulted in a VS VIP PUT operation with the discovered networks in its payload.
> fix for AV-150791

- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/status/status_toiler.go
This PR fixes a crash issue seen in NPL deployments.
For NPL deployments the parameter `Key` was not filled in the `StatusOptions` from the rest layer and it was getting accessed at the follower AKO dequeue status method. Hence the crash.
With this commit, the parameter `Key` will be filled by the rest layer in all cases.
> fix for AV-165125

- internal/k8s/ako_init.go
This commit removes the wait time of 20 seconds for static route creation during bootup.
> fixes AV-165396

- hack/jenkins/get_build_path.sh
This PR is for adding a script to AKO repository, for getting the path where a specific build is stored in the build server. The script will take build number and branch name as parameters for computing the path. This script will be used by a Jenkins job, created for getting and submitting the SRP provenance data based on build number and branch.
> AV-166170 : Adding script to get build path for SRP data submission

- internal/k8s/ako_init.go
- internal/k8s/leader_election_callbacks.go
- internal/lib/avi_api.go
- internal/lib/constants.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
- internal/rest/rest_utils.go
This PR fixes an issue of status IP not getting updated for service type LoadBalancer in NodePortLocal deployments.
Tested scenario:
1. Created service of type LoadBalancer and immediately deleted the Leader AKO.
Results - Openshift:
```
|      Test Suite Path and Name : avi-                                             |                | …
```
> fix for AV-165655

- internal/lib/constants.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
This PR includes changes for enabling Application Profile configuration for L4 VS, by adding **ako.vmware.com/application-profile** annotation in LoadBalancer Services. The user can add the preferred Application Profile as value for **ako.vmware.com/application-profile** annotation in LoadBalancer Services. AKO reads the value for this annotation and configures the corresponding virtual service with the specified application profile.
> AV-168951 : Enable Application Profile configuration for L4 VS

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
`Issue`: In dedicated mode, when Aviinfrasetting is applied to ingress, on deletion of such ingress, AKO is not cleaning up VS and VS VIP.
`Fix`: This PR addresses this issue.
Testing: Create and delete ingress
1. Secure and Insecure SNI and EVH with aviinfrasetting applied and not applied.
> AV-168535: Delete VS when ingress/route deleted if there is no child associated with it

- docs/install/helm.md
- docs/values.md
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/k8s/validator.go
- pkg/utils/constants.go
- pkg/utils/utils.go
This PR adds a flag in values.yaml by using which the secret handling can be restricted only to the namespace where the AKO is present.
Tested Scenario:
Added 14K secrets in namespace test and rebooted the AKO.
```
root@shalini-python3-dev:/home/aviuser/swathin# ock get secret -n test | wc -l
14206
root@shalini-python3-dev:/home/aviuser/swathin
```
1. With the flag set as true
```
CONTAINER           CPU %               MEM                 DISK                INODES
0f3c6e9f6f45b       0.01                26.72MB             32.77kB             19
```
2. With flag set as false
```
CONTAINER           CPU %               MEM                 DISK                INODES
b929eb67e0602       0.24                456.5MB             16.38kB             19
```
> [Cherry-pick] AV-171375: Restricts secret handling by using a flag in values.yaml

- buildsettings.json
- tests/ingresstests/ingressclass_test.go
This commit adds a fix for UT TestUpdateIngressClassWithoutInfraSetting failing
cc @arihantg
> K8s supported version upgrade to 1.26 and TestUpdateIngressClassWithoutInfraSetting UT update

- internal/rest/avi_obj_vrf.go
Issue: If two clusters with name `orange` and `orange-new` are syncing to same Avicontroller, then rebooting AKO with clustername `orange` was deleting static routes of `orange-new`
Reason: AKO was doing prefix match for matching routes with clustername. That was causing issue.
Solution: USed regex to match routes belonging to same cluster.
> Resolve clustername overlap issue while creating static route for cluster

- buildsettings.json
- cmd/ako-main/main.go
- internal/lib/control_config.go
This PR contains:
1. Added retry logic while enabling Aviinfrasetting, HostRule and HttpRule and AKO POD during AKO reboot.
2. Changing Avi controller min version to 21.1.4
Total retries: 3 
Total retrytimeout: 6+ min
Non retryable Errors:  `Resource Not Found`, `UnAuthorized` , `Forbidden`
For Other errors: like `timeout`, `server timeout` etc, AKO will do 3 retries. Even after that, AKO could fetch resource, AKO will disable that CRD for that run
`Output for retryable errors`
-----
2023-04-10T05:58:09.746Z	WARN	lib/control_config.go:213	ObjectType: AviInfraSetting, Error: [Get "https://10.96.0.1:443/apis/ako.vmware.com/v1alpha1/aviinfrasettings?timeout=2m0s&timeoutSeconds=120": dial tcp 10.96.0.1:443: i/o timeout], Reason:[]
2023-04-10T06:00:39.747Z	WARN	lib/control_config.go:213 …
> AV-168279: Add retry logic for kube-api access

- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- helm/ako/crds/ako.vmware.com_hostrules.yaml
This PR corrects one issue in the hostrule CRD yaml file.
**Results**
```
swathins@swathinsQMD6M load-balancer-and-ingress-services-for-kubernetes % kubectl apply -f helm/ako/crds/ako.vmware.com_hostrules.yaml
customresourcedefinition.apiextensions.k8s.io/hostrules.ako.vmware.com created
swathins@swathinsQMD6M load-balancer-and-ingress-services-for-kubernetes %
```
> fix for AV-176917

- internal/rest/avi_obj_vs.go
- tests/dedicatedevhtests/l7_evh_crd_test.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
This PR fixes one issue while applying a hostrule with datascript references to a parent VS.
Also contains the UT to test the hostrule applied to Parent VS.
> [fix] fix for AV-174152

- internal/lib/constants.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- tests/servicesapitests/servicesapi_l4_test.go
This commit adds the changes to set System-TCP-Proxy as the network profile for the L4 VSes created from gateways when the license is ENTERPRISE. Also added a UT to test it.
UT result
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^TestServicesAPINetworkProfileBasedOnLicense$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests	15.153s
```
> AV-177293 fix 

- internal/lib/utils.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/dequeue_ingestion.go
- tests/integrationtest/l4_crd_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
This PR adds the l4rule support for shared VIP services.
FT Results:
> EVH - Non-dedicated
```
|      Test Suite Path and Name : avi-                                             |                |                     |             |             |
| dev/test/avitest/functional/ako/test_l4_rules.py                                 | …
```
> AV-177170: [L4 CRD] Shared VIP support

- internal/k8s/controller.go
This PR includes changes for fixing a bug because of which AKO was unable to properly process BlockAffinity CRD objects at runtime. Hence, for Calico CNI, AKO was unable to add or delete static routes for BlockAffinity CRD objects created at runtime. A sample BlockAffinity object looks like the following. AKO was trying to use the **name** field instead of **node** field in the spec.
```
apiVersion: crd.projectcalico.org/v1
kind: BlockAffinity
metadata:
name: aakash-k8s-10-133-0-0-26
spec:
cidr: 10.133.0.0/26
deleted: "false"
node: aakash-k8s
state: confirmed
```
> AV-175963 : Changes in event handler of BlockAffinity CRD to get the node name correctly for Calico CNI

- Makefile
- tests/calicotests/static_route_test.go
- tests/integrationtest/lib.go
This PR adds UT to check the changes in event handler of BlockAffinity CRD to get the node name correctly for Calico CNI. Now that AKO gets the node name correctly, it is able to configure static routes at runtime for BlockAffinity object addition and deletion.
> AV-175963 : UT for BlockAffinity addition and deletion support with Calico CNI

- internal/k8s/ako_init.go
Issue: AKO 1.10.1 taking 36 min to bootup for 193 nodes and 9k ingresses with 4k pods
Reason: As part of WCP merge, order of Object reading during AKO Full Sync is changed. As Ingresses were getting read first, all objects which can impact ingress object like httprule, ingressclass, aviinfrasetting etc. were causing update again on each ingress object leading to additional delay.
Resolution: Changed ordering back to older commit. It will solve delay issue.
> AV-180047: fix: AKO Bootup time is 36 min with 193 Nodes and 9k ingresses and 4k pods

- internal/status/route_status.go
**Fix**: The code to ignore the route status update when the insecure Edge Termination Policy set as `Allow` was at the wrong place which was preventing the status update in case of an AKO reboot.
**RCA**: AKO was posting the below data, which contains the details about the route, namespace, service metadata, etc, to the status layer during the AKO bootup.
```
[
...
{
"IngSvc": "",
"Vip": [
"10.10.7.24"
],
"ServiceMetadata": {
"namespace_ingress_name": null,
"ingress_name": "c5-010-rt-010",
"namespace": "c5-010",
"hostnames": [
"c5-010-rt-010.cluster5.vcd.k8s-systest.com"
],
"namespace_svc_name": null,
"crd_status": {
"type": "",
"value": "",
"status": ""
},
"pool_ratio": 50,
"passthrough_parent_ref": "",
"passthrough_child_ref": "",
"gateway": "",
"insecureedgetermallow": true, …
```
> AV-179484: Fixes the issue of no status when insecure Edge Termination Policy set as Allow

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
This PR changes the number of domains added to a dedicated VS. The autogenerated FQDN will not be added to a Dedicated VS even if the value of AutoFQDN is set as **flat** or **default**.
**What's changed:** The previous behavior was to add two domains - one from the ingress/route and the other an autogenerated one based on the flag AutoFQDN. As part of this PR, the autogenerated FQDN is removed from Dedicated VS as it is not required.
**Reason:**  The autogenerated FQDN is added to retain the VIP of Shared VSes when the AVI controller is used with Infoblox IPAM. This behavior is not required for a Dedicated VS since the VIP is not shared, and the IP can be released when the VS is removed.
**Tested Scenarios:**
Manually checked the absence of generated domain in VSVIP of a dedicated VS. …
> AV-179162: No Autogenerated domain for Dedicated Shard VS when AutoFQDN is `flat` or `default`

- docs/README.md
AKO 1.8.2 will support Avi controller version 22.1.3 and 22.1.4 with API version set as 22.1.2.
> AKO 1.8.2 support for 22.1.4

- internal/rest/avi_obj_vrf.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
Scenario tested:
1. Delete/Change static routes from Avi controller and check routes are properly synced or not.
2. Test concurrent update scenario (with delay introduced in vrfcontext code path) and check AKO is syncing vrfcontext to proper state or not.
3. `deleteConfig=true/false` in configmap and check static route sync.
4. `deleteConfig=true/false` in configmap and check static route sync in concurrent update scenario.
> AV-180534: Handle Concurrent update to VRFContext

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/rest/avi_obj_vs.go
- internal/status/svcapi_status.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/servicesapitests/servicesapi_l4_test.go
This PR adds support for mixed protocols for ports in LoadBalancer services and Gateway Services API. This support was missing due to error in implementation.
> AV-182960 : Fix to support mixed protocols for ports in LoadBalancer services and Gateway Services API

- helm/ako/templates/statefulset.yaml
This PR is for cherry picking changes for removing CTRL_CA_DATA env variable from AKO Statefulset definition as it is created from a secretKeyRef and violates CNTR-K8-001160 ([CNTR-K8-001160 - Secrets in Kubernetes must not be stored as e...](https://www.tenable.com/audits/items/DISA_STIG_Kubernetes_v1r5.audit:fdb2906c002a74a6f822c62bef0d8ed0) ). This was detected as part of https://jira.eng.vmware.com/browse/TKG-20458. The fix will just include removal of CTRL_CA_DATA env variable as it is not used by AKO. Instead, AKO reads the certificateAuthorityData directly from avi-secret (a kubernetes secret object) in the avi-system namespace.
> AV-183627 : Remove CTRL_CA_DATA env variable from AKO Statefulset definition as it violates CNTR-K8-001160 (#1199)

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/constants.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/httproute_status.go
- ako-gateway-api/status/status.go
- ako-gateway-api/tests/ingestion/gateway_test.go
- ako-gateway-api/tests/status/gateway_test.go
- ako-gateway-api/tests/status/httproute_test.go
- ako-gateway-api/tests/utils.go
This PR contains the following:
1. Validation of HTTPRoute objects.
2. Status layer changes for HTTPRoute objects.
3. UTs to test the HTTPRoute objects
TODO: FTs
UT results:
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^(TestHTTPRouteWithValidConfig|TestHTTPRouteWithAtleastOneParentReferenceValid|TestHTTPRouteTransitionFromInvalidToValid|TestHTTPRouteTransitionFromValidToInvalid|TestHTTPRouteWithNoParentReference|TestHTTPRouteWithAllParentReferenceInvalid|TestHTTPRouteWithNonExistingGatewayReference|TestHTTPRouteWithNonExistingListenerReference|TestHTTPRouteWithNonAKOGatewayControllerReference|TestHTTPRouteWithNoHostnames)$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/ako-gateway-api/tests/status
ok …
```
> AV-183085: [GatewayAPI] HTTPRoute Ingestion layer validation and Status layer code

- internal/nodes/avi_model_l4_translator.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
1. Add Hostname from external-dns.alpha.kubernetes.io/hostname only to the VSVIP and won't add any auto-generated FQDN.
2. UTs to check the number of FQDNs added to the VSVIP.
**Result:**
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^TestSvcExtDNSAddition$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest
```
> AV-180357 : Add Hostname from external-dns annotation only when AutoFQDN is flat or default

- ako-gateway-api/k8s/validator.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
1. HTTP Request policy based on the requestHeaderModifier
filters present in the HTTPRouteFilter.
2. HTTP Response policy based on the responseHeaderModifier
filters present in the HTTPRouteFilter.
3. HTTP Redirect policy based on the requestRedirect filters present
in the HTTPRouteFilter.
**UTs**: deferred
> HTTP Policies for GatewayAPI

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
- ako-gateway-api/tests/graphlayer/gateway_test.go
- ako-gateway-api/tests/graphlayer/httproute_test.go
- ako-gateway-api/tests/status/httproute_test.go
- ako-gateway-api/tests/utils.go
This PR contains the following:
1. Logic to figure out the Parent and child model for all the
objects pushed to the Graph layer.
2. Child VS deletion logic
3. Logic to delete stale child VSes
4. UTs to test the HTTPRoute, HTTPRouteRule, HTTPRouteFilter CRUD.
5. UTs to test HTTPRouteFilter of type RequestHeaderModifier,
ResponseHeaderModifier and RequestRedirect
**UT Results**:
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^(TestHTTPRouteCRUD|TestHTTPRouteRuleCRUD|TestHTTPRouteFilterCRUD|TestHTTPRouteFilterWithRequestHeaderModifier|TestHTTPRouteFilterWithResponseHeaderModifier|TestHTTPRouteFilterWithRequestRedirect)$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/ako-gateway-api/tests/graphlayer
ok …
```
> [GatewayAPI]code to process Service, Endpoint and Route objects

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
This PR adds the following changes:
1. Code to process HTTPRoute objects during bootup.
2. Optimization to process the GatewayAPI objects once during bootup.
3. Get the object from DeltaFIFO if the delete event is missed.
4. Bug fixes.
> [GatewayAPI]Code to process objects during fullsync and bug fixes

- internal/objects/infrasetting.go
- internal/objects/store.go
- tests/ingresstests/ingressclass_test.go
This PR fixes the issue of VS and Pools not getting deleted when multiple ingress use same aviinfrasetting for shard size.
This issue is see when two ingress use the same ingress class and the ingress class refers to an aviinfrasetting object which sets the shard size. The vs and pool creation works fine. But on deleting the first ingress, the shard size to avinfrasetting mapping was also getting deleted even though it should still be in use with the second ingress. So, when the second ingress is deleted, the shard size from avinfrasetting object is not considered and hence wrong model name was calculated leading to failure in deletion.
Fix:
Check the ingress to aviinfasetting mapping in **IngRouteInfraSettingStore**. If no mapping exists, then only delete the shard size to …
> AV-184860 : VS and Pools not deleted when multiple ingress use same infrasetting for shard size

- ako-gateway-api/nodes/avi_model_l7_translator.go
- cmd/gateway-api/main.go
This PR adds the logic to populate the pool servers in NodePort deployments.
**Test scenario:**
Manually updated the `serviceType` to `NodePort` and verified the pool servers populated from the controller GUI.
> AV-187992: NodePort Implementation for GatewayAPI

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/gatewayclass_status.go
- ako-gateway-api/status/httproute_status.go
- ako-gateway-api/status/status.go
- ako-gateway-api/tests/status/gatewayclass_test.go
This commit adds the following:
1. Status update of GatewayClass during ingestion
2. Status layer changes for GatewayClass
3. minor fixes
4. Adds UTs to test the status layer changes for GatewayClass 
**UTs**:
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^(TestGatewayClassValidation|TestGatewayClassWithNonAKOController)$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/ako-gateway-api/tests/status
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/ako-gateway-api/tests/status	20.620s
```
> AV-187995: GatewayClass status layer changes

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
1. fixes the stale mappings present in the store.
2. Pool removal when the service referred in the `backendRef` is removed.
3. UTs to test the backendRef updates
**UT Results:**
```
Running tool: /usr/local/go/bin/go test -timeout 1000s -run ^(TestHTTPRouteCRUD|TestHTTPRouteRuleCRUD|TestHTTPRouteFilterCRUD|TestHTTPRouteFilterWithRequestHeaderModifier|TestHTTPRouteFilterWithResponseHeaderModifier|TestHTTPRouteFilterWithRequestRedirect|TestHTTPRouteWithValidConfig|TestHTTPRouteBackendRefCRUD|TestHTTPRouteBackendServiceCDC|TestHTTPRouteBackendServiceUpdate)$ github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/gr …
```
> [GatewayAPI] Pool removal on Service deletion and other minor fixes

- docs/install/helm.md
- docs/values.md
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
This PR adds imagePullSecrets support for AKO in Helm chart. This will enable the user to store the AKO image in their own private registries and use the imagePullSecrets to pull the AKO image on their cluster from their own private registry.
TO DO : Documentation
> AV-188019 : Adding ImagePullSecret support for AKO in Helm Chart

- internal/lib/constants.go
- internal/lib/utils.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
1. logic to reduce the length of the label created by the AKO when the AutoFQDN is set as flat for service of Type LB.
2. Consider only the fqdn in the `external-dns.alpha.kubernetes.io/hostname` when configured with AutoFQDN as flat or default for Service of type LB and shared VIP LB service.
3. UTs to test various scenarios.
**Logic:** https://confluence.eng.vmware.com/display/~swathins/Bug%3A+AV-180357
**Relevant part of RFC 1035:**
```
The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.
```
**UT:**
```
go test -timeout 1000s -run …
```
> AV-180357: Limit the Label length as per RFC1035 to 63 chars when AutoFQDN is set as flat 

- internal/rest/rest_operation.go
`err` from avi controller was getting typecasted wrong. This was causing issue in AKO retry mechanism.
> Fix: AV-189167: remove improper conversion of error structure

- internal/nodes/ingress_model_rel.go
In AKO, HTTPrule is namespace specific.  So if customer creates two ingresses say ingress1 and ingress2 with same fqdn.
ingress1 is in namespace default with path /path1 and ingress2 is namespace red with path /path2 . Then customer creates 2 httprule, rule1 and rule2.
rule1 is applied to ingress1/path1 and rule2 is applied to ingress2/path2 . So when rule2 is applied, configuration done by rule1 on pool is getting removed.
> AV-189284: Fix httprule issue overwriting other httprule setting applied to ingress with same fqdn with different path.

- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- pkg/utils/constants.go
This PR adds retries for **unauthorized** error while getting or listing routes with route informer. There were some random Unauthorized errors seen and adding retries may help in solving those.
```
2023-09-23T15:25:03.059Z	WARN	status/route_status.go:201	msg: Could not get the route object for UpdateStatus: an error on the server ("Internal Server Error: \"/apis/route.openshift.io/v1/namespaces/c6-002/routes/c6-002-rt-008-p1\": Unauthorized") has prevented the request from succeeding (get routes.route.openshift.io c6-002-rt-008-p1)
```
> AV-187521 : Adding retires for unauthorized error while getting routes with informer

- internal/lib/lib.go
> use first IP in case of multiple internal IPs for node (#1082)

- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/k8s/leader_election_callbacks.go
This PR adds the logic to go over all the CRDs present in the cluster and validate it. The validation would trigger an UPDATE event that will update the models and eventually, the configurations will get applied on the AVI objects when the CRD is marked as Accepted.
This PR also adds the code to track the state of AKO and a state machine to handle the transition during leader elections.
> AV-180407: CRD validation after failover

- docs/ovn-kubernetes.md
- internal/lib/dynamic_client.go
This PR is for adding support to read Pod CIDR subnet(s) for OVN-Kubernetes CNI in OpenShift 4.13 or higher versions. The OVN-Kubernetes CNI configures the Pod CIDR subnet(s) on each node as part of the **k8s.ovn.org/node-subnets** annotation. AKO reads the **default** pod CIDR subnet value(s) from this annotation for each node and configures the required static routes on the Avi controller. However, the format of this annotation has changed starting OpenShift 4.13. Some sample annotation values are shown below.
For OpenShift version less than **4.13 :** 
```
k8s.ovn.org/node-subnets: '{"default":"10.128.0.0/23"}'
```
For OpenShift version **4.13** or higher **:**
```
k8s.ovn.org/node-subnets: '{"default":["10.128.0.0/23"]}'
```
> AV-190776 : Add support to read Pod CIDR subnet(s) for nodes with OVN-Kubernetes CNI in OpenShift 4.13

- Makefile
- internal/nodes/avi_model_evh_nodes.go
- internal/rest/avi_obj_vs.go
- tests/dedicatedevhtests/l7_evh_crd_test.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
This PR fixes the regression introduced in AKO 1.11.1 for SNI Dedicated L7 VS while adding SSL Key Cert Ref using hostrule. This issue has been detected as part of https://avinetworks.atlassian.net/browse/AV-193232. This issue was because the same SSL Key Cert Ref was appended twice to the virtual service SSL Key and Cert Refs List in case of SNI Dedicated L7 VS.
> AV-193232 : Fix for regression introduced in 1.11.1 for SNI Dedicated L7 VS while adding SSL Key and Cert Ref using hostrule

- .gitignore
- Makefile
- ako-operator/Makefile
This PR is for generating cover profile for AKO UT's from Makefile. An additional -coverprofile flag has been added to each go test command. This will generate coverage report (cover.out file) for each go test command. These coverage reports will be consumed by a downstream Jenkins job and fed to Sonarqube for generating aggregated code coverage.
> AV-194094 : Cover profile generation for AKO UT's from Makefile for coverage report in Sonarqube

- cmd/ako-main/main.go
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/lib/avi_api.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
- internal/status/status_toiler.go
- pkg/api/api.go
- pkg/api/api_fake.go
- pkg/api/models/models.go
- pkg/api/models/status.go
1. Number of objects in Ingestion, Graph, Status, retry(slow,fast) queues
2. Number of API calls made by AKO to Avi Controller
3. Number of API calls per Object per type made by AKO to Avi Controller
TODO:
This PR doesn't take care of fetching `conntectivity status of AKO with Avi Controller`, `number of nodes in K8`
> AV-193761: Prometheus metrics publish for

- CHANGELOG.md
- buildsettings.json
- docs/README.md
- docs/install/helm.md
- docs/openshift/openshift_helm.md
- vendor/github.com/vmware/alb-sdk/go/models/bgp_profile.go
- version.yaml
This PR is to fix the issue of AKO not creating static routes when a value greater than **2147483647** is specified for **LocalAs** (Local Autonomous System ID) field in Bgp profile. This scenario is applicable only when Bgp profile is specified for VRF Context. The type for **LocalAs** field was **int32** and hence a value greater than **2147483647** was not accepted. Now, the type has been changed to **unit32**.
> AV-194491 : Setting local_as field type in bgp profile of vrf context to uint32 to avoid parsing error

- CHANGELOG.md
- vendor/github.com/vmware/alb-sdk/go/models/bgp_peer.go
This PR is an extension of https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1342.
> AV-194491 : Setting local_as and remote_as fields type for bgp peer to uint32 to avoid parsing error

- Makefile
- internal/k8s/ako_init.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- tests/dedicatedevhtests/l7_evh_crd_test.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
UT Tests:
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests      154.323s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedevhtests     279.278s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1042.875s
```
```
PASS
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests  955.852s
```
> AV-195886: Fix for missing SSL port on adding HostRule with SSL cert to insecure Dedicated VS

- internal/k8s/controller.go
This task is to identify and reject irrelevant update events for Kubernetes objects in AKO. AKO will identify the events based on certain criteria and not do any further processing for those events. The purpose of this task is to avoid processing large number of irrelevant events like CrashLoopBackoff in pods that will eventually prevent AKO from catching up to the changes to the LoadBalancers and Ingresses.
> AV-196761 : Identify and reject irrelevant update events for Kubernetes objects in AKO

- internal/k8s/controller.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/dequeue_nodes.go
this issue caused AKO to not update existing PKI profile and workload certificate not being updated, and therefore traffic failure on FTs on subsequent runs
> AV-189304 Fix Istio incorrect cache retrieval

- Makefile
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
This commit makes the following change:
- To ensure that race condition does not happen in case of status update/delete of ingresses, key on which sharding was done to status queue is now changed from ingressname to hostname, to ensure that status changes of particular hostname will always get enqueued in same queue and sequential flow will be present
> AV-195118: Fixing race condition in status layer

- cmd/ako-main/main.go
- docs/akoconfig.md
- docs/values.md
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/crdcontroller.go
- internal/lib/avi_api.go
- internal/lib/control_config.go
- internal/lib/lib.go
Following is manual testing done:
1. NodePort mode:
a. If VRF is set in configmap, use that else use Global VRF
2. ClusterIP mode for Vcenter cloud only
a. Test VRF is valid or not.
b. Test VIP network, mentioned in Configmap, is under the VRF, mentioned in configmap, or not.
c. Test Node network list (used for pool placement network) is under the VRF or not.
d. Create a new VRF in admin tenant and check all objects are getting created under given vrf including static routes.
e. Use `test` tenant and VRF `global` present under `admin tenant` to check all objects are getting created under given tenant and global vrf or not.
UT Pending: Need to check how to do UT for this scenario
> AV-197474: VRF support in vcenter cloud

- ako-gateway-api/nodes/dequeue_ingestion.go
This PR is for removing model saving after each child deletion to allow model saving and publishing once in DequeueIngestion. This will delete the old child VS and create the new child VS. When the matches section is updated in HTTPRoute, a new child vs should be created.
> AV-196436 & AV-196437 : Removing model saving after child deletion to allow model saving and publishing in DequeueIngestion for new child creation

- ako-gateway-api/k8s/ako_init.go
AV-198407 Fixing parent vs creation for gateways created before bootup
This PR fixes creation of parent vs when gateway is created first and then AKO is started.
Since the gateway code s similar to AKO's code, PublishToRestLayer is called only by the leader in HA mode in AKO
However in Gateways, since we are yet to model Gateways behaviour in HA mode, I am temporarily disabling check for sync==True, to enable publishing all parent VSes to RestLayer
> AV-198407 Fixing parent vs creation for gateways created before bootup

- Dockerfile.ako
- Dockerfile.ako-gateway-api
- Dockerfile.ako-infra
- Dockerfile.ako-operator
- Makefile
This is temporary fix till we resolve 
1. Upgrade all build vms to latest docker so that we will use golang:latest image for testing
2. Resolve buildvcs issue with permanent fix.
> Fix: Failure in go build and go test in AKO

- ako-gateway-api/k8s/validator.go
- pkg/utils/constants.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/status/gateway_test.go
AV-199356 Added Validations for AllowedRoutes in Gateway Listener Validations.
- This PR adds validations to reject Gateways with Listeners having `Invalid Listener -> allowedRoutes -> kinds -> kind` and `Invalid Listener -> allowedRoutes -> kinds -> Group`.
- Unit TestCases for Ingestion and Graph Layer
> AV-199356 Added Validations for AllowedRoutes in Gateway Listener Validations

- ako-gateway-api/k8s/validator.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/gateway_test.go
AV-199142 Validation for Multiple Gateways with Overlapping hostnames
This PR:
- Adds validation for rejecting multiple Gateways with Listener having same hostname.
- Adds validation for rejecting multiple Gateways with Listener having overlapping hostname
- Unit TestCases for both of these scenarios
> AV-199142 Validation for Multiple Gateways with Overlapping hostnames

- ako-gateway-api/k8s/ako_init.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
The issue is with the user name used by ako-gateway for created_by field in rest requests for Avi objects and for the name prefix used by ako-gateway to create the Avi objects. The issue is a regression added as part of changes for validating the values.yaml fields. The values set by ako-gateway for user name and name prefix are over-written by validator function. Hence, we are moving out the code for setting the user and name prefix out of the validator function.
> AV-200194 : Regression for user and name prefix in ako and ako-gateway

- Makefile
- pkg/utils/events.go
Tested by running Ut with invalid HTTP route and enabling eventrecording . 
`no kind is registered for the type v1.HTTPRoute in scheme "pkg/utils/events.go:40"
`
was replaced in logs by
`
2024-02-21T13:22:35.758+0530    ERROR   k8s/validator.go:227    key: HTTPRoute/default/httproute-06, msg: HTTPRoute object httproute-06 is not valid
2024-02-21T13:22:35.758+0530    INFO    record/event.go:299     Event(v1.ObjectReference{Kind:"HTTPRoute", Namespace:"default", Name:"httproute-06", UID:"", APIVersion:"gateway.networking.k8s.io/v1", ResourceVersion:"2024-02-21 13:22:35.757036 +0530 IST", FieldPath:""}): type: 'Warning' reason: 'Detached' HTTPRoute object httproute-06 is not valid`
> AV-199357 register gatewayapi for event recording

- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- internal/cache/controller_obj_cache.go
- tests/gatewayapitests/graphlayer/httproute_test.go
This PR fixes issue which was discovered while running **test_httproute_multiple_hosts** test case in **test_http_route** test suite. The results are shared below.
```
|      Test Suite Path and Name : avi-dev/test/avitest/functional/ako/ako-gw-      |                |                     |             |             |
| …
```
> AV-197532 : HTTPRoute with multiple hostnames attaches invalid hostname to the child vs

- docs/values.md
- helm/ako/templates/secret.yaml
- helm/ako/values.yaml
- tests/helmtests/avi-secret_test.yaml
This PR is to allow AKO to use existing avi-secret in avi-system namespace. If username and either of password or authtoken are not specified in Helm chart values.yaml, avi-secret will not be created as part of Helm installation. AKO will assume that avi-secret already exists in avi-system namespace and will reference it.
> AV-201231 : Allow AKO to use existing avi-secret in avi-system namespace

- internal/nodes/ingress_model_rel.go
The PR fixes the issue of attachment of aviinfrasetting to routes if aviinfrasetting is accepted after annotation addition to the route. The FT for the case can be found as part of this PR : https://github.com/avinetworks/avi-dev/pull/115457
> AV-200223 : AVIInfra Passthrough route is not getting created if aviinfrasetting is accepted later

- docs/roles/ako-tenant.json
When AKO is running with non-admin user, with customized role, it required `READ` permission to read tenant resources. Otherwise there will be failure in bootup.
> Update ako-tenant.json: Allow user from this tenant to read tenants.

- internal/rest/dequeue_nodes.go
AKO was throwing follwowing panic error
panic: interface conversion: interface {} is *cache.AviPkiProfileCache, not cache.AviPkiProfileCache
> Fix Istio failure due to panic

- internal/nodes/dequeue_ingestion.go
Test results are given below for NPL. Only failures are for udp traffic as the client script was not updated correctly.
```
|      Test Suite Path and Name : avi-                                             |                |                     |             |             |
| dev/test/avitest/functional/ako/test_lbsvc.py …
```
> AV-205285 : Shared VIP virtual service is not re-created if the LB service with incorrect configuration is deleted for NPL

- buildsettings.json
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
- tests/integrationtest/l4_service_test.go
We had introduced this changes to have uniform behaviour for L4 and Ingress. As L4 service has same naming convention with aviinfrasetting and without aviinfrasetting, L4 service was getting deleted due to this changes if infrasetting is not proper. This is causing issue in some scenarios.
So this PR is fixing that.
> Allow LB to process even after aviinfrasetting is not valid.

- ako-infra/ingestion/vcf_k8s_controller.go
- internal/k8s/ako_init.go
- internal/lib/avi_api.go
- pkg/utils/avi_rest_utils.go
- tests/scaletest/lib/utils.go
This PR increases the timeout for Avi client to 2 minutes as we are getting `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` error for **sslkeyandcertificate** PUT request in large setups.
> AV-205715 : Increase timeout for avi client to two minutes

- internal/nodes/avi_vrf_translator.go
- tests/cnitests/static_route_test.go
AV-205437 Static Route fix
This PR fixes following issue with Static routes:
If we have multiple nodes with multiple PODCidrs, if we delete all block affinities on any of intermediate node, the NodeId and NodeStaticRoute arrays and nodes gets deleted which results in a continuous route_ids(since we have handled it in delete and update case). However, if we delete all static routes from controller and reboot ako, the Node, NodeIds and NodeStaticRoute gets added even if number of block affinities are 0 for that node(Since we had not handled addition case earlier). As a part of the fix, if number of static route/PODCidrs attached to the Node are zero, we will not add Node, NodeIds and NodeStaticRoutes to the VRF node
> AV-205437 Static Route fix

- internal/rest/avi_obj_vs.go
This PR addresses the issue of Follower AKO keeps on restarting after setup creation. The follower was getting OOMKilled due to status update in happening in bulk. The status update has been disabled for follower as it was only processing the status update operations but ultimately not doing anything.
> AV-205976 : disabling status update for vs and pool from follower

- docs/gateway-api/gateway-api-v1.md
Gateway API Doc fix
Due to <> brackets in Gateway API objects naming conventions, the rendered naming conventions had missing values for data inside <>. This PR fixes that issue.
> Gateway API Doc fix

- internal/rest/dequeue_nodes.go
AKO would shutdown due to panic during cache retrieval
> AV-206693 Fix panic with Istio

- ako-gateway-api/k8s/validator.go
- ako-gateway-api/objects/gateway_store.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/status/httproute_test.go
AV-206565 Fix for AKO GW crash when HttpRoute attaching to one existing and one non existing gateway.
This PR fixes ako gw crashes we were seeing due to index mismatch in httpRoute->Status->Parent validation.
**Reason for crash**: In case of non-existent gateway or gateway having gateway class with a different controller, we are not setting anything in httpRoute status corresponding to this parent which is correct as per Gateway API Spec, however when we were trying to set something at next index in httpRoute->Status->Parent for the next valid parent i.e. at 1 index a panic was seen leading to ako gw container crash since we were adding entry at 0th index and trying to update it at index 1.
**Testing Done:**
Added a Unit Test Case simulating the same scenario.
> AV-206565 Fix for AKO GW crash when HttpRoute attaching to one existing and one non existing gateway

- internal/cache/controller_obj_cache.go
At bootup AKO was making calls to populate httppolicy set in cache for each VS if it was finding missing match in cache for any external policyset.  With this fix we will fetch the missing policyset by uuid and add it to cache.
> AV-205821 add external httppolicyset in cache

- internal/lib/utils.go
- internal/nodes/avi_model_l4_translator.go
- tests/npltests/npl_pod_test.go
AKO does not honour readines probe for pods when Antrea with NPL is used. AKO was setting the npl ip and port in the pool server even if the pod was not ready. Now, AKO will not populate the pool servers if the pod is not ready. Also, if the pod was initially ready and running and becomes not ready later, the servers will be removed from the pool.
> AV-209807 : AKO does not honour readines probe for pods when Antrea with NPL is used

- ako-gateway-api/nodes/avi_model_l7_translator.go
AV-209065 Gateway container crash fix
This PR fixes the regression introduced due to the length check removed as a part of this PR https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1382/files#diff-58c8f75b8707ea2e7bb3d1df4ed00cf35aa868544a55ed54876e6318ddafcef8 which causes gateway container crash when multiple gateways and multiple httproutes shares same backend app and httproute tries to connect to the the gateway listener which is not its parent.
**Testing status:**
Crash scenarios tested
Manual testing for gateway with and without the section name
> AV-209065 Gateway container crash fix

- tests/npltests/npl_pod_test.go
Thsi PR adds a UT to test that AKO now honours readines probe for pods when Antrea with NPL is used for LoadBalancer service. Previously UT was only added for ingress. Also, small changes have been made in the previously added UT to fix some issues.
> AV-209807 : Adding UT to test AKO now honours readines probe for pods when Antrea with NPL is used

- ako-gateway-api/k8s/gateway_controller.go
- cmd/gateway-api/main.go
This PR:
- removed pod informer being initialized incorrectly
- halts the gateway-api container when nodeportlocal is enabled
> AV-206828 Fix AKO-GW container crash when NPL enabled

- ako-gateway-api/lib/constants.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- internal/cache/controller_obj_cache.go
- internal/rest/avi_obj_string_group.go
AV-210421 StringGroup cache fix for Gateway
**Issue:** SinceStringGroup object does not have a created_by field, the GET call on the controller was always giving an empty response when objects were fetched using created_by field resulting into failure in cache update.
**Changes:** AKO will now fetch StringGroup objects on the basis of name.contains "ako-gw"+ clustername prefix
Also as a part of this PR, StringGroup names will be prefixed with Clustername
**Testing Done:**
Manually tested CRUD and reboot scenarios. No error in cache updation is seen
> AV-210421 StringGroup cache fix for Gateway

- tests/gatewayapitests/utils.go
root@akshay-dev-box:/var/work/load-balancer-and-ingress-services-for-kubernetes# make gatewayapitests
sudo docker run \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /var/work/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests		coverage: 0.0% of statements
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer	244.725s	coverage: 17.5% of …
> Gateway UT fixes

- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/k8s/validator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/crd_translator.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- internal/rest/k8s_utils.go
- internal/status/ing_status.go
- internal/status/multicluster_ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
This Pr add an annotation specifying the tenant name of vs in ingress,routes,lbsvc and mci
Testing done:
Update from default to tenant named "tt" on ingress and LBsvc
Update from  "tt" tenant to tenant named "tt2" on ingress and LBSVC
Hostrule re-validation on tenant update to "tt" and "t2" tenant
> AV-208387 add tenant annotation for AMKO consumption

- internal/rest/dequeue_nodes.go
```
aviuser@avi-dev:~/load-balancer-and-ingress-services-for-kubernetes$ make int_test > out.txt
aviuser@avi-dev:~/load-balancer-and-ingress-services-for-kubernetes$ grep -w ok out.txt
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/k8stest	30.408s	coverage: 9.0% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest	484.065s	coverage: 26.9% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests	975.908s	coverage: 39.3% of statements in ./...
ok  	github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests	1328.222s	coverage: 38.8% of statements in ./...
ok …
```
> AV-214324: Skip Default cert cleanup when cleaning up a VS

- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/dedicatedvstests/l7_dedicated_rest_test.go
file changes for dedicatedvstests
replaces names for following resources with suffixed variants
- secrets
- infrasettings
UT run for dedicatedvstests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/dedicatedvstests      155.556s
> AV-210932 Improve UT runtime (dedicatedvstests)

- ako-gateway-api/nodes/avi_model_l7_translator.go
- tests/gatewayapitests/graphlayer/httproute_test.go
There is a change in this PR: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1468
which addresses part of the issue AV-216010 so both PR has to be merged to address the issue AV-216010
> AV-216010: Fix http policyset creation fails with error no port specified for httproute and Gateway without hostname

- ako-gateway-api/nodes/gateway_model_rel.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/gatewayclass_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
- tests/integrationtest/l4_crd_test.go
****PR is addressing issue ***
AKO gateway was failing to create child VS when HTTPRoute with multiple/single matches and single hostname is attaching to a Gateway with multiple listeners. Each listener will have same Host with different port. In HttpRoute, there is only name of  gateway mentioned in parent ref.
> AV-210402: Fix: AKO-Gw: Child VS creation fails with duplicate FQDN in VHMatch creation

- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- internal/nodes/avi_model_evh_nodes.go
- tests/gatewayapitests/graphlayer/httproute_test.go
AV-208589 RouteToChildVs mapping fixes.
This PR fixes following issues with one HTTPRoute getting connected to 2 Gateways:
- Hostname of first parentVS/Gateway listener being appended to the second parentVS' DNS fqdn
- RouteToChildVS mapping resulting into child VSes not getting deleted
Testing Status:
Unit Test Cases added.
Manual Testing Done.
Unit Test run attached
FT run attached
> AV-208589 RouteToChildVs mapping fixes

- Makefile
- internal/k8s/crdcontroller.go
- pkg/utils/utils.go
- tests/urltests/url_validation_test.go
This PR removes double encoding for URI. Also adds two log statements. Similar changes have already been merged to release-1.12.2 branch as part of https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1522.
> AV-216533 : Remove double encoding for URI (#1522)

- ako-gateway-api/lib/constants.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
Adding a default backend "/" http policy set which will return 404 if the path is not met. This will also return 404 if there is no hostname match.
Case 1: Success
Case 2: Wrong path
Case 3: Wrong path but http route is "/" . This goes till the backend
Case 4: Wrong host
Case 5: Wildcard hostname
Pending Case:
Empty hostname
> AV-199140: Add default HTTP policy set for default-backend 404

- tests/ingresstests/crd_test.go
- tests/ingresstests/ingress_annotation_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
- tests/ingresstests/l7_rest_test.go
- tests/ingresstests/lib.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_secure_route_test.go
file changes for ingresstests
UT results
ok github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/ingresstests 1102.513s
NOTE: this PR skips the test case TestCreateIngressWithFaultCacheSync. the case will be updated and fixed as separate PR
> AV-210932 Improve UT runtime (ingresstests)

- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/evhtests/l7_evh_rest_test.go
file changes for evhtests and vippernstests
UT results
vippernstests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1483.889s
evhtests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/evhtests      1573.992s
> AV-210932 Improve UT runtime (evhtests, vippernstests)

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/status/status.go
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_pool_group.go
AV-218385 ChildVS Deletion should not update Gateway listener status
This pr will make sure that creation/updation/deletion of childVS should not update gateway listener status
Testing status:
Manually tested creation/updation/deletion of HTTPRoute leading to the deletion of childVS and not updating anything in gateway status.
TODO:
Attach UT run results
Attach FT run results
> AV-218385 ChildVS Deletion should not update Gateway listener status

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/objects/gateway_store.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/gatewayclass_status.go
- ako-gateway-api/status/httproute_status.go
- ako-gateway-api/status/status.go
- internal/status/ing_status.go
- tests/gatewayapitests/ingestion/gateway_test.go
```
**********************************************************************************************************************************
|      Test Suite Path and Name : test/avitest/functional/ako/ako-gw-              |                |                     |             |             |
| api/test_http_route.py …
```
> AV-206829 move gateway/route status updates to status layer

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_validator.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/gatewayclass_status.go
- ako-gateway-api/status/httproute_status.go
- ako-gateway-api/status/status.go
- internal/lib/constants.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
AV-219152 Moving HTTPRoute Validation to Graph layer
> AV-219152 Moving HTTPRoute Validation to Graph layer

- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/httproute_status.go
```
make gatewayapitests 
sudo docker run \
-e ENDPOINTSLICES_ENABLED="false" \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/myfork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests               coverage: 0.0% of statements
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    472.123s        coverage: 18.4% of statements …
```
> AV-206824 Update port in vhmatch of child vs

- ako-gateway-api/k8s/validator.go
- tests/gatewayapitests/status/gateway_test.go
```
make gatewayapitests 
sudo docker run \
-e ENDPOINTSLICES_ENABLED="false" \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/myfork/load-balancer-and-ingress-services-for-kubernetes:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests               coverage: 0.0% of statements
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    444.186s        coverage: 18.4% of statements …
```
> AV-220211 check listener protocol at start of validation

- ako-gateway-api/nodes/avi_model_l4_translator.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/nodes/route_validator.go
- ako-gateway-api/objects/gateway_store.go
- ako-gateway-api/status/status.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/status/httproute_test.go
AV-206859 Setting ResolvedRef Condition in HTTProute
Testing Status:
Manual Testing done
Unit TestCase added
> AV-206859 Setting ResolvedRef Condition in HTTProute

- ako-infra/ingestion/avi_infra_controller.go
- cmd/infra-main/main.go
- internal/cache/controller_obj_cache.go
Tests Done -
1)Restarted AKO in SV cluster for already working setup, cloud gets picked using old value set in namespace annotation.
2)Removed cloud from namespace annotation and restart AKO, cloud associated with VS "'cluster name'--kube-system-kube-apiserver-lb-svc" gets picked.
3)Failed/Bypassed the above 2 check by introducing some code and cloud gets picked through old method.
> AV-220244: Check for Namespace annotation and VS lb svc for determining the correct cloud

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_validator.go
- ako-gateway-api/objects/gateway_store.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/utils.go
This PR contains fix for 2 issues:
1. [AV-221779] : Fix secret and gateway re-ordering
2. [AV-222515]: AKO-Gateway: Gateway status conditions are not reflected correctly on deleting certificate associated with gateway
TODO: It doesn't take care of deleting Parent VS if no certificate attached to it. Parent VS will be there with default-cert.
> Av 221779 Fix secret and gateway re-ordering

- Makefile
AV-223305 Fix coverpkg for gateway UTs in Makefile
-coverpkg flag in docker run for gateway FTs was analysing coverage in entire load-balancer-and-ingress-services-for-kubernetes due to which Ut coverage %age was lower. These changes will make changes in Make file to analyse only directories which are relevant for Gateway Uts.
UT coverage w/o these changes:
```
ok      [github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer](http://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer)    493.161s        coverage: 18.2% of statements in ./...
ok      [github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/ingestion](http://github.com/vmware/load-balancer-and-ingre …
```
> AV-223305 Fix coverpkg for gateway UTs in Makefile

- internal/rest/ssl_key_certificate.go
The **test_regex_app_root_secure_vs** test in test_http_rules test suite was failing because of this issue and now it runs fine. FT Run Results :
```
|      Test Suite Path and Name : avi-                                             |                |                     |             |             |
| …
```
> AV-223927 : Check PKIProfile Cache for existing pkiprofile while computing pkiprofile for new pool

- internal/cache/controller_obj_cache.go
On AKO boot-up, PKIProfile cache is not updated as cloud_ref is used in the get request URI. But, when PKIProfile is created cloud_ref is not populated. So, removed cloud_ref from the get request URI.
Without the fix, PKIProfile cache is not not populated and leads to POST request for existing PKIProfile causing 409 error.
```
2024-12-19T08:53:12.842Z	INFO	cache/controller_obj_cache.go:136	Refreshing all object cache
2024-12-19T08:53:12.883Z	DEBUG	cache/controller_obj_cache.go:1637	Adding key to sslkey cache :{admin kubernetes-calico--my-infrasetting-test-grpc-host.avi.internal}
.
.
.
2024-12-19T08:53:14.275Z	WARN	rest/rest_operation.go:307	key: admin/kubernetes-calico--Shared-L7-0, msg: RestOp method POST path /api/pkiprofile tenant admin Obj {"ca_certs":[{"certificate":"-----BEGIN …
```
> AV-225892 : PKIProfile cache is not updated as cloud_ref is used in the get request URI

- ako-clean/cleanup.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/lib/utils.go
The issue [AV-228042](https://vmw-jira.broadcom.net/browse/AV-228042) was due to pagination issue in GetAllTenants function.      
PopulateCache Changes - moved away from populating cache on per tenant basis instead using * in X-Avi-Tenant to list all the objects in all the tenants at once. This would ensure that PopulateCache does not become a bottleneck in a scaled environment
> AV-228042 Fixed pagination issue in GetAllTenants and Populatecache changes

- AKO_GATEWAY_CHANGELOG.md
- CHANGELOG.md
- docs/install/helm.md
- docs/openshift/openshift_helm.md
This PR adds release notes for AKO 1.13.1 release. It also updates missing release notes for older 1.12.x releases in changelog for master branch.
**Note :** I have changed the base/destination branch from master to release-1.13.1 in this PR as Jeya's automation already update the helm chart version to 1.14.1 after we had the build leading to conflicts.
> AV-228261 : Add release notes for AKO 1.13.1 release

- Makefile
- buildsettings.json
- docs/README.md
- internal/nodes/dequeue_ingestion.go
- tests/integrationtest/l4_crd_test.go
- tests/integrationtest/l4_service_test.go
This PR cherry-picks commit from https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1641. It also updates K8s version as required by the customer. Also updates OpenShift version in document based on K8s version.
> AV-226793 : For shared-vip, when service type is changed from LB to ClusterIP and reverted, ako does not create the VS

- ako-gateway-api/lib/constants.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/nodes/route_validator.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/npltests/gateway_npl_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
- tests/integrationtest/lib.go
This PR handles RegexPAth support in GatewayAPI. We can add regex validation as part of code also as per PCRE standards.
> AV-231547:Regex path support in GatewayAPI

- tests/evhtests/l7_evh_crd_test.go
No hostname ingress Test case in EVH was failing due to EVH child was not getting created as there was no subdomain presents as it was getting removed in latest added UT
> Fix UT Failure in evh

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/nodes/route_validator.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
AV-231513 HTTPRoute Rewrite Filter
> AV-231513 HTTPRoute Rewrite Filter

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_obj_l4ps.go
This change fixes the issue observed in the PR https://bugzilla-vcf.lvn.broadcom.net/show_bug.cgi?id=3499916#c1
> Include Pool name in L4 Policy checksum calculation

- internal/rest/dequeue_nodes.go
- pkg/utils/types.go
Simulated client connection error(introduced 100% loss to controller IP). The key will be added to slow retry queue for any connection error. Logs:
[retry.txt](https://github.com/user-attachments/files/19429301/retry.txt)
> AV-232182: Retry on url error(client)

- internal/nodes/crd_translator.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/ingresstests/crd_test.go
- tests/ingresstests/l7_rest_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
This PR fixes the underlying issue seen in the following bugs https://vmw-jira.broadcom.net/browse/AV-232211 and https://vmw-jira.broadcom.net/browse/AV-232413.
The primary issue is that If an ingress/route does not specify a path in spec, and the corresponding hostrule has useRegex field set to true, the PG name in httppolicyset is not being encoded for the empty path in SNI mode. This leads to httppolicyset creation failure as the actual pg and pools are re-created with encoded names, but httppolicyset tries to use the old not encoded pg name.
> AV-232413 : Encode pg and pool name in SNI mode for ingress/route host with no path defined

- internal/lib/lib.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
With this change:
1. For VIPPerNS: Hostrule for shared VS has to be created with FQDNType Contains.
There are bunch of UTs not enabled for vip per ns. In future PR, we can enable those/ change as per VIP Per NS.
> AV-233670: VIP Per Namespace: Do not add auto fqdn to L7 VS

- cmd/gateway-api/main.go
AV-232009 Fix label creation on SE group by Gateway container.
Testing Status:
Manually tested for following scenario:
1) Remove existing staticroutes from vrfcontext, remove label from SE group, set disableStaticRouteSync to "true" in configmap. Reboot ako. Static routes were not populated and label was not added to SE group as expected.
2) Set disableStaticRouteSync to "false" in configmap. Reboot ako. Static routes were popoulated in controller and label was added to Service Engine Group as expected.
> AV-232009 Fix label creation on SE group by Gateway container

- ako-clean/cleanup.go
- internal/k8s/advl4_controller.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/nodes/avi_model_advl4_translator.go
- tests/advl4tests/advl4_hostname_test.go
- tests/advl4tests/informers/advl4_informer_test.go
- tests/advl4tests/setup.go
WCP Doc : https://vmw-confluence.broadcom.net/pages/viewpage.action?spaceKey=WCP&title=Log+Client+IP+-+Proxy+Protocol+-+Notes
Change:
When AKO comes up in WCP environment, it will create proxy enabled application profile in AVI. This app profile will get used when any advL4LB service gets created with certain annotation as a hint to AKO to add it as ref in VS. This application profile will be deleted using cleanup when supervisor/wcp gets disabled.
> Added support for Proxy Enabled Application Profile in WCP env

- .github/workflows/go.yml
- internal/lib/utils.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_vrf_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_vrf.go
- tests/cnitests/static_route_test.go
- tests/integrationtest/static_route_test.go
AV-232614 Static Route fixes.
This PR includes following changes:
1) Replace route ids generation with golang's UUID generation(For nodes CRUD). Modify logic for addition/updation/deletion of block affinities respectively as per new UUIDs
2) Safely Remove redundant data structures earlier needed when allocating route ids in serial order.
3) Remove all the internal data in cache corresponding to a node, when there is any error while fetching node data/ node ip, which may have lead to multiple duplicate records in the past.
4) Fixed existing UnitTestCases.
5) Removing records with duplicate route_ids(not needed)
6) Add logic to sanitize data before sending to controller to check for occurence of duplicate records.
7) Addition of new unittest cases if needed to simulate the above error.
8) …
> AV-232614 Static Route fixes

- ako-infra/avirest/netinfo_handler.go
- ako-infra/avirest/vpc_handler.go
- internal/lib/lib.go
- internal/rest/avi_obj_vsvip.go
- tests/avimockobjects/ipamdnsproviderprofile_mock.json
- tests/infratests/akoinfra_test.go
Issue : VPC with name "VPC-foo" gets used as name for AVIInfraSetting CR which is not DNS compliant. As a result, AVIInfraSetting CR won't get created.
Fix : Create hash of project name and vpc name, and use it as AVIInfraSetting CR name.
For parity, same change has been done in case of T1 based WCP environment.
> Changed AVIInfraSettingCR Name

- internal/k8s/crdcontroller.go
```
// During the portal-webapp migration from Python to Go, network views were not correctly ported. However, network APIs are now being routed through Go code,
// which is incorrect. The Avi Controller needs to be fixed.
// For now, disabling the subnet UUID validation for AWS to avoid impact on EKS deployments.
```
EKS tests have been passed after this change.
```
16:50:41 functional/ako/test_multivip.py::TestMultiVipSNI::test_create_ingress PASSED [  5%]
16:51:45 functional/ako/test_multivip.py::TestMultiVipSNI::test_update_to_multivip_ingress PASSED [ 10%]
16:53:07 functional/ako/test_multivip.py::TestMultiVipSNI::test_update_to_single_vip_ingress PASSED [ 15%]
16:53:54 functional/ako/test_multivip.py::TestMultiVipSNI::test_create_l4 PASSED  [ 20%]
16:54:20 …
```
> AV-228166 Relax subnet validation check for EKS deployments

- internal/k8s/crdcontroller.go
This is a follow-up of https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1731
> AV-228166 relax subnet uuid validation check for AKS deployments as well

- internal/k8s/crdcontroller.go
cherry-pick of https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1748, https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1731
> [release-1.13.2] Fix eks network validation check 1.13.2

- internal/cache/controller_obj_cache.go
- internal/lib/avi_api.go
AV-237682 Disable se group label updation by follower ako
Tested Locally:
**Setup:**
Multinode cluster with ako running in HA mode.
- On bootup, segroup has labels with clustername added and static routes added to vrfcontext.
- On setting **deleteConfig** flag to **true** , ako-0(Leader pod) removed the clustername label from SE group.
- On setting  **deleteConfig** flag to **false** , ako-0(Leader pod ) added the clustername label to SE group. ako-1, the follower node also tried adding the same clustername label to SE however, it failed with "HTTP code: 412; error from Controller: map[error:Concurrent Update Error" and then it have fetched and refreshed SEGroup data from controller and compared the label and since the label matched, it gave, "labels: …
> AV-237682 Disable se group label updation by follower ako

- .github/workflows/go.yml
https://github.com/actions/runner-images/issues/11101 : The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15
> AV-238793 : Update platform as ubuntu-20.04 support d

- .github/workflows/go.yml
actions/runner-images#11101 : The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15
> AV-238793 : Update platform to latest as ubuntu-20.04 support deprecated

- Dockerfile.ako-operator
This change is change is added to fix the following error occurring while publishing the image.
```
"failed": [
{
"name": "HasRequiredLabel",
"elapsed_time": 0,
"description": "Checking if the required labels (name, vendor, version, release, summary, description, maintainer) are present in the container metadata.and that they do not violate Red Hat trademark.",
"help": "Check HasRequiredLabel encountered an error. Please review the preflight.log file for more information.",
"suggestion": "Add the following labels to your Dockerfile or Containerfile: name, vendor, version, release, summary, description, maintainerand validate that they do not violate Red Hat trademark.",
"knowledgebase_url": "https://access.redhat.com/documentation/en-us/red_hat_software_certification/2024/html-single/red_h …
```
> AV-209475 : Add maintainer label to ako-operator docker image

- ako-operator/Makefile
- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
These annotations are now mandated by RedHat for certification. The previous attempt to complete the certification had failed with the below error.
```
"failed": [
[evaluate-preflight-result : evaluate-results]       {
[evaluate-preflight-result : evaluate-results]         "name": "RequiredAnnotations",
[evaluate-preflight-result : evaluate-results]         "elapsed_time": 14,
[evaluate-preflight-result : evaluate-results]         "description": "Checks that the CSV has all of the required feature annotations.",
[evaluate-preflight-result : evaluate-results]         "help": "Check that the CSV has all of the required feature annotations.",
[evaluate-preflight-result : evaluate-results]         "suggestion": "Add all of the required annotations, and make sure the value is set to either …
```
> AV-209475 : Update required feature annotations in the bundle

- ako-crd-operator/api/v1alpha1/healthmonitor_types.go
- ako-crd-operator/config/crd/bases/ako.vmware.com_healthmonitors.yaml
- ako-crd-operator/docs/samples/healthmonitor/hm-http.yaml
- ako-crd-operator/docs/samples/healthmonitor/hm-ping.yaml
- ako-crd-operator/docs/samples/healthmonitor/hm-tcp.yaml
- ako-crd-operator/helm/ako-crd-operator/chart/templates/crd/ako.vmware.com_healthmonitors.yaml
Added validations for PING and TCP HMs.
Manual tests done: 
1. Created both PING and TCP HMs
2. Updated both PING and TCP HMs.
3. Validate TCP HM creation/updation fails if tcp_half_open is set to true and other tcp fields are set.
Also fixed an issue where auth_type validation was failing when complete http object was missing in case of TCP or PING HM
> AV-239773: Add validation for PING and TCP HMs

- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- docs/crds/hostrule.md
- helm/ako/crds/ako.vmware.com_hostrules.yaml
- internal/nodes/crd_translator.go
- pkg/apis/ako/v1beta1/hostrule.go
- pkg/apis/ako/v1beta1/zz_generated.deepcopy.go
- pkg/client/v1beta1/clientset/versioned/clientset.go
- pkg/client/v1beta1/clientset/versioned/fake/clientset_generated.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/ako_client.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/aviinfrasetting.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/fake/fake_ako_client.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/fake/fake_aviinfrasetting.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/fake/fake_hostrule.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/fake/fake_httprule.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/hostrule.go
- pkg/client/v1beta1/clientset/versioned/typed/ako/v1beta1/httprule.go
- pkg/client/v1beta1/informers/externalversions/ako/v1beta1/aviinfrasetting.go
- pkg/client/v1beta1/informers/externalversions/ako/v1beta1/hostrule.go
- pkg/client/v1beta1/informers/externalversions/ako/v1beta1/httprule.go
- pkg/client/v1beta1/informers/externalversions/factory.go
- pkg/client/v1beta1/informers/externalversions/generic.go
- pkg/client/v1beta1/listers/ako/v1beta1/aviinfrasetting.go
- pkg/client/v1beta1/listers/ako/v1beta1/hostrule.go
- pkg/client/v1beta1/listers/ako/v1beta1/httprule.go
- tests/ingresstests/crd_test.go
Adds 'Duration' field to FullClientLogs under AnalyticsPolicy to allow customization of log collection duration which currently defaults to 0 (infinity).
Includes CRD changes, HostRule `AnalyticsPolicy` > 'FullClientLogs` spec change per CRD, and integration test `TestHostruleAnalyticsPolicyUpdate` change to verify default duration and hr specified duration modifications, as well as `hostrule.md` change to include duration field in sample and description of duration field under *Configure Analytics Policy*.
> AV-239969 Add FullClientLogs 'Duration' field support to hostrule crd

- ako-crd-operator/Dockerfile
- ako-crd-operator/internal/constants/constants.go
- ako-crd-operator/internal/controller/applicationprofile_controller.go
- ako-crd-operator/internal/controller/applicationprofile_controller_test.go
- ako-crd-operator/internal/controller/healthmonitor_controller.go
- ako-crd-operator/internal/controller/healthmonitor_controller_test.go
- ako-crd-operator/internal/utils/utils.go
- ako-crd-operator/internal/utils/utils_test.go
Sample object after deletion failure due to object being reffered to other objects:
```
apiVersion: ako.vmware.com/v1alpha1
kind: HealthMonitor
metadata:
creationTimestamp: "2025-06-17T09:28:34Z"
deletionGracePeriodSeconds: 0
deletionTimestamp: "2025-06-18T06:36:31Z"
finalizers:
- healthmonitor.ako.vmware.com/finalizer
generation: 4
name: example-ping-healthmonitor
namespace: default
resourceVersion: "11159506"
uid: eae8bbd9-c390-4a31-812c-f021403ef2a4
spec:
failed_checks: 4
monitor_port: 80
receive_timeout: 5
send_interval: 10
successful_checks: 2
type: HEALTH_MONITOR_PING
status:
backendObjectName: my-cluster2-default-example-ping-healthmonitor
conditions:
- lastTransitionTime: "2025-06-17T09:51:38Z"
message: HealthMonitor updated successfully on Avi Controller
reason: Updated
status: …
```
> AV-239696: Add status condition on deletion failure 

- hack/jenkins/promote_build.py
```
08:58:13    File "promote_build.py", line 1
08:58:13  SyntaxError: Non-ASCII character '\xc2' in file promote_build.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[Pipeline] }
```
> AV-245081 fix utf-8 order

- hack/jenkins/promote_build.py
```
08:58:13    File "promote_build.py", line 1
08:58:13  SyntaxError: Non-ASCII character '\xc2' in file promote_build.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[Pipeline] }
```
> AV-245081 fix utf-8

- Makefile
There is a failure seen in the build pipeline https://prodjenkins.avilb.broadcom.net/job/ako_OS-release-1.13.2-ci-build/154/console#:~:text=12%3A33%3A33-,cp%20./helm/ako/crds/*%20./ako%2Doperator/helm/ako%2Doperator/crds/,-12%3A33%3A33 as the ako-operator/helm directory itself is now removed. Hence removed the pre-build target from Makefile.
> AV-238748 : AV-238748 : Fix Makefile to remove pre-build target that is no longer required

- ako-clean/cleanup.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/nodes/avi_model_advl4_translator.go
- tests/advl4tests/advl4_hostname_test.go
- tests/integrationtest/lib.go
Jira Id: https://vmw-jira.broadcom.net/browse/VKAL-30110
This change will create a TCP HalfOpen HM at the time of AKO boot-up. If a gateway gets created (against the lb service) with the "proxy enabled" annotation then AKO will use the TCP Half Open HM for the pools associated to the VS which gets realised against the gateway. Also, this HM gets deleted when supervisor gets disabled.
> VKAL-30110: Added support for TCP Half Open Health Monitor in WCP env

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
In VKS, roles are created with granular RBAC filters and are specific to their tenant. Consequently, a user with such a role is not allowed to populate the cache for all tenants. A generic mode is being introduced to control this behavior.
Additionally, the VPC mode has been added to the gateway container's env section.
> VKAL-32019 Add dedicated tenant mode flag for VKS Clusters

- buildsettings.json
Update Kubernetes maxVersion to 1.34
This is required for VKS standard package release Oct 22
https://vmw-confluence.broadcom.net/spaces/WCP/pages/2218034077/Standard+Packages+v2025.10.22
> Update Kubernetes maxVersion to 1.34

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/nodes/gateway_model.go
- internal/lib/constants.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/utils.go
- tests/integrationtest/l4_service_test.go
This is for VCD to VCF migration use case.
VCF handling of L4 annotation will be taken separately.
> AV-247848: Add TrafficEnabled flag for ParentVS in GatewayAPI and L4 VS

- helm/ako/templates/statefulset.yaml
- tests/helmtests/statefulset_test.yaml
GatewayAPI wasn't able to read `vpcMode` env variable due to missing env read (from configmap) set in Statefulsets' template.
> AV-245746 Add vpc_mode to ako-gateway-api sts container template

- ako-crd-operator/helm/ako-crd-operator/chart/templates/manager/manager.yaml
- ako-crd-operator/helm/ako-crd-operator/chart/templates/rbac/service_account.yaml
This PR removes certain jinja2 templates defined in the chart, that try to use fields, that are not defined in values.yaml. Using undefined fields results in nil pointer exception in older helm versions while same is ignored in newer helm versions.
> AV-251077 : AKO CRD Opertaor installation fails when Helm version 3.2.1 is used
