- go.mod
- go.sum
- internal/lib/constants.go
- internal/rest/dequeue_nodes.go
- pkg/utils/avi_rest_utils.go
- vendor/github.com/avinetworks/sdk/go/session/avisession.go
- vendor/modules.txt
This commit pulls in the latest SDK changes. It also fixes an issue
with deleting virtualservices on retries.
> New SDK pull plus delete fixes

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
added ControllerIP  in configs in values.yaml. 
let me know if it's better to keep it in configs, or under any other tag
> changes in helm templates

- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- internal/rest/dequeue_nodes.go
(cherry picked from commit f87c4b87a36a1b4793c371e529943654f7bf4d5a)
> skipping retry for dummy VS for stale object deletion

- cmd/ako-main/main.go
Removed the SDK logging from AKO logs.
> Got rid of the SDK logs

- internal/rest/dequeue_nodes.go
- pkg/utils/log.go
adding timestamp to log file name 
Pass model to ExecuteRestAndPopulateCache for sni vs deletion
> multiple fixes: cherry-pick 

- internal/status/svc_status.go
This commit would not reset the LB status, if it's already reset.
> Don't reset status if it's already reset.

- internal/k8s/ako_init.go
Advanced L4 does not support DNS. Hence the full sync thread is
disabled because it's mainly used for fetching DNS info from the
controller.
> Disable full sync in advanced l4.

- CONTRIBUTING.md
- Dockerfile.ako
- helm/ako/templates/statefulset.yaml
- scripts/pre_stop_hook.sh
Changing upstream url to point to appropriate AKO Repo.
> Changing CONTRIBUTING file to point to latest AKO repo.

- internal/k8s/ako_init.go
Just disabling sync on configmap deletion and enabling sync on recreation of configmap
creates problem as there could be ongoing operations when full sync gets triggered
by configmap recreation.
Shutting down api server would trigger a deletion of the AKO pod. After the configmap is
recreated, ako pod had to be deleted (if gone to a state of crashloopbackoff).
> shutdown api server if configmap is deleted

- go.sum
- internal/k8s/ako_init.go
In advanced L4 mode, we enable full sync with a 5 min hard-coded time
interval and sync the gateway to the service status.
> Run full sync that syncs the gateway status with the service status

- internal/status/ing_status.go
- internal/status/route_status.go
patch call would make sure that update doesn't fail if the object version has changed
> use patch call to update status for ingress and route

- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/types.go
For vsvip build, we first do a get in layer3. If this fails, we should do a retry.
> adding retry for vsvip build failure

- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/types.go
- vendor/github.com/avinetworks/sdk/go/session/avisession.go
Do fast retry only for 401 error 
adding retry for vsvip build failure
> Cherry-picks: Do fast retry only for 401 error, adding retry for vsvip build failure

- helm/ako/templates/statefulset.yaml
- pkg/utils/avi_rest_utils.go
changing env var CTRL_ROOTCA to CTRL_CA_DATA
> env var name change CTRL_CA_DATA

- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- tests/multicloudtests/multi_cloud_test.go
- Changed the validation to Allow public clouds in ClusterIP mode.
- Adds GCP  cloud.
> Allowing public clouds in Cluster IP mode.

- go.mod
- helm/ako/templates/secret.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/k8s/advl4_controller.go
- internal/lib/advl4.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/dequeue_ingestion.go
- internal/status/advl4_status.go
- tests/advl4tests/advl4_hostname_test.go
gateway finalizer implementation
catch intended gateway delete via deletionTimestamp
persist VS in avi for broken gw-svc relationship if gateway is valid
> cherrypicks from release-1.3.1

- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- tests/avimockobjects/ipamdnsproviderprofiledomainlist_mock.json
- tests/bootuptests/bootupmock/ipamdnsproviderprofiledomainlist_mock.json
- tests/integrationtest/lib.go
…ing the subdomain generic wrt dns provider type.
> Cherry-pick, Changes to use ipamdnsproviderprofiledomainlist which will make fetching the subdomain generic wrt dns provider type.

- internal/status/ing_status.go
Fix for broken ingress status update from https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/commit/52ee1929389329759a62e3c047286e1ededb93f9
> fix ingress status patch calls from #150

- cmd/ako-main/main.go
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/lib/utils.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/status/ing_status.go
- pkg/utils/types.go
- pkg/utils/utils.go
Addresses: namespace wise migration changes for L7.
---
TODO: Integration test case. 
Updating helm-chart values.md.
------
Tested :
1. Valid/Invalid namespace add
2. Valid/Invalid namespace deletion
3. Valid/Invalid ingress add and deletion
Above test case with NSmigration flag enabled and disabled--> tested.
> For Ingress: Namespace wise migration changes

- tests/scaletest/configs/st_testbed.json
- tests/scaletest/lib/ingress.go
- tests/scaletest/lib/utils.go
- tests/scaletest/scale_test.go
Fetching kubeconfig file path from the testbed file
> Fetching kube config file path

- Makefile
- cmd/ako-main/main.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/lib.go
- tests/integrationtest/lib.go
- tests/namespacemigrationtests/l7_ingress_namespace_migration_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
Integration tests for Namespace wise migration feature
--- Testing---
Ran successfully:
make int_test
> Integration Test Cases for syncing k8s namespaced ingresses

- internal/cache/avi_ctrl_clients.go
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/ingress_model_rel.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/utils.go
> cherry-pick commits from release-1.3.1 to master, conflict resolution

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/status/route_status.go
Tested with insecure routes on openshift seutp
> Openshift: Enable Namespace sync for routes

- internal/status/route_status.go
- tests/oshiftroutetests/oshift_route_rest_test.go
Fixes "oc describe route routename" crash.
Added LastTransitionTime test condition to verify, time is getting published or not.
> Fix: <oc describe route routename > crash

- Makefile
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_route_namespace_sync_test.go
- tests/oshiftroutetests/oshift_route_passthrough_test.go
- tests/oshiftroutetests/oshift_route_rest_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
Openshift Unit test cases for namespace sync feature.
> UT for openshift namespace sync

- tests/advl4tests/advl4_hostname_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/l7_ingress_node_test.go
- tests/oshiftroutetests/oshift_crd_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
Please check that these tests cover all the functionalities possible as part of the Get..Name() functions in internal/lib.go
> explicit naming convention unit tests

- internal/rest/avi_obj_vs.go
Fixing the error in the VsVip creation.
`ipam_network_subnet not set in vip, no usable_networks in ipam_profile`
> Fixing the usable_network_uuids deprecation for GCP Cloud.

- helm/ako/crds/hostrule.yaml
- internal/apis/ako/v1alpha1/hostrule.go
- internal/apis/ako/v1alpha1/zz_generated.deepcopy.go
- internal/nodes/crd_translator.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
converted enableVirtualhost to *bool for nil checks
removed default functionality to  avoid PUT requests to VS
> remove enableVirtualHost default functionality via schema, check for nil

- internal/rest/avi_obj_vs.go
> Skip populating IPAMNetwork Subnet for AWS and Azure clouds as they use the cloud subnet.

- helm/ako/values.yaml
There is some confusion around the apiServerPort field. This commit
adds a comment in the values.yaml to clear the confusion.
> Update comment against the apiport

- Dockerfile.ako-operator
Required for Red Hat Certification.
> Fix labels and License for ako-operator

- Makefile
- tests/scaletest/lib/ingress.go
- tests/scaletest/scale_test.go
- Added service type LB test case
- Changed ingress group to networking.k8s.io/v1
> AV-86149 : Added service type LB test case & Changed ingress group to networking.k8s.io/v1

- Makefile
- internal/k8s/ako_init.go
- internal/lib/utils.go
- internal/nodes/dequeue_ingestion.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- Added UTs for NPL
- Fixed issues in the code caught by UTs
> Unit Tests for Node Port Local

- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/objects/npl.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- Added a new object lister SharedPodToLBSvcLister to track this
- For Pod addition this would get updated
- When a Pod is deleted services would be fetched from this lister
> Delete Servers for Service type LB when Pod is deleted

- internal/nodes/dequeue_ingestion.go
- internal/objects/ingress_to_service.go
- This fixes an intermittent issue in UT
> Fix for service-ingress mapping in NPL on ingress backend change

- pkg/utils/utils.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- deleting multiple models at the start of the tests which uses multiple Hosts
> Fix for problem in multiple UTs

- ako-operator/README.md
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
- ako-operator/config/secrets/secret.yaml
- ako-operator/controllers/configmap.go
- ako-operator/controllers/configmap_test.go
- ako-operator/controllers/statefulset_test.go
- ako-operator/controllers/suite_test.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
AKO Operator changes for 1.3.3
Includes Updates in AKOO to include the new field of values.yaml - autoFQDN
> AKO Operator changes

- internal/nodes/ingress_model_rel.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- Also added test for this use case
> Delete servers from model when Service is deleted for NPL

- internal/k8s/controller.go
- internal/lib/constants.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_crd_test.go
- tests/servicesapitests/servicesapi_l4_test.go
The fix includes pushing all mapped services in case the AviInfraSetting changes.
> UTs and fixes for annotation based AviInfraSetting usage in Service LB

- Makefile
- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/crd_translator.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_vs.go
- internal/rest/dequeue_nodes.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
- tests/integrationtest/lib.go
- Changing the model for EVH from creating multiple child EVH for each host+path combination to creating a single VS per host.
- Added L3 changes for EVH.
- Added support for host rule and http rule crd for EVH.
- Added UT for L3 changes, for graph layer changes to accommodate changed model and CRD support.
> Graph and Rest layer changes for supporting EVH in AKO.

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/utils.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/dequeue_ingestion.go
- internal/status/ing_status.go
- internal/status/route_status.go
- pkg/utils/constants.go
- pkg/utils/utils.go
This PR addresses:
1) L4 Namespace Sync: Sync L4 services from valid namespace with AVI controller. Do not address advance L4
2) Code optimization.
> L4 Namespace Sync

- Dockerfile.ako
- Dockerfile.ako-operator
- internal/lib/lib.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/ingress_model_rel.go
- internal/status/ing_status.go
- internal/status/route_status.go
- version.yaml
- included update for version in 1.4.1
> skip status deletion for Ingress if hostname is present in spec 

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
> cherry-pick, Modifying the pool name to include the service name for consistent naming in kubernetes and openshift use cases.

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
> Modifying the pool name to include the service name for consistent naming in kubernetes and openshift use cases.

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/nodes/route_ingress_model.go
- internal/objects/infrasetting.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
- tests/hostnameshardtests/crd_hostname_test.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_rest_test.go
- tests/hostnameshardtests/l7_evh_hostnameshard_test.go
- tests/hostnameshardtests/l7_hostname_rest_test.go
- tests/hostnameshardtests/l7_hostname_shard_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/servicesapitests/servicesapi_l4_test.go
* Layer7 AviInfraSetting shardSize based modelName
* add infrasetting in sslkeycertnodename
* additional UTs for infrasetting CRD
* addressing review comments
* test fix
> cherry-pick: Layer7 AviInfraSetting shardSize based modelName (#316)

- tests/hostnameshardtests/l7_hostname_shard_test.go
This fixes some problems with the existing unit test where the gomega
comparisons were not correct.
> Fixed some issues with existing unit tests.

- internal/k8s/controller.go
- internal/lib/constants.go
- internal/nodes/dequeue_ingestion.go
- internal/nodes/ingress_model_rel.go
- internal/status/status_toiler.go
- internal/status/svc_annotation.go
- tests/npltests/npl_pod_test.go
- Bug fix: Skip adding npl annotation for service type NodePort
- UT to verify this fix
- Handling annotation update through status queue
> Improvement in adding NPL annotation for services

- internal/k8s/ako_init.go
(cherry picked from commit 292ae60aefb7a8076e0e7e66dc9bde96a0266444)
> delete NPL annotation from Services when deleteConfig is set to true

- internal/cache/controller_obj_cache.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
Disable GRBAC if avi controller build is less than 20.1.5.
> Changes in rest layer to use Markers instead of Labels.

- internal/rest/rest_operation.go
> Add session timeouts into retryable errors

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_datascript.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/ssl_key_certificate.go
* sslkeycert, pkiprofile, l4policy, vsdatascript layer 3 chcksum fix
* remove irrelevant logs
* addressing review comments
* checksum conditional fix
* logfix
> cherry-pick: sslkeycert, pkiprofile, l4policy, vsdatascript layer 3 checksum without GRBAC fixes

- internal/k8s/advl4_controller.go
- internal/k8s/crdcontroller.go
- internal/k8s/services_api.go
* crash fix, check for deleted gateway type DeletedFinalStateUnknown
* DeletedFinalStateUnknown checks in AKO CRD event handlers
> cherry-pick: crash fix check for deleted object type DeletedFinalStateUnknown (#380)

- cmd/ako-main/main.go
- internal/cache/controller_obj_cache.go
Only start AKO if AVI controller state is active, else we may face DB sync issue after upgrade.
> Check AVI controller state during boot up

- internal/rest/dequeue_nodes.go
This fixes a problem where some objects could not be deleted, when deleteConfig flag was set to true.
This happens when session gets timed out, retry would fix the errors.
> skip other operations if sni child deletion fails

- internal/status/ing_status.go
- internal/status/route_status.go
Fixes a panic error - index out of range sometimes while updating route status
> Use correct index while deleting Route status

- internal/lib/lib.go
- internal/status/ing_status.go
In this time, the informers are not initialized yet.
> Use kubeclient instead of informer to fetch ingress class for status update during bootup

- cmd/ako-main/main.go
(cherry picked from commit 07d9834684fd296edc15c357ca32c2e24d595d76)
> check for vip network list after setting cloud type

- internal/lib/lib.go
(cherry picked from commit dfa1c9647091b06819c886b77da47159ec0c720c)
> fix for checking cloud type in GetVipNetworkList

- internal/nodes/avi_model_evh_nodes.go
- tests/hostnameshardtests/crd_evh_hostname_test.go
> Change the application of SSL related properties of hostrule from EVH child to parent Node.

- internal/status/ing_status.go
- internal/status/svc_status.go
- tests/hostnameshardtests/ingressclass_hostname_test.go
* prevent service status removal even if status update has errors
* test fix
* addressing review comments
> prevent service status removal even if status update has errors (#441)

- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_tls_passthrough.go
- tests/hostnameshardtests/ingress_annotation_test.go
Added a case for NPL while populating servers for passthrough.
Also fixd a bug where AKO crashes if hostname is changed in passthrough ingress.
Added a test to check the same condition.
> Supporting NPL in passthrough mode and bug fix

- helm/ako/templates/statefulset.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- pkg/utils/constants.go
- pkg/utils/utils.go
- tests/advl4tests/advl4_hostname_test.go
- tests/bootuptests/stale_obj_delete_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/ingresstests/crd_test.go
- tests/ingresstests/ingress_annotation_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/k8stest/controller_test.go
- tests/multicloudtests/multi_cloud_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_route_namespace_sync_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- tests/scaletest/scale_test.go
- tests/servicesapitests/servicesapi_l4_test.go
- tests/temp/temp_sni_to_pool_test.go
AKO would identify it's namespace based on the statefulset
through which it runs.
Fixes #449
> Support for dynamic namespaces in AKO

- internal/cache/controller_obj_cache.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/lib/avi_api.go
This also adds a few checks around executing CRD clientset calls
if the CRD is not installed on the cluster.
> adding additional logs for raw avi api queries outside rest layer

- internal/lib/lib.go
- internal/nodes/avi_model_routeingr_hostname_shard.go
- internal/status/route_status.go
- fix multihost ingress status update during bootup
- use clientset while validating ingress class during status sync
> chery-picks from release-1.4.3 bug fixes related to status syncing

- internal/status/route_status.go
Introduced in #509, the parsing method aggregated hostnames based on ingresses,
and as result attached multiple hostnames to a single VIP, which is not always
the case. This commit fixes the parsing logic to account for different VIPs
in an ingress too.
> Regression issue fix for multi host ingresses with different IPs.

- internal/status/route_status.go
Introduced in #509, the parsing method aggregated hostnames based on ingresses,
and as result attached multiple hostnames to a single VIP, which is not always
the case. This commit fixes the parsing logic to account for different VIPs
in an ingress too.
> Regression issue fix for multi host ingresses with different IPs. (cherry-pick)

- README.md
- docs/README.md
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- tests/ingresstests/ingress_annotation_test.go
- tests/ingresstests/ingressclass_test.go
Individual commit messages are self-explanatory.
> A few miscellaneous fixes and updates to docs/tests/utility functions.

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
- internal/nodes/crd_translator.go
- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
- pkg/utils/types.go
This PR handles
1. Adding Markers to avi objects
2. Removing markers from shared objects
Note: Passthrough objects are shared so it will not be marked
> Add Marker support to Avi Objects

- ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
commit description in individual commits.
> VSNode checkum updates and LB Service syncing with useServiceAPI

- ako-operator/helm/ako-operator/crds/ako.vmware.com_aviinfrasettings.yaml
- internal/cache/controller_obj_cache.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
- remove sni/passthrough/evh child node checksusm addition to VsNode
- Sync Service TypeLB into dedicated VSes eve if UseServicesAPI: true
- Add pagination support for bulk fetching vrfcontext/usable networks/SEGs
> cherry-picks to 1.5.1

- internal/lib/lib.go
> remove encoding for passthrough VS name

- internal/cache/controller_obj_cache.go
- internal/nodes/avi_model_evh_nodes.go
> Fix: EVH Passthrough VS Update Scenario and Add Cloud Name while fetching SEG

- helm/ako/templates/configmap.yaml
- helm/ako/values.yaml
- internal/cache/avi_ctrl_clients.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
> AV-121037: Enable Markers for SNI and EVH deployments for controller version >= 20.1.5

- internal/nodes/avi_model_nodes.go
We should not check if EVH is enabled for checksum calculation
fixes AV-121140
> Calculate checksum based on VS type

- internal/lib/lib.go
- internal/nodes/avi_model_tls_passthrough.go
> AV-121118: Add markers to Passthrough Pool and poolgroup

- buildsettings.json
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/ingresstests/crd_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
- tests/integrationtest/lib.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_crd_test.go
This also sets Avi maxVersion to 20.1.6 for AKO 1.5.1
> Include IngressClass/AviInfraSetting UTs for EVH

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/status/route_status.go
> EVH: Fix route transition secure to insecure issue

- internal/nodes/avi_model_evh_nodes.go
- internal/rest/avi_evh_obj.go
Add sslprofileref in Parent EVH VS. 
Porting changes to 1.5.1. Will cherrypick to master.
> Fix EVH: issue in setting up sslprofileref in EVH

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
(cherry picked from commit b469e8d37edf1d511e98aaa24b0446735ada4a06)
> changed loglevel from info to warn when default secret is not present

- internal/k8s/ako_init.go
The Namespace list is used while populating status during boot up.
Hence, updating the list after initializing Namespace Sync.
> Populate valid Namespace list during AKO boot up

- CHANGELOG.md
- buildsettings.json
- docs/README.md
- docs/ako_operator.md
- docs/ako_tenancy.md
- docs/akoconfig.md
- docs/crds/avinfrasetting.md
- docs/gateway-api/gateway-api.md
- docs/ingress/ingress.md
- docs/install/helm.md
- docs/install/operator.md
- docs/public_clouds.md
- docs/upgrade/upgrade.md
- docs/values.md
Includes documentation for:
vipNetworkList refactor. Introduced upgrade notes.
AviInfraSetting spec.network refactor
FQDN support with serviceAPIs
CHANGELOG for 1.5.1
> release-1.5.1 docs, avi-helm-chart pending changes, new feature documentation (shchauhan)

- docs/troubleshooting.md
(cherry picked from commit ba909b7c9020c1d96fab6ea0b0ae85d3ac4dfb0e)
> Troubleshooting for NPL with Antrea version < 1.2.0

- internal/lib/cni.go
- internal/status/ing_status.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- tests/servicesapitests/servicesapi_l4_test.go
> If default ingress controller is set fetch all Ingresses for status sync

- helm/ako/templates/statefulset.yaml
> remove unused .Values.imagePullSecrets from statefulset

- internal/cache/controller_obj_cache.go
Incorrect string parsing for name fixed.
> Fix for marker based network name, additional logs

- ako-operator/helm/ako-operator/templates/secret.yaml
- ako-operator/helm/ako-operator/values.yaml
- docs/ako_operator.md
- docs/install/helm.md
- docs/install/operator.md
- helm/ako/values.yaml
Added missing "authtoken" field in
1. values.yaml
2. AKO operator files
> Fix: Added missed 'authtoken' field

- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
- ako-operator/controllers/configmap.go
- ako-operator/controllers/configmap_test.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/validator.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/evhtests/l7_evh_rest_test.go
- Also introduced a new flag vipPerNamespace so that this feature can be used outside a VCF cluster
> helm changes for VCF cluster and VIP per Namespace

- ako-infra/ingestion/controller.go
- ako-infra/ingestion/vcf_controller.go
- cmd/ako-main/main.go
- cmd/infra-main/main.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/dynamic_client.go
- internal/lib/lib.go
Introducing ako-infra which would be used to create a new container.
Handling NCP Boostrap CRD is moved to AKO-Infra.
> Add AKO-Infra and reorganise files

- internal/nodes/avi_model_l7_translator.go
A simple one liner change to use informers instead of clients for secret data.
> Added a change to convert the secret from clientset to informer

- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/k8s_utils.go
- internal/status/advl4_status.go
- internal/status/ing_status.go
- internal/status/route_status.go
- internal/status/svc_status.go
- internal/status/svcapi_status.go
- tests/advl4tests/advl4_hostname_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_rest_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/oshift_route_rest_test.go
- tests/servicesapitests/servicesapi_l4_test.go
Status update for Ingress and Service Type LB is updated
following cases are tested.
VIP <-> MultiVip
VIP <-> Public IP
VIP -> (MultiVIP <-> Public) -> VIP
UTs added
> Multivip status update

- ako-operator/Makefile
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/values.yaml
This PR includes : 
1. Cherry-pick of commit in #656
2. Akoconfig and values.yaml changes for AKO Operator 1.5.2
> AKO Operator - CRD version upgrade, akoconfig and values.yaml changes

- ako-operator/helm/ako-operator/crds/ako.vmware.com_hostrules.yaml
- helm/ako/crds/ako.vmware.com_hostrules.yaml
This PR fixes hostrule CRD file merge issue.
> Fixes hostrule CRD file merge issue

- docs/crds/hostrule.md
This PR adds the  Hostrule CRD document changes for Analytics Policy code changes.
> Doc: Hostrule CRD document changes for Analytics Policy

- tests/scaletest/lib/ingress.go
- tests/scaletest/scale_test.go
Testcase for checking create, update and deletion of different type of ingress in a reboot during scale test.
> Adds testcase to scale test code

- internal/k8s/ako_init.go
This PR reverts the code to skip the shared empty parent VS deletion.
> Reverts the code to skip the shared empty parent VS deletion

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
Add SEG to dedicated VS. Remove FQDN in case of wrong certificate.
> Add SEG to dedicated VS. Remove FQDN in case of wrong certificate

- CHANGELOG.md
This PR for mentioning change log for AKO 1.6.1
@sudswasavi @monotosh-avi @chauhanshubham @swathinsankaran @aaha97 : Please review the changes.
> Chagelog for 1.6.1

- docs/install/helm.md
- docs/upgrade/upgrade.md
This PR modify existing helm upgrade doc to make it work on 1.6.1
> AKO 1.6.1- changes in helm upgrade process

- CHANGELOG.md
- docs/faq.md
This PR addresses the document changes for `retain VS VIP over AKO reboot`.
> Doc: FAQ changes for `retain VS VIP over AKO reboot`

- internal/nodes/avi_model_tls_passthrough.go
Without this change passthrough VSVip creation fails in nsxt environment.
fixes AV-135928
> set T1 LR in the VSVip of Passthrough VS

- docs/faq.md
(cherry picked from commit 026544510d6544736bf63ca4ff78d3e8b549ed16)
> Doc update for AKO statefulset annotation change  cherry-pick to master

- internal/cache/avi_ctrl_clients.go
- internal/lib/avi_api.go
- internal/lib/lib.go
> Add tenant and api version for fetching authtoken

- Makefile
- helm/ako/crds/ako.vmware.com_clustersets.yaml
- helm/ako/crds/ako.vmware.com_multiclusteringresses.yaml
- helm/ako/templates/clusterrole.yaml
- internal/k8s/crdcontroller.go
- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/validator.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/status/crd_status.go
- internal/status/multicluster_ing_status.go
- internal/status/status_toiler.go
- pkg/apis/ako/v1alpha1/mci.go
- tests/integrationtest/lib.go
- tests/k8stest/controller_test.go
- tests/multiclusteringresstests/multicluster_ingress_graph_test.go
- tests/multiclusteringresstests/multicluster_ingress_rest_test.go
1. Rest layer changes to identify multi-cluster ingress VSes
2. Status layer changes to update annotations and status
3. Ingestion, Graph and rest layer UTs
> [MCI] Rest and status layer changes

- internal/nodes/avi_model_l4_translator.go
> Donot program fqdn for L4 via external dns when autoFQDN is disabled

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_nodes.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
1. Fixes the issue of FQDN aliases not getting added to all the HTTP policies
2. Optimizes the way the FQDN aliases are added to HTTP policies
> FQDN aliases bug fix and optimizations

- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_nodes.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
FQDN aliases bug fix and optimizations
> Cherry-pick of FQDN aliases bug fix to 1.6.3

- CHANGELOG.md
Documentation
As we do not have release 1.6.3 on harbor, adding items from 1.6.3 to 1.6.4
> Documentation: Release notes for 1.6.4

- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/dequeue_nodes.go
- internal/rest/ssl_key_certificate.go
As part of PR changes, in EVH deployment, AKO processes next EVH child if current child does not fail with error
1. Error status code is between 500 to 599
2. Error status code is 408 which indicates there is an issue with controller session timeout
3. Error status code is 400 with error `no free IP available`
4. Error status code is 403 with error `configuration not allowed during controller upgrade`
5. Error status code is 401 with invalid credential error
> Unblock next EVH child if current EVH child fails with error that does not impact next child

- docs/crds/hostrule.md
- docs/crds/httprule.md
This commit adds documentation for
specifying kubernetes secret in hostrule to configure sslKeyCertificate
specify pkiProfile for reencrypt in httprule
> Add documentation for new httprule and hostrule fields

- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/lib.go
- internal/objects/nodes.go
- tests/integrationtest/l4_nodeport_service_test.go
> NodePort Optimization: Filter out nodes based on nodeLabelSelector present in values.yaml

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/rest/avi_obj_pool.go
This fixes the VLAN segment support with NSX-T cloud.
> AV-138208 Allow NodeNetwork list for pool placement network on NSX-T cloud

- internal/status/ing_status.go
- internal/status/route_status.go
Fixes slice bounds out of range error while deleting ingress statuses.
Fixes AV-143532
> Fix pod panic while deleting ingress statuses

- internal/k8s/ako_init.go
This commit takes care of the ingress class processing during fullsync.
> [Fix] Ingress class processing in fullsync

- CHANGELOG.md
- buildsettings.json
- docs/install/helm.md
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/dequeue_nodes.go
- internal/rest/ssl_key_certificate.go
1. Process next EVH child if current child does not fail with 
-     Error status code is between 500 to 599
-     Error status code is 408 which indicates there is an issue with controller session timeout
-     Error status code is 400 with error no free IP available
-     Error status code is 403 with error configuration not allowed during controller upgrade
-     Error status code is 401 with invalid credential error
2. Added doc changes for 1.5.4
> Evh active network release 1.5.4

- internal/nodes/ingress_model_rel.go
This PR fixes an issue where the AKO was not retrieving the routes correctly
for an empty path in the route configuration.
> [fix] AKO not honoring httprule updates in Openshift

- internal/rest/avi_obj_pool.go
This PR sets the external uuid field of pool servers to ip:port
> AV-140317 Added ExternalUUID field in Pool servers

- Dockerfile.ako-operator
- buildsettings.json
- docs/install/helm.md
- docs/install/operator.md
- version.yaml
> Update version in master to 1.8.1

- internal/rest/avi_obj_vsvip.go
fixed incorrect compare for vips and fips
> Fix status update

- internal/cache/avi_ctrl_clients.go
- internal/lib/avi_api.go
- internal/lib/lib.go
- pkg/utils/avi_obj_cache.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/constants.go
pkg util changes for CTRL_CA_DATA
> Donot use CTRL_CA_DATA from environment variables

- ako-operator/Makefile
- ako-operator/README.md
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
Please note: AKO-Operator currently do not support helm install. Still changes has been added considering future alternative option.
> AKO-Operator 1.7.1: Adding fields to AKO Config CRD

- CHANGELOG.md
This PR contains the updated release notes of AKO release 1.5.5.
> Release notes for 1.5.5

- CHANGELOG.md
- Dockerfile.ako-operator
- docs/README.md
- docs/install/helm.md
This Pr deals with
1. Update to helm doc as per AKO 1.7.2
2.  Update to changeLog.
> Doc changes for AKO 1.7.2

- CHANGELOG.md
This PR adds a known issue to the changelogs of the 1.7.2 release.
> Documentation update for 1.7.2 release

- README.md
Reverts vmware/load-balancer-and-ingress-services-for-kubernetes#900
> AV-150130 Revert "Revert "Update README.md""

- ako-operator/helm/ako-operator/crds/ako.vmware.com_httprules.yaml
- helm/ako/crds/ako.vmware.com_httprules.yaml
- internal/k8s/crdcontroller.go
- internal/lib/constants.go
> [Cherry-pick]: Fix HttpRule: Remove mandatory check for DestCA and PkiProfile (#888)

- README.md
Reverts vmware/load-balancer-and-ingress-services-for-kubernetes#902
> Revert "AV-150130"

- NOTICE.txt
Reverts vmware/load-balancer-and-ingress-services-for-kubernetes#918
> Revert "Update NOTICE.txt"

- docs/multiple-ako.md
Cherry-pick from 1.7.1 to master
* Doc: Multiple AKO support
* Review comments addressed
> [Cherry-pick] Doc from 1.7.1 to master: Multiple AKO support (#857)

- docs/ingress/ingress.md
- docs/openshift/openshift.md
- docs/public_clouds.md
Cherry-pick from 1.7.1 to master.
> openstack support, alternate default certificate

- CHANGELOG.md
- docs/README.md
- docs/install/helm.md
- docs/values.md
Readme is changed as per 1.8.1 requirement.
> [Cherry-pick] Release-1.7.1: Helm updates, compatability matrix update, update to values.yaml, changelog addition

- cmd/ako-main/main.go
- go.mod
- helm/ako/templates/clusterrole.yaml
- helm/ako/templates/configmap.yaml
- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_pool.go
- internal/rest/dequeue_nodes.go
- vendor/modules.txt
1. statefulset updated to add annotations for certificates.
2. file watcher for certificate updates.
3. secret informer for certificates exported as k8s secret
4. pki profile and sslkey cert update using root CA and workload certifcate
5. pool update after certificate rotation
> Istio mTLS support

- docs/crds/avinfrasetting.md
- docs/ingress/ingress.md
- docs/openshift/objects.md
- docs/shared_vip.md
This PR contains doc changes
1. For aviinfrasetting support in passthrough VS
2. For shared vip
> Doc: Aviinfrasetting support in Passthrough VS

- Makefile
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/evhtests/l7_evh_rest_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
- tests/multicloudtests/multi_cloud_test.go
> Fix for UT failures

- helm/ako/templates/statefulset.yaml
This PR fixes one issue with the statefulset yaml present in the helm.
> Fix for statefulset yaml issue

- helm/ako/values.yaml
This PR fixes an issue with values.yaml.
> Fixes the issue with values.yaml

- internal/rest/dequeue_nodes.go
This PR adds the code to clear the cache when a partial delete happens. During partial delete, the cache is not cleared properly and the AKO does PUT calls to the controller instead of POST calls.
> [AV-154259] fix to clear cache during partial delete

- internal/rest/dequeue_nodes.go
This PR adds the code to clear the cache when a partial delete happens. During partial delete, the cache is not cleared properly and the AKO does PUT calls to the controller instead of POST calls.
> [cherry-pick to release 1.8.1]fix to clear cache during partial delete

- helm/ako/templates/statefulset.yaml
- helm/ako/values.yaml
This PR cherry-picks the fixes raised in release-1.8.1 which are related to helm charts.
> Fix for helm chart issues

- CHANGELOG.md
- docs/install/helm.md
This PR cherry-picks the release-1.7.2 documentation to the release-1.8.1 branch.
> Cherry-pick of release-1.7.2 documentation to release-1.8.1 

- CHANGELOG.md
- docs/README.md
This PR contains the changelogs for the 1.8.1 release as well as the controller version max version to 22.1.1.
> Added changelogs for 1.8.1 release

- CHANGELOG.md
- docs/install/helm.md
This PR cherry-picks the document changes in release-1.7.2 to master.
> Cherry-pick of release-1.7.2 documentation to master 

- internal/k8s/crdcontroller.go
> AV-158136: Validate enableSSL on listener Port only when listener settings are configured

- CHANGELOG.md
This PR contains the cherry-pick of changelogs for release-1.8.1.
> Cherry-pick of changelogs for release-1.8.1

- CHANGELOG.md
This PR adds a known issue to the changelogs of release 1.7.1.
> Adds a known issue to release-1.7.1 changelogs

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/rest/avi_obj_pool.go
nodenetworklist check mandatory for nsx-t vlan and vcenter cloud
update pool placement network for nsx-t vlan and vcenter cloud only
update vip placement network for nsx-t vlan
> AV-156959 Nodenetwork list mandatory fix for nsx-t vlan

- cmd/ako-main/main.go
- internal/k8s/ako_init.go
- internal/k8s/controller.go
- internal/k8s/crdcontroller.go
- internal/k8s/leader_election_callbacks.go
- internal/k8s/validator.go
- internal/lib/control_config.go
- pkg/utils/constants.go
- pkg/utils/leader_election.go
- tests/advl4tests/advl4_hostname_test.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
- tests/ingresstests/l7_graph_test.go
- tests/integrationtest/l4_nodeport_service_test.go
- tests/integrationtest/l4_service_test.go
- tests/multiclusteringresstests/multicluster_ingress_graph_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/servicesapitests/servicesapi_l4_test.go
This PR includes the following changes:
1. Leader election bootstrap code.
2. Ingestion layer changes for leader election.
3. Skips the validation of CRDs in passive AKO during ingestion of CRD objects.
4. UT fixes
> [HA] Ingestion Layer code changes

- internal/lib/constants.go
- internal/nodes/avi_model_tls_passthrough.go
Manual Testing done as follow:
1. create passthrough VS without infrasetting
2. Create passthrough VS with infrasetting
3. Transition passthrough VS with to without infrasetting and vice versa.
4. Traffic test
TODO: Run FT suits.
> AV-159292: Fix for Error datascript for passthrough VS

- internal/cache/cache_utils.go
- internal/cache/controller_obj_cache.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
This PR adds code to update IPv6 IPs to status of ingress.
the priority for status ip is as follows 
public ip > ipv6 ip > ipv4 ip
> AV-157761 Status update for IPv6 AKO

- internal/rest/avi_obj_vs.go
This PR contains the code changes to copy the parent reference while adding the child VS cache object to the cache.
In the rest layer in order to populate the IP address for the status of Ingress/Routes, we either traverse through the VS VIP key collections present in the VS cache or traverse through the parent VS's VSVIP Collection and fetch the IP Addresses mapped to it.
But for a child VS the latter will be the approach taken to figure out the IP address. But when the child VS is newly added for the first time, the parent reference is not added properly, which resulted in an empty IP address getting populated for it.
TODO: FT runs
> [AV-150821] fix for status IPs not getting updated properly for some Ingresses/Routes

- cmd/ako-main/main.go
- docs/crds/avinfrasetting.md
- docs/install/helm.md
- docs/istio_support.md
- docs/values.md
- internal/lib/lib.go
- internal/nodes/avi_model_l7_translator.go
- internal/rest/avi_obj_vsvip.go
AV-159603 secure ingress with Istio fix #993
AV-160069 Fix error logs with istio on AKO bootup #992
AV-156960 Add vip placement from vip network for nsxt vlan #991
Docs for Istio and IPv6 support #942
> Cherrypicks from multiple PRs

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
add alternate cert to avi controller with a different name than regular cert
> AV-162992 add alternate cert to avi controller with a different name

- internal/cache/controller_obj_cache.go
- internal/rest/dequeue_nodes.go
istio resources should now get cleaned up as per regular workflow if istioenabled is set to false or deleteconfig is set to true
> AV-160076 Cleanup istio resources after istio is disabled

- Makefile
- tests/avimockobjects/l4policyset_mock.json
- tests/avimockobjects/l4policyset_uuid_mock.json
- tests/avimockobjects/virtualservice_mock.json
- tests/hatests/follower_crd_test.go
- tests/hatests/follower_l4_test.go
- tests/hatests/follower_l7_test.go
- tests/hatests/follower_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/lib.go
- tests/integrationtest/lib.go
- tests/oshiftroutetests/lib.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
This PR contains the UTs to test the AKO follower code. It verifies the cache created at the follower AKO and also verifies whether the follower AKO does any operations other than GET.
> [HA] UTs to test AKO HA

- docs/values.md
- helm/ako/values.yaml
Add instructions for authtoken encoding
Fix wording for IPv6 docs
> Doc updates for Authtoken and IPv6

- internal/rest/avi_obj_vsvip.go
- internal/rest/k8s_utils.go
This PR fixes the following two issues : https://avinetworks.atlassian.net/browse/AV-166395 and https://avinetworks.atlassian.net/browse/AV-166398. The test results are attached.
[svcapi.txt](https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/files/10382849/svcapi.txt)
> AV-166395 & AV-166398 : AKO FT fixes

- docs/faq.md
- docs/sctp.md
This PR includes documentation for SCTP protocol support with AKO.
> AV-166503 : Documentation for SCTP protocol support with AKO

- Dockerfile.ako
- docs/troubleshooting/troubleshooting.md
- docs/values.md
- helm/ako/values.yaml
This PR adds the documentation for `securityContext`.
> [Doc] [AV-164899] Documentation for `securityContext`

- docs/roles/ako-essential.json
Updated PERMISSION_SYSTEMCONFIGURATION in ako-essential.json to READ_ACCESS
> Updating SystemConfig permission for ako-essential role

- internal/k8s/ako_init.go
- internal/rest/dequeue_nodes.go
Istio Bootstrap needs to execute after leader election.
need to use key instead of model name (name is empty in model) for certificate rotation flow
> Fix Istio resource creation

- ako-operator/README.md
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
- ako-operator/controllers/role.go
- ako-operator/controllers/statefulset.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- docs/ako_operator.md
- docs/akoconfig.md
- docs/install/operator.md
This PR includes changes for creating the AKO Operator release version 1.9.1, and certifying it through the RH portal.
> AV-169470 : AKO Operator 1.9.1 Release and RH Certification

- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/clusterrole.yaml
- ako-operator/bundle/metadata/annotations.yaml
This PR includes bundle changes for AKO Operator 1.9.1 Release and RH Certification
> AV-169470 : Bundle changes for AKO Operator 1.9.1 Release

- internal/rest/rest_operation.go
> AV-169804: Fix: Static routes are not getting deleted from controller when deleteConfig is set to true

- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
Updating akoconfig crd in bundle which was missed earlier
> AV-169470 : Updating akoconfig crd in bundle

- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
Updating spec descriptor for replicaCount field which was missed earlier
> AV-169470 : Updating spec descriptor for replicaCount field

- internal/lib/constants.go
- internal/lib/lib.go
- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/dequeue_ingestion.go
This reverts commit 0755b8363cc05d8d928dd5cdfa206e911c0d8a6b.
Reverting L4-Annotation commit for app-profile as this was beta feature.
> Revert "L4 app release 1.9.1 (#1057)"

- internal/nodes/avi_vrf_translator.go
- tests/integrationtest/static_route_test.go
We are fixing two issues as part of one bug id.
This PR fixes one issue as follow.
Issue: When AKO is running, AKO VRF cache is build. If multiple node update occurs, route-id for each route was getting populated same. Due to this PATCH to vrfcontext was failing due to duplicate route-id.
Resolution: When update to existing node come, use existing route-id present in cache.
This PR fixes this issue.
> AV-171818: Fix vrf cache issue in update node case

- internal/nodes/avi_vrf_translator.go
- tests/integrationtest/static_route_test.go
cherry-pick from master branch.
> AV-171818: Fix vrf cache issue in update node case (#1073)

- internal/rest/rest_operation.go
Porting changes to 1.9.2 from master
> AV-169804: Fix: Static routes are not getting deleted from controller when deleteConfig is set to true (#1058)

- buildsettings.json
- version.yaml
This PR updates the version in `version.yaml` to 1.9.3.
> Release version to 1.9.3

- internal/status/crd_status.go
This PR includes the status layer changes for L4 CRD.
> [L4 CRD] status layer changes for L4 CRD

- docs/README.md
- docs/ako_ha.md
- docs/install/helm.md
- docs/ipv6-support.md
This PR contains the version changes from 1.9.2 to 1.9.3 in the doc files.
> [Doc] Version change for 1.9.3

- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
This PR contains the rest layer code changes for L4 CRD.
> [L4 CRD] Rest layer Changes 

- helm/ako/crds/ako.vmware.com_l4rules.yaml
- internal/k8s/validator.go
This PR contains the following fixes: 
1. Corrects the CRD definition
2. Resolves an issue with Application persistence profile validation.
> [L4 CRD] Bug fixes

- internal/rest/avi_obj_vrf.go
> AV-172884:Resolve clustername overlap issue while creating static route for cluster (#1108)

- docs/install/helm.md
- docs/install/operator.md
- docs/openshift/openshift.md
- docs/values.md
- helm/ako/values.yaml
- internal/lib/constants.go
- internal/lib/dynamic_client.go
- tests/integrationtest/lib.go
- tests/integrationtest/static_route_test.go
This PR is for adding support for OVN-Kubernetes CNI in Openshift with AKO.
> AV-177986 : Support for OVN-Kubernetes CNI in Openshift with AKO

- Dockerfile.ako-operator
- ako-operator/README.md
- ako-operator/api/v1alpha1/akoconfig_types.go
- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
- ako-operator/bundle/manifests/clusterrole.yaml
- ako-operator/bundle/metadata/annotations.yaml
- ako-operator/config/crd/bases/ako.vmware.com_akoconfigs.yaml
- ako-operator/config/samples/ako_v1alpha1_akoconfig.yaml
- ako-operator/controllers/configmap.go
- ako-operator/controllers/configmap_test.go
- ako-operator/controllers/role.go
- ako-operator/controllers/statefulset.go
- ako-operator/controllers/statefulset_test.go
- ako-operator/controllers/suite_test.go
- ako-operator/controllers/utils.go
- ako-operator/helm/ako-operator/crds/ako.vmware.com_akoconfigs.yaml
- ako-operator/helm/ako-operator/templates/ako-operator-manager-role.yaml
- ako-operator/helm/ako-operator/templates/akoconfig.yaml
- ako-operator/helm/ako-operator/values.yaml
- docs/ako_operator.md
- docs/akoconfig.md
- docs/install/operator.md
This PR includes changes in ako-operator for Openshift marketplace release version 1.9.3.
> AV-178871 : AKO Operator 1.9.3 Release and RH Certification

- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
This PR includes changes for ako-operator 1.9.3 bundle.
> AV-178871 : AKO Operator 1.9.3 bundle changes

- docs/crds/l4rule.md
- docs/shared_vip.md
This PR contains the document changes for L4Rule CRD.
> AV-134285 : Documentation for L4Rule CRD

- docs/crds/ssorule.md
This PR includes documentation for SSORule CRD.
> AV-152365 : Documentation for SSORule CRD

- internal/status/route_status.go
> AV-179484: Fixes the issue of no status when insecure Edge Termination Policy set as Allow

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_nodes.go
- internal/rest/avi_obj_vs.go
- tests/dedicatedevhtests/l7_evh_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/hatests/follower_l4_test.go
- tests/ingresstests/l7_graph_test.go
- tests/ingresstests/l7_nodeport_test.go
- tests/ingresstests/lib.go
- tests/integrationtest/l4_crd_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/multiclusteringresstests/multicluster_ingress_graph_test.go
- tests/namespacesynctests/l7_ingress_namespace_sync_test.go
- tests/npltests/npl_pod_test.go
- tests/oshiftroutetests/lib.go
- tests/oshiftroutetests/oshift_l4_l7_nodeport_test.go
- tests/oshiftroutetests/oshift_route_model_test.go
- tests/oshiftroutetests/oshift_route_namespace_sync_test.go
- tests/oshiftroutetests/oshift_route_passthrough_test.go
- tests/oshiftroutetests/oshift_route_rest_test.go
- tests/oshiftroutetests/oshift_secure_route_test.go
- tests/temp/temp_sni_to_pool_test.go
In UTs, parameter protocol is added while creating service. That resulted in changes in multiple files.
> AV-180342: Fix: shared vip service support for mix protocols. Mix protocol support was not working when SCTP protocol is specified with either UDP/TCP

- CHANGELOG.md
- buildsettings.json
- docs/README.md
This PR adds the changelogs for the 1.10.1 release and also updates the compatibility matrix.
> Changelogs and compatibility matrix for release 1.10.1

- internal/k8s/ako_init.go
> AV-180047: fix: AKO Bootup time is 36 min with 193 Nodes and 9k ingresses and 4k pods (#1161)

- docs/cilium.md
* AV-169294 : Documentation for Cilium CNI support with AKO
* AV-169294 : Adding SCTP conditions to Cilium Documentation
> AV-169294 : Documentation for Cilium CNI support with AKO (#1162)

- docs/crds/ssorule.md
* AV-152365 : Documentation for SSORule CRD
* AV-152365 : Fixes for review comments
* AV-152365 : Adding condition for SSORule may get rejected on Openshift if useDefaultSecretsOnly is true
---------
> AV-152365 : Documentation for SSORule CRD (#1153)

- docs/crds/avinfrasetting.md
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
> doc for HTTP2 flow in FE + change to keep union of hostrule and aviinfra listeners

- CHANGELOG.md
- buildsettings.json
- docs/README.md
> [Cherry-pick]Changelogs and compatibility matrix for release 1.10.1

- .github/workflows/go.yml
This PR updates the Ubuntu version from `18.04` to `20.04` in go.yml.
> Updates the Ubuntu version to 20.04 in go.yml

- tests/evhtests/l7_evh_ingressclass_test.go
- tests/ingresstests/l7_rest_test.go
- tests/integrationtest/lib.go
This PR cherry-picks PRs #1060 and #1131 which contain the UT fixes to the release-1.7.4
> Cherry-picks UT fixes to release-1.7.4

- buildsettings.json
- docs/README.md
- docs/install/helm.md
- version.yaml
This PR changes the version to 1.7.4 in all documents.
> Doc changes for release-1.7.4 

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/evhtests/l7_evh_ingressclass_test.go
- tests/ingresstests/ingressclass_test.go
- tests/ingresstests/l7_graph_test.go
This PR cherry-picks the #1175 PR.
> AV-179162: No Autogenerated domain for Dedicated Shard VS when AutoFQDN is flat or default

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
- cmd/gateway-api/main.go
- helm/ako/templates/statefulset.yaml
This PR includes
1. graph layer changes (Build VS, VsVip, TLSNodes)
2. Object store changes (gateway <-> gatewayClass)
3. Adding more validation
> AV-183086 Graph Layer changes for Gateway API

- ako-gateway-api/k8s/gateway_controller.go
This PR adds the event handlers for the HTTPRoute object.
UTs: Will be added in the next PR.
> AV-183085: [GatewayAPI]Event handlers for HTTP Route object

- internal/cache/controller_obj_cache.go
Tested:
1. Both networks have configured networks, make sure AKO picks up the right one based on CIDR configured in AKO. (For both VIP) (Configmap level and aviinfrasetting level). 
--> For pool, this testing is not done as AKO does not implement cidr overlapping logic for pools.
2. No CIDR configured, make sure AKO picks up the right network based on common hosts (For both vip and pool) (Configmap level and aviinfra level)
> Fix: Fixed logic for finding overlap IPaddress. Added debug logs

- ako-gateway-api/tests/graphlayer/gateway_test.go
- ako-gateway-api/tests/graphlayer/gatewayclass_test.go
Positive case
Create Gateway (TLS/noTLS)
Transition Gateway (TLS <-> noTLS)
Delete Gateway
> AV-183082 Add Graph Layer UTs

- ako-gateway-api/nodes/avi_model_l4_translator.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/objects/gateway_store.go
- internal/nodes/avi_model_evh_nodes.go
This pull request contains the initial commit for creating the child VS.
> AV-183086: [GatewayAPI] Initial commit of child VS creation code

- internal/nodes/crd_translator.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
- tests/oshiftroutetests/oshift_crd_test.go
This pull request includes a solution for a problem encountered when processing an HTTPRule with an empty LB algorithm and unit tests to verify the modifications.
> AV-184601: Fix for HTTPRule with empty LBAlgorithm

- buildsettings.json
- docs/ako_ha.md
- docs/install/helm.md
- helm/ako/crds/ako.vmware.com_aviinfrasettings.yaml
- helm/ako/values.yaml
- internal/cache/controller_obj_cache.go
- internal/k8s/ako_init.go
- internal/k8s/crdcontroller.go
- internal/k8s/validator.go
- internal/lib/lib.go
- internal/rest/avi_obj_vsvip.go
- vendor/modules.txt
This PR works on following two issues:
1. [Introducing networkUUID parameter in values.yaml and aviinfrasetting]
2. [Using SEG mgmt network for finding out host overlap]
3. Also update AKO version to 1.10.3
TODO: UT (Working on it)
TODO: FT
> Using SEG mgmt network for finding out host overlap

- buildsettings.json
- docs/README.md
- docs/install/helm.md
- version.yaml
This Pr updates the version in version.yaml and all other documents to 1.7.5.
> Updates the version to 1.7.5

- internal/k8s/crdcontroller.go
> Fix: Use mgmt network from confimap SE group if aviinfrasetting SEG is not present

- docs/crds/l4rule.md
- docs/gateway-api/gateway-api.md
- docs/objects.md
1. Corrects one typo in the L4Rule document.
2. Corrects one typo in the GatewayAPI and Objects.md document.
> Doc corrections

- internal/k8s/crdcontroller.go
- internal/k8s/validator.go
>  Fix: Use mgmt network from confimap SE group if aviinfrasetting SEG is not present

- docs/install/helm.md
- docs/openshift/openshift_helm.md
This PR cherry-picks #1242 to 1.7.5 release.
> Helm based installation changes for release-1.7.5

- CHANGELOG.md
> Changelogs for release-1.7.5

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/status/status.go
- internal/nodes/avi_model_evh_nodes.go
- internal/rest/avi_evh_obj.go
- pkg/utils/constants.go
1. Fixes a few bugs present in the Gateway API code.
2. Default PG addition to child VS.
3. Fixes a few issues with the host addition to VSVIP.
4. Fixes the log formatting.
> [Gateway API] Bug fixes

- Makefile
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/status/gateway_status.go
- ako-gateway-api/status/gatewayclass_status.go
- ako-gateway-api/status/httproute_status.go
- ako-gateway-api/status/status.go
- ako-gateway-api/tests/graphlayer/httproute_test.go
- ako-gateway-api/tests/ingestion/gateway_test.go
- ako-gateway-api/tests/utils.go
1. Adds target to run the Gateway APIs UTs
2. Fixes the UT issues and a few lint issues
> [Gateway API] fixes lint issues

- ako-gateway-api/objects/nodes.go
- ako-gateway-api/rest/dequeue_nodes.go
- ako-gateway-api/retry/dequeue_retry.go
This PR removes the unused files from the code base of GatewayAPI.
> [GatewayAPI] Removes the unused files

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/tests/graphlayer/gatewayclass_test.go
save gateway list before deleting the mapping
poolnode network placement setting code bug fix
> [BUG FIX]  Fix fetching gateway for gateway class

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/objects/gateway_store.go
This PR
1. Adds secret handling
2. fixes store update after gateway deletion
3. add TODOs
> [GatewayAPI] Secret Handling and bug fixes

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/lib/lib.go
fix seg fault due to informer intialization not being removed
> [GatewayAPI] Code cleanup 

- docs/gateway-api/gateway-api-v1alpha1.md
- docs/gateway-api/gateway-api-v1beta1.md
This PR contains the documentation for the Gateway API implementation.
> Documentation for Gateway API implementation

- cmd/ako-main/main.go
- internal/lib/lib.go
> Reboot AKO when there is error in retrieving out Openshift clientset or informer in Openshift environment

- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- tests/gatewayapitests/graphlayer/gateway_test.go
> AV-188865 Secret Handling Fix

- docs/crds/l4rule.md
- docs/shared_vip.md
The PR is to update the L4Rule CRD documentation to include the details about newly added SSL support for L4 VS.
> AV-188667 : Documentation for L4 SSL support with L4Rule CRD

- internal/rest/avi_obj_vsvip.go
Old vsvip cache should be fetched before updating the cache
> Fix status update not getting triggered

- ako-gateway-api/k8s/validator.go
- ako-gateway-api/status/gateway_status.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
Add UTs for ingestion layer coverage
> [Gateway API] Add ingestion layer UTs

- ako-operator/bundle.Dockerfile
- ako-operator/bundle/manifests/ako-operator.clusterserviceversion.yaml
- ako-operator/bundle/manifests/ako.vmware.com_akoconfigs.yaml
- ako-operator/bundle/manifests/clusterrole.yaml
- ako-operator/bundle/metadata/annotations.yaml
This PR adds bundle changes for AKO Operator 1.11.1 release.
> AV-191380 : Bundle changes for AKO Operator 1.11.1 Release

- internal/nodes/avi_vrf_translator.go
- tests/cnitests/static_route_test.go
AV-190960 Static Route Creation Fix
> AV-190960 Static Route Creation Fix

- CHANGELOG.md
- docs/README.md
- docs/akoconfig.md
- docs/install/helm.md
- helm/ako/values.yaml
Not done changes for AKO operator fields.
> AV-194029: Change description of nsx-T parameter in values.yaml

- ako-infra/avirest/handle_netinfo.go
- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/nodes/avi_vrf_translator.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- pkg/utils/utils.go
- tests/ingresstests/l7_graph_test.go
- tests/integrationtest/lib.go
This PR includes:
- update node IPv4 and IPv6 static IPs 
- prioritize IPs from annotation for calico and antrea cni
- read IPFamily from Service and populate servers
- update both IPv4 and IPv6 IPs when present, and overwrite with public IP if present
> AV-195873 AV-195878 Backend support for dualstack and status update

- ako-infra/avirest/handle_netinfo.go
- buildsettings.json
- internal/lib/lib.go
- internal/nodes/avi_model_l4_translator.go
- internal/rest/avi_obj_pool.go
- pkg/utils/utils.go
This PR includes:
1. K8 1.29 support
2. Regression fix for pool placement network.
> AV-198256: Fix pool placement network related issue. Support for K8 1.29

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/gateway_controller.go
- cmd/gateway-api/main.go
- internal/k8s/ako_init.go
- internal/status/statefulset_status.go
- internal/status/status_publisher.go
read and update deleteConfig and disableSync from configmap
> AV-196227 HandleConfigMap with AKO-gateway-api

- internal/status/route_status.go
As part of this PR, AKO will populate status and annotations of route with vs uuid and controller uuid to have backward compatibility with AMKO during upgrade.
> AV-199362: Route Status Reason field update with vsuuid and controller uuid

- ako-gateway-api/nodes/gateway_model.go
- internal/nodes/avi_model_evh_nodes.go
- internal/rest/avi_evh_obj.go
- internal/rest/dequeue_nodes.go
- pkg/utils/constants.go
- pkg/utils/types.go
> AV-202495: Fix Panic when avi controller returns error during object creation.

- internal/rest/dequeue_nodes.go
Manually tested with a expired certificate in secure ingress .
> AV-202495 check object type before the typecast

- internal/nodes/avi_model_l7_hostname_shard.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_model_tls_passthrough.go
> AV-203152: Fix: Failure in creating Virtual service, PG and other pools if name of one of the pool exceeds maximum avi controller length limit

- cmd/ako-main/main.go
- internal/lib/control_config.go
- internal/lib/lib.go
With this PR, log message will be printed during bootup only.
> Reducing number of Promethues enabled/disabled log messages

- internal/objects/store.go
> AV-121758: AKO Pod restarted due to panic due to indexing issue. Copy object instead of sending reference

- ako-gateway-api/k8s/ako_init.go
- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/constants.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/objects/gateway_store.go
- ako-gateway-api/status/gateway_status.go
- internal/lib/constants.go
- pkg/utils/utils.go
- tests/gatewayapitests/status/httproute_test.go
- Gw names in store must with prefixed with namespaces
- Listener names outside gateway in store must with prefixed with namespaces
- Update listener store object instead of string manipulation for better readability
- Make a common function to delete all gateway related mappings, this also fixes some mappings
- Make a common function to update/delete all httproute related mappings, this also fixes some mappings
- Add gateway to hostname list mapping to be used for overlap check
- Route to gateway mappings not being properly updated when route is updated 
- Add the sort functions during new sync
- Add port from listener to vhmatch
- Add IPv6 validation on static ip for gateway
- Fix ports being appeneded instead of making union on parent vs creation
- fix gateway status appending …
> AV-199417 Bug fixes for AKO gateway

- internal/status/svc_status.go
this PR addresses the issue AKO was updating the same status with IPv4 IP and then IPv6 IP resulting in only one IP added to the status at a time.
> AV-204987 LBSvc status fix for dualstack IPs

- Dockerfile.ako
- Dockerfile.ako-infra
- Dockerfile.ako-operator
- Makefile
- buildsettings.json
- docs/README.md
- docs/ako_ha.md
- docs/install/helm.md
- docs/openshift/openshift_helm.md
- internal/nodes/avi_vrf_translator.go
- tests/cnitests/static_route_test.go
- version.yaml
AV-205437 Static Route fixes
This PR fixes index outofbound error causing panic if indexes are not updated properly.
Adds a unit testcase to simulate the panic
Upgrades AKO version from 1.10.3 to 1.10.4
> AV-205437 Static Route fixes

- docs/crds/l4rule.md
> AV-204388: Documentation: Apply L4 CRD deployed in one namespace into other ns objects

- AKO_GATEWAY_CHANGELOG.md
- docs/gateway-api/gateway-api-v1.md
AV-203576 Documentation update for Gateway
> AV-203576 Documentation update for Gateway

- CHANGELOG.md
> AV-205437 Changelog Update

- internal/lib/constants.go
- internal/nodes/avi_model_l4_translator.go
- internal/rest/avi_obj_vs.go
- tests/integrationtest/l4_crd_test.go
- tests/integrationtest/lib.go
This PR is cherry-pick for https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1437
> AV-207450 : L4Rule with SSL enabled not applied to L4 VS if license type is Enterprise with Cloud Services

- internal/nodes/avi_model_advl4_translator.go
- internal/nodes/avi_model_l4_translator.go
- tests/integrationtest/l4_service_test.go
> AV-207312: Fix AKO crash in NSX-T shared L4 vip environment with no subdomain configured

- ako-gateway-api/nodes/avi_model_l7_translator.go
AV-209065 Gateway container crash fix
> AV-209065 Gateway container crash fix

- buildsettings.json
> AKO 1.13.1: Change min and max version of K8s and AviController as per AKO 1.13.1 release

- ako_cicd/jenkins/ci-build/ci-build.sh
- ako_cicd/jenkins/ci-build/save_build_on_registry.sh
- ako_cicd/jenkins/ci-build/srp/save_and_submit_srp_data.sh
Test Run: https://prodjenkins.eng.vmware.com:8443/job/ako_OS-master-ci-build/705/
> ako gateway api image changes

- ako-gateway-api/nodes/gateway_model_rel.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/gatewayclass_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
> AV-210402: Release-1.12.2: Fix: AKO-Gw: Child VS creation fails with duplicate FQDN in VHMatch creation

- ako-gateway-api/k8s/validator.go
- ako-gateway-api/lib/lib.go
- ako-gateway-api/nodes/avi_model_l4_translator.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/dequeue_ingestion.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/objects/gateway_store.go
- pkg/utils/constants.go
- pkg/utils/utils.go
- tests/gatewayapitests/graphlayer/gateway_test.go
- tests/gatewayapitests/graphlayer/gatewayclass_test.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/gateway_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/gateway_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
TODO:
1. write down function for hostname at gateway and httproute empty --> Done
2. Write down UT for graphlayer. --> Done
3. Deletion functionality for HTTP Route mapped with Parent VS --> Done
> AV-209062: Wildcard fqdn support in Gateway

- ako-clean/cleanup.go
- internal/lib/avi_api.go
- internal/rest/rest_operation.go
- pkg/utils/avi_rest_utils.go
- pkg/utils/utils.go
- tests/integrationtest/lib.go
- tests/scaletest/lib/utils.go
Add URI encoding to rest calls to support resource names in AVI 30.x
> AV-212214 Add URI encoding to rest calls

- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/objects/gateway_store.go
> AV-214519: AKO GW pod crashed with panic : interface {} is nil, not [……]objects.GatewayListenerStore

- tests/advl4tests/advl4_hostname_test.go
this PR isolates changes required for https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1339 
file changes for advl4tests 
- replace service names with suffixed names
- replace gateway names with suffixed names
- replace gatewayClass names with suffixed names
UT run for advl4tests
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/advl4tests    47.849s
> AV-210932 Improve UT runtime (advl4tests)

- Makefile
- internal/lib/lib.go
> AV-214469: Fix concurrent map read and write in vip network and node network map

- tests/integrationtest/lib.go
- tests/servicesapitests/servicesapi_l4_test.go
file changes for servicesapitests
UT results
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/servicesapitests      80.254s
> AV-210932 Improve UT runtime (servicesapitests)

- tests/integrationtest/lib.go
- tests/multitenancytests/multitenancy_infrasetting_ako_svc_test.go
- tests/multitenancytests/multitenancy_infrasetting_evh_test.go
- tests/multitenancytests/multitenancy_infrasetting_ingress_test.go
file changes for multitenancytests
UT results
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/multitenancytests     71.828s
> AV-210932 Improve UT runtime (multitenancytests)

- tests/integrationtest/l4_crd_test.go
- tests/integrationtest/l4_nodeport_service_test.go
- tests/integrationtest/l4_service_test.go
- tests/integrationtest/lib.go
- tests/integrationtest/static_route_test.go
file changes for integrationtests
UT results
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/integrationtest       500.357s
> AV-210932 Improve UT runtime (integrationtest)

- internal/lib/utils.go
- internal/status/ing_status.go
fix incorrect status update due to concurrency issue.
the issue was found when running the UT ingresstests::TestMultiHostIngressStatusCheck
concurrent threads were overwriting valid IP in status because updates were not atomic in nature and both referred to the same old ingress objects.
this is fixed in this PR by adding locks before status updates when same object is being updated by multiple threads and fetching the latest status before proceeding with the update
> AV-213944 Status update concurrency fix

- tests/gatewayapitests/graphlayer/httproute_test.go
```
aviuser@avi-dev:~/myfork/vhmatch$ make gatewayapitests 
sudo docker run \
-e ENDPOINTSLICES_ENABLED="false" \
-w=/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes \
-v /home/aviuser/myfork/vhmatch:/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes golang:bullseye \
go test -mod=vendor github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/... -failfast -timeout 0 -coverprofile cover-20.out -coverpkg=./...
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests               coverage: 0.0% of statements
ok      github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/tests/gatewayapitests/graphlayer    448.058s        coverage: 18.4% of statements in ./... …
```
> fix TestHTTPRouteWithValidConfig UT

- Makefile
- internal/k8s/controller.go
- tests/oshiftroutetests/oshift_secure_route_test.go
> AV-220793: Fix: Restricting FQDN functionality is not working as per expectation in openshift route update scenario

- Makefile
- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/lib/lib.go
- internal/lib/lib.go
- tests/dedicatedvstests/l7_dedicated_crd_test.go
- tests/dedicatedvstests/l7_dedicated_graph_test.go
- tests/dedicatedvstests/l7_dedicated_rest_test.go
- tests/evhtests/l7_evh_crd_test.go
- tests/evhtests/l7_evh_graph_test.go
- tests/npltests/npl_pod_test.go
Context:
Was enabling either EPS or Pod informer in NPL mode. 
Fix:
Enable both EPS and Pod informer in NPL mode(required). EP will be enabled only when NPL and EPS is disabled.
> AV-221886: Enable both EPSlice and pod informer on NPL mode

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_validator.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/status/httproute_test.go
> AV-220811: Remove code related with empty hostname at gateway listener and httproute

- ako_cicd/jenkins/ci-build/save_build_on_mnt.sh
fix(AV-224026): Added Read permission for other users on tar files
> fix(AV-224026): Added Read permission for other users on tar files

- AKO_GATEWAY_CHANGELOG.md
- docs/gateway-api/gateway-api-v1.md
AV-223112 Gateway API Documentation Update
> AV-223112 Gateway API Documentation Update

- internal/nodes/crd_translator.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
> AV-224167: Fix: AKO is crashing when hostrule, with LogAllHeader field in AnalyticsPolicy field, is applied to an ingress

- docs/gateway-api/gateway-api-v1.md
> Gateway document Update

- docs/gateway-api/gateway-api-v1.md
AV-228826 Gateway api documentation update
> AV-228826 Gateway api documentation update

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
TODO:
1. UT / FT for tenant name with special characters
2.  Run existing UTs
3.  As AviController now allows special character in each object name so we need to check whether to handle that or not.
> AV-228668: Fix: tenant name with special characters

- docs/troubleshooting/troubleshooting.md
AV-231510 Troubleshoot doc update for AV-230178
> AV-231510 Troubleshoot doc update for AV-230178

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/crd_translator.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
- tests/integrationtest/lib.go
> AV-231550: AKO doesn't apply hostrule with Shared Vs FQDN if there is no DNS present in the cloud

- internal/status/route_status.go
TO DO: Handle it for ingress also
> AV-228152 Check if Vs is present before bulk delete  of route status

- internal/cache/controller_obj_cache.go
- internal/lib/lib.go
- internal/rest/avi_datascript.go
- internal/rest/avi_evh_obj.go
- internal/rest/avi_obj_httpps.go
- internal/rest/avi_obj_l4ps.go
- internal/rest/avi_obj_pool.go
- internal/rest/avi_obj_vs.go
- internal/rest/avi_obj_vsvip.go
- internal/rest/avi_pool_group.go
- internal/rest/ssl_key_certificate.go
* AV-228668: Fix: tenant name with special characters
* Review comments addressed
> AV-228668: Fix: tenant name with special characters (#1654)

- internal/lib/lib.go
- internal/nodes/avi_model_evh_nodes.go
- internal/nodes/avi_model_l7_translator.go
- internal/nodes/crd_translator.go
- tests/evhtests/l7_evh_crd_test.go
- tests/ingresstests/crd_test.go
- tests/integrationtest/lib.go
> AV-231550: AKO doesn't apply hostrule with Shared Vs FQDN if there is no DNS present in the cloud (Cherry Pick)

- internal/status/route_status.go
> AV-228152 Check if Vs is present in cache before bulk delete of route status

- internal/cache/controller_obj_cache.go
This PR fixes issue of stale StringGroup deletion. There were two causes of failure that are described below.
1) The **cloud_ref.name** field used in URI for getting all string groups while cache population was not a valid field for stringgroup and hence no stringgroups were fetched at bootup leading to failure in deletion of stale ones. The cloud_ref field was removed from the URI and the fix was tested by first creating ingress, hostrule with useRegex enabled, and other k8s resources. AKO creates the VS, stringgroup, and other avi objects. Later, AKO is scaled to zero pods and all k8s resources are deleted. AKO is scaled up to one pod again and AKO deletes all the stale objects including stringgroups.
2) There was another scenario which could arise even after fixing the URI in step 1. …
> AV-232211 : Stale string groups not getting cleaned on controller inspite of multiple AKO reboots

- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/nodes/route_validator.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
AV-231513 release-1.13.2 cherry pick
> AV-231513 release-1.13.2 cherry pick

- cmd/gateway-api/main.go
AV-232009 Fix label creation on SE group by Gateway container
> AV-232009 Fix label creation on SE group by Gateway container

- docs/gateway-api/gateway-api-v1.md
AV-232305 Gateway doc update with httproute rewrite filter limitations
> AV-232305 Gateway doc update with httproute rewrite filter limitations

- docs/gateway-api/gateway-api-v1.md
AV-232305 Gateway doc update with httproute rewrite filter limitation
> AV-232305 Gateway doc update with httproute rewrite filter limitation

- .github/workflows/go.yml
- internal/lib/utils.go
- internal/nodes/avi_model_nodes.go
- internal/nodes/avi_vrf_translator.go
- internal/nodes/dequeue_ingestion.go
- internal/rest/avi_obj_vrf.go
- tests/cnitests/static_route_test.go
- tests/integrationtest/static_route_test.go
AV-232614 Static Route fixes.- Cherry-pick
> AV-232614 Static Route fixes.- Cherry-pick

- docs/gateway-api/gateway-api-v1.md
AV-236996 Gateway API doc update
> AV-236996 Gateway API doc update

- internal/cache/controller_obj_cache.go
- internal/lib/avi_api.go
AV-237682 Disable se group label updation by follower ako
> AV-237682 Disable se group label updation by follower ako

- internal/cache/controller_obj_cache.go
The stack trace for panic can be seen below.
```
panic: interface conversion: interface {} is nil, not string
goroutine 129 [running]:
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/cache.(*AviObjCache).AviObjVSCachePopulate(0xc000175960, 0xc00049cf08, {0xc000054083, 0xd}, 0xc00048f968, {0x0, 0x0, 0x1dffb60?})
/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/cache/controller_obj_cache.go:2389 +0x3774
github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/cache.(*AviObjCache).AviObjCachePopulate.func1(0xc000175960, {0xc000054083, 0xd}, 0xc00048f968, 0xc00049cf08)
/go/src/github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/internal/cache/controller_obj_cache.go:146 +0x12a …
```
> AV-237408 : Avoid panic while cache population if httppolicyset uuid is empty in vs object

- ako-clean/cleanup.go
- cmd/clean-main/main.go
WCPSVC will only be sending 1 of clusterID or Supervisor ID
> Revert Cleanup Script changes

- ako-infra/avirest/netinfo_handler.go
- ako-infra/ingestion/avi_infra_controller.go
- ako-infra/ingestion/constants.go
- cmd/infra-main/main.go
- internal/k8s/ako_init.go
- internal/lib/constants.go
- internal/lib/lib.go
- pkg/utils/utils.go
- tests/infratests/akoinfra_test.go
Reverts vmware/load-balancer-and-ingress-services-for-kubernetes#1775
> Revert "Handle Supervisors across vCenter"

- internal/cache/controller_obj_cache.go
Cherry-pick from https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1834
> AV-244346 Skip VipNetworkList user input in VPC Mode

- CHANGELOG.md
- docs/values.md
- docs/vpc_mode.md
Cherry-pick from 
1. https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1830
2. https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/1838
CHANGELOG.
> AV-244081 Add vpc_mode.md and update vpcMode kb in values.md

- internal/cache/controller_obj_cache.go
- internal/rest/dequeue_nodes.go
- internal/rest/rest_operation.go
- pkg/apis/ako/v1alpha2/l7rule.go
- pkg/utils/utils.go
> AV-246069: Redact private key before logging

- ako-gateway-api/k8s/gateway_controller.go
- ako-gateway-api/k8s/gateway_crd_controller.go
- ako-gateway-api/lib/dynamic_client.go
- ako-gateway-api/nodes/avi_model_l7_translator.go
- ako-gateway-api/nodes/gateway_model_rel.go
- ako-gateway-api/nodes/route_model.go
- ako-gateway-api/nodes/route_validator.go
- ako-gateway-api/objects/gateway_store.go
- helm/ako/templates/clusterrole.yaml
- internal/nodes/avi_model_l7_hostname_shard.go
- pkg/utils/utils.go
- tests/gatewayapitests/graphlayer/httproute_test.go
- tests/gatewayapitests/ingestion/httproute_test.go
- tests/gatewayapitests/status/httproute_test.go
- tests/gatewayapitests/utils.go
- Integrates ApplicationProfiles to Gateway API.
- Adds graph, ingestion and status tests.
> AV-244023 Add Application Profile to Gateway API

- ako-gateway-api/nodes/avi_model_l7_dedicated_translator.go
- internal/cache/cache_utils.go
- pkg/utils/utils.go
This PR also fixes: https://vmw-jira.broadcom.net/browse/AV-249266
> AV-248349: Implement backend extension ref for dedicated mode

- internal/lib/lib.go
Fixes https://bugzilla-vcf.lvn.broadcom.net/show_bug.cgi?id=3587419
> [1.13.4] VKAL-32783 Handle enableEVH flag using strconv.ParseBool
